// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.1 (64-bit)
// Version: 2022.1
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module harris_filterSingle (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        GxxStream_dout,
        GxxStream_num_data_valid,
        GxxStream_fifo_cap,
        GxxStream_empty_n,
        GxxStream_read,
        SxxStream_din,
        SxxStream_num_data_valid,
        SxxStream_fifo_cap,
        SxxStream_full_n,
        SxxStream_write
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [255:0] GxxStream_dout;
input  [4:0] GxxStream_num_data_valid;
input  [4:0] GxxStream_fifo_cap;
input   GxxStream_empty_n;
output   GxxStream_read;
output  [255:0] SxxStream_din;
input  [4:0] SxxStream_num_data_valid;
input  [4:0] SxxStream_fifo_cap;
input   SxxStream_full_n;
output   SxxStream_write;

reg ap_idle;
reg GxxStream_read;
reg SxxStream_write;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_enable_reg_pp0_iter7;
reg    ap_enable_reg_pp0_iter8;
reg    ap_enable_reg_pp0_iter9;
reg    ap_enable_reg_pp0_iter10;
reg    ap_enable_reg_pp0_iter11;
reg    ap_idle_pp0;
reg    ap_done_reg;
reg    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
reg   [0:0] icmp_ln241_reg_1934;
reg   [0:0] icmp_ln241_reg_1934_pp0_iter1_reg;
reg   [0:0] icmp_ln244_reg_1976;
reg   [0:0] empty_62_reg_1986;
reg    ap_predicate_op69_read_state3;
reg    ap_block_state3_pp0_stage0_iter2;
wire    ap_block_state4_pp0_stage0_iter3;
wire    ap_block_state5_pp0_stage0_iter4;
wire    ap_block_state6_pp0_stage0_iter5;
wire    ap_block_state7_pp0_stage0_iter6;
wire    ap_block_state8_pp0_stage0_iter7;
wire    ap_block_state9_pp0_stage0_iter8;
wire    ap_block_state10_pp0_stage0_iter9;
wire    ap_block_state11_pp0_stage0_iter10;
reg   [0:0] select_ln234_3_reg_1972;
reg   [0:0] select_ln234_3_reg_1972_pp0_iter10_reg;
reg    ap_block_state12_pp0_stage0_iter11;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln241_fu_394_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    GxxStream_blk_n;
wire    ap_block_pp0_stage0;
reg    SxxStream_blk_n;
reg    ap_block_pp0_stage0_11001;
reg   [0:0] icmp_ln241_reg_1934_pp0_iter2_reg;
wire   [0:0] icmp_ln242_fu_412_p2;
reg   [0:0] icmp_ln242_reg_1938;
wire   [4:0] select_ln234_fu_418_p3;
reg   [4:0] select_ln234_reg_1943;
reg   [4:0] select_ln234_reg_1943_pp0_iter1_reg;
reg   [4:0] select_ln234_reg_1943_pp0_iter2_reg;
reg   [4:0] select_ln234_reg_1943_pp0_iter3_reg;
reg   [4:0] select_ln234_reg_1943_pp0_iter4_reg;
reg   [4:0] select_ln234_reg_1943_pp0_iter5_reg;
reg   [4:0] select_ln234_reg_1943_pp0_iter6_reg;
reg   [4:0] select_ln234_reg_1943_pp0_iter7_reg;
reg   [4:0] select_ln234_reg_1943_pp0_iter8_reg;
reg   [4:0] select_ln234_reg_1943_pp0_iter9_reg;
wire   [0:0] icmp_fu_442_p2;
reg   [0:0] icmp_reg_1950;
wire   [0:0] icmp48_fu_458_p2;
reg   [0:0] icmp48_reg_1955;
wire   [7:0] select_ln241_fu_464_p3;
reg   [7:0] select_ln241_reg_1960;
wire   [4:0] add_ln242_fu_472_p2;
reg   [4:0] add_ln242_reg_1967;
wire   [0:0] select_ln234_3_fu_483_p3;
reg   [0:0] select_ln234_3_reg_1972_pp0_iter2_reg;
reg   [0:0] select_ln234_3_reg_1972_pp0_iter3_reg;
reg   [0:0] select_ln234_3_reg_1972_pp0_iter4_reg;
reg   [0:0] select_ln234_3_reg_1972_pp0_iter5_reg;
reg   [0:0] select_ln234_3_reg_1972_pp0_iter6_reg;
reg   [0:0] select_ln234_3_reg_1972_pp0_iter7_reg;
reg   [0:0] select_ln234_3_reg_1972_pp0_iter8_reg;
reg   [0:0] select_ln234_3_reg_1972_pp0_iter9_reg;
wire   [0:0] icmp_ln244_fu_492_p2;
reg   [0:0] icmp_ln244_reg_1976_pp0_iter2_reg;
reg   [0:0] icmp_ln244_reg_1976_pp0_iter3_reg;
reg   [0:0] icmp_ln244_reg_1976_pp0_iter4_reg;
reg   [0:0] icmp_ln244_reg_1976_pp0_iter5_reg;
reg   [0:0] icmp_ln244_reg_1976_pp0_iter6_reg;
reg   [0:0] icmp_ln244_reg_1976_pp0_iter7_reg;
reg   [0:0] icmp_ln244_reg_1976_pp0_iter8_reg;
reg   [0:0] icmp_ln244_reg_1976_pp0_iter9_reg;
wire   [0:0] empty_62_fu_507_p2;
reg   [3:0] rowBuffer_addr_reg_1990;
reg   [3:0] rowBuffer_addr_reg_1990_pp0_iter2_reg;
wire   [31:0] obj_var_fu_521_p1;
reg   [511:0] tmp_62_i_reg_2036;
wire   [767:0] input_fu_605_p10;
reg   [31:0] tmp_135_i_reg_2046;
reg   [31:0] tmp_145_i_reg_2051;
reg   [31:0] tmp_155_i_reg_2056;
reg   [31:0] tmp_155_i_reg_2056_pp0_iter5_reg;
wire   [31:0] res_fu_1000_p2;
reg   [31:0] res_reg_2061;
reg   [31:0] res_reg_2061_pp0_iter5_reg;
wire   [31:0] res_91_fu_1012_p2;
reg   [31:0] res_91_reg_2067;
reg   [31:0] res_91_reg_2067_pp0_iter5_reg;
wire   [31:0] res_92_fu_1024_p2;
reg   [31:0] res_92_reg_2073;
wire   [31:0] res_93_fu_1036_p2;
reg   [31:0] res_93_reg_2079;
reg   [31:0] res_93_reg_2079_pp0_iter5_reg;
wire   [31:0] res_94_fu_1048_p2;
reg   [31:0] res_94_reg_2086;
wire   [31:0] res_95_fu_1060_p2;
reg   [31:0] res_95_reg_2093;
wire   [31:0] res_96_fu_1072_p2;
reg   [31:0] res_96_reg_2100;
wire   [31:0] res_97_fu_1084_p2;
reg   [31:0] res_97_reg_2107;
wire   [31:0] add_ln113_51_fu_1096_p2;
reg   [31:0] add_ln113_51_reg_2113;
wire   [31:0] add_ln113_37_fu_1111_p2;
reg   [31:0] add_ln113_37_reg_2118;
wire   [31:0] add_ln113_30_fu_1116_p2;
reg   [31:0] add_ln113_30_reg_2123;
wire   [31:0] add_ln113_42_fu_1124_p2;
reg   [31:0] add_ln113_42_reg_2129;
wire   [31:0] add_ln113_44_fu_1133_p2;
reg   [31:0] add_ln113_44_reg_2135;
wire   [31:0] add_ln113_46_fu_1142_p2;
reg   [31:0] add_ln113_46_reg_2141;
wire   [31:0] add_ln113_48_fu_1151_p2;
reg   [31:0] add_ln113_48_reg_2147;
wire   [31:0] add_ln113_52_fu_1160_p2;
reg   [31:0] add_ln113_52_reg_2153;
wire   [31:0] add_ln113_38_fu_1169_p2;
reg   [31:0] add_ln113_38_reg_2159;
wire   [31:0] add_ln113_39_fu_1174_p2;
reg   [31:0] add_ln113_39_reg_2165;
wire   [31:0] add_ln113_40_fu_1178_p2;
reg   [31:0] add_ln113_40_reg_2171;
wire   [31:0] res_110_fu_1187_p2;
reg   [31:0] res_110_reg_2177;
reg   [25:0] trunc_ln91_6_reg_2182;
wire   [31:0] res_114_fu_1207_p2;
reg   [31:0] res_114_reg_2187;
reg   [25:0] trunc_ln91_7_reg_2192;
wire   [31:0] res_118_fu_1227_p2;
reg   [31:0] res_118_reg_2197;
reg   [25:0] trunc_ln91_8_reg_2202;
wire   [31:0] res_122_fu_1247_p2;
reg   [31:0] res_122_reg_2207;
reg   [25:0] trunc_ln91_9_reg_2212;
wire   [31:0] res_126_fu_1267_p2;
reg   [31:0] res_126_reg_2217;
reg   [25:0] trunc_ln91_1_reg_2222;
wire   [31:0] res_98_fu_1287_p2;
reg   [31:0] res_98_reg_2227;
reg   [25:0] trunc_ln_reg_2232;
wire   [31:0] res_102_fu_1307_p2;
reg   [31:0] res_102_reg_2237;
reg   [25:0] trunc_ln91_s_reg_2242;
wire   [31:0] res_106_fu_1327_p2;
reg   [31:0] res_106_reg_2247;
reg   [25:0] trunc_ln91_5_reg_2252;
wire   [31:0] res_111_fu_1345_p2;
reg   [31:0] res_111_reg_2257;
reg   [19:0] trunc_ln92_6_reg_2262;
wire   [31:0] res_115_fu_1363_p2;
reg   [31:0] res_115_reg_2267;
reg   [19:0] trunc_ln92_7_reg_2272;
wire   [31:0] res_119_fu_1381_p2;
reg   [31:0] res_119_reg_2277;
reg   [19:0] trunc_ln92_8_reg_2282;
wire   [31:0] res_123_fu_1399_p2;
reg   [31:0] res_123_reg_2287;
reg   [19:0] trunc_ln92_9_reg_2292;
wire   [31:0] res_127_fu_1417_p2;
reg   [31:0] res_127_reg_2297;
reg   [19:0] trunc_ln92_1_reg_2302;
wire   [31:0] res_99_fu_1435_p2;
reg   [31:0] res_99_reg_2307;
reg   [19:0] trunc_ln6_reg_2312;
wire   [31:0] res_103_fu_1453_p2;
reg   [31:0] res_103_reg_2317;
reg   [19:0] trunc_ln92_s_reg_2322;
wire   [31:0] res_107_fu_1471_p2;
reg   [31:0] res_107_reg_2327;
reg   [19:0] trunc_ln92_5_reg_2332;
wire   [31:0] res_112_fu_1489_p2;
reg   [31:0] res_112_reg_2337;
reg   [7:0] trunc_ln93_6_reg_2342;
wire   [31:0] res_116_fu_1507_p2;
reg   [31:0] res_116_reg_2347;
reg   [7:0] trunc_ln93_7_reg_2352;
wire   [31:0] res_120_fu_1525_p2;
reg   [31:0] res_120_reg_2357;
reg   [7:0] trunc_ln93_8_reg_2362;
wire   [31:0] res_124_fu_1543_p2;
reg   [31:0] res_124_reg_2367;
reg   [7:0] trunc_ln93_9_reg_2372;
wire   [31:0] res_128_fu_1561_p2;
reg   [31:0] res_128_reg_2377;
reg   [7:0] trunc_ln93_1_reg_2382;
wire   [31:0] res_100_fu_1579_p2;
reg   [31:0] res_100_reg_2387;
reg   [7:0] trunc_ln7_reg_2392;
wire   [31:0] res_104_fu_1597_p2;
reg   [31:0] res_104_reg_2397;
reg   [7:0] trunc_ln93_s_reg_2402;
wire   [31:0] res_108_fu_1615_p2;
reg   [31:0] res_108_reg_2407;
reg   [7:0] trunc_ln93_5_reg_2412;
reg   [23:0] trunc_ln292_s_reg_2417;
reg   [23:0] trunc_ln292_1_reg_2422;
reg   [23:0] trunc_ln292_2_reg_2427;
reg   [23:0] trunc_ln292_3_reg_2432;
reg   [23:0] trunc_ln292_4_reg_2437;
wire   [23:0] res_S_var_7_fu_1759_p3;
reg   [23:0] res_S_var_7_reg_2442;
wire   [23:0] res_S_var_9_fu_1782_p3;
reg   [23:0] res_S_var_9_reg_2447;
wire   [23:0] select_ln287_fu_1800_p3;
reg   [23:0] select_ln287_reg_2452;
wire   [23:0] select_ln289_fu_1808_p3;
reg   [23:0] select_ln289_reg_2457;
wire   [23:0] select_ln289_9_fu_1814_p3;
reg   [23:0] select_ln289_9_reg_2462;
wire   [23:0] select_ln289_10_fu_1820_p3;
reg   [23:0] select_ln289_10_reg_2467;
wire   [23:0] select_ln289_11_fu_1826_p3;
reg   [23:0] select_ln289_11_reg_2472;
wire   [23:0] select_ln289_12_fu_1832_p3;
reg   [23:0] select_ln289_12_reg_2477;
reg    rowBuffer_ce0;
reg    rowBuffer_we0;
wire   [767:0] rowBuffer_d0;
wire   [3:0] rowBuffer_address1;
reg    rowBuffer_ce1;
wire   [767:0] rowBuffer_q1;
wire   [31:0] ap_phi_reg_pp0_iter0_obj_var_13_reg_277;
reg   [31:0] ap_phi_reg_pp0_iter1_obj_var_13_reg_277;
reg   [31:0] ap_phi_reg_pp0_iter2_obj_var_13_reg_277;
reg   [31:0] ap_phi_reg_pp0_iter3_obj_var_13_reg_277;
wire   [31:0] ap_phi_reg_pp0_iter0_obj_var_12_reg_288;
reg   [31:0] ap_phi_reg_pp0_iter1_obj_var_12_reg_288;
reg   [31:0] ap_phi_reg_pp0_iter2_obj_var_12_reg_288;
reg   [31:0] ap_phi_reg_pp0_iter3_obj_var_12_reg_288;
wire   [31:0] ap_phi_reg_pp0_iter0_obj_sroa_6_0_i_reg_299;
reg   [31:0] ap_phi_reg_pp0_iter1_obj_sroa_6_0_i_reg_299;
reg   [31:0] ap_phi_reg_pp0_iter2_obj_sroa_6_0_i_reg_299;
reg   [31:0] ap_phi_reg_pp0_iter3_obj_sroa_6_0_i_reg_299;
wire   [31:0] ap_phi_reg_pp0_iter0_obj_sroa_9_0_i_reg_310;
reg   [31:0] ap_phi_reg_pp0_iter1_obj_sroa_9_0_i_reg_310;
reg   [31:0] ap_phi_reg_pp0_iter2_obj_sroa_9_0_i_reg_310;
reg   [31:0] ap_phi_reg_pp0_iter3_obj_sroa_9_0_i_reg_310;
wire   [31:0] ap_phi_reg_pp0_iter0_obj_sroa_12_0_i_reg_321;
reg   [31:0] ap_phi_reg_pp0_iter1_obj_sroa_12_0_i_reg_321;
reg   [31:0] ap_phi_reg_pp0_iter2_obj_sroa_12_0_i_reg_321;
reg   [31:0] ap_phi_reg_pp0_iter3_obj_sroa_12_0_i_reg_321;
wire   [31:0] ap_phi_reg_pp0_iter0_obj_sroa_15_0_i_reg_332;
reg   [31:0] ap_phi_reg_pp0_iter1_obj_sroa_15_0_i_reg_332;
reg   [31:0] ap_phi_reg_pp0_iter2_obj_sroa_15_0_i_reg_332;
reg   [31:0] ap_phi_reg_pp0_iter3_obj_sroa_15_0_i_reg_332;
wire   [31:0] ap_phi_reg_pp0_iter0_obj_sroa_18_0_i_reg_343;
reg   [31:0] ap_phi_reg_pp0_iter1_obj_sroa_18_0_i_reg_343;
reg   [31:0] ap_phi_reg_pp0_iter2_obj_sroa_18_0_i_reg_343;
reg   [31:0] ap_phi_reg_pp0_iter3_obj_sroa_18_0_i_reg_343;
wire   [31:0] ap_phi_reg_pp0_iter0_obj_sroa_21_0_i_reg_354;
reg   [31:0] ap_phi_reg_pp0_iter1_obj_sroa_21_0_i_reg_354;
reg   [31:0] ap_phi_reg_pp0_iter2_obj_sroa_21_0_i_reg_354;
reg   [31:0] ap_phi_reg_pp0_iter3_obj_sroa_21_0_i_reg_354;
wire   [767:0] ap_phi_reg_pp0_iter0_input_3_reg_365;
reg   [767:0] ap_phi_reg_pp0_iter1_input_3_reg_365;
reg   [767:0] ap_phi_reg_pp0_iter2_input_3_reg_365;
reg   [767:0] ap_phi_reg_pp0_iter3_input_3_reg_365;
reg   [767:0] ap_phi_reg_pp0_iter4_input_3_reg_365;
wire   [63:0] trunc_ln244_cast_i_fu_488_p1;
reg   [4:0] j_fu_228;
reg   [4:0] ap_sig_allocacmp_j_load;
wire    ap_loop_init;
reg   [7:0] i_fu_232;
reg   [7:0] ap_sig_allocacmp_i_load;
reg   [11:0] indvar_flatten_fu_236;
wire   [11:0] add_ln241_fu_400_p2;
reg   [11:0] ap_sig_allocacmp_indvar_flatten_load;
reg   [1535:0] windowBuffer_fu_240;
wire   [1535:0] windowBuffer_5_fu_978_p7;
reg    ap_block_pp0_stage0_01001;
wire   [7:0] add_ln241_3_fu_426_p2;
wire   [6:0] tmp_fu_432_p4;
wire   [6:0] tmp_26_fu_448_p4;
wire   [0:0] empty_61_fu_502_p2;
wire   [0:0] empty_fu_497_p2;
wire   [255:0] tmp_63_i_fu_924_p4;
wire   [255:0] tmp_64_i_fu_934_p4;
wire   [255:0] tmp_65_i_fu_944_p4;
wire   [255:0] tmp_66_i_fu_954_p4;
wire   [255:0] trunc_ln55_3_fu_974_p1;
wire   [255:0] tmp_68_i_fu_964_p4;
wire   [31:0] tmp_137_i_fu_704_p4;
wire   [31:0] tmp_157_i_fu_904_p4;
wire   [31:0] add_ln109_fu_994_p2;
wire   [31:0] tmp_147_i_fu_804_p4;
wire   [31:0] trunc_ln55_fu_630_p1;
wire   [31:0] tmp_149_i_fu_824_p4;
wire   [31:0] add_ln109_32_fu_1006_p2;
wire   [31:0] tmp_139_i_fu_724_p4;
wire   [31:0] tmp_130_i_fu_634_p4;
wire   [31:0] tmp_150_i_fu_834_p4;
wire   [31:0] add_ln109_34_fu_1018_p2;
wire   [31:0] tmp_140_i_fu_734_p4;
wire   [31:0] tmp_131_i_fu_644_p4;
wire   [31:0] tmp_151_i_fu_844_p4;
wire   [31:0] add_ln109_36_fu_1030_p2;
wire   [31:0] tmp_141_i_fu_744_p4;
wire   [31:0] tmp_132_i_fu_654_p4;
wire   [31:0] tmp_152_i_fu_854_p4;
wire   [31:0] add_ln109_38_fu_1042_p2;
wire   [31:0] tmp_142_i_fu_754_p4;
wire   [31:0] tmp_133_i_fu_664_p4;
wire   [31:0] tmp_153_i_fu_864_p4;
wire   [31:0] add_ln109_40_fu_1054_p2;
wire   [31:0] tmp_143_i_fu_764_p4;
wire   [31:0] tmp_134_i_fu_674_p4;
wire   [31:0] tmp_154_i_fu_874_p4;
wire   [31:0] add_ln109_42_fu_1066_p2;
wire   [31:0] tmp_144_i_fu_774_p4;
wire   [31:0] tmp_136_i_fu_694_p4;
wire   [31:0] tmp_156_i_fu_894_p4;
wire   [31:0] add_ln109_44_fu_1078_p2;
wire   [31:0] tmp_146_i_fu_794_p4;
wire   [31:0] tmp_148_i_fu_814_p4;
wire   [31:0] tmp_158_i_fu_914_p4;
wire   [31:0] add_ln113_50_fu_1090_p2;
wire   [31:0] tmp_138_i_fu_714_p4;
wire   [31:0] add_ln113_36_fu_1107_p2;
wire   [31:0] add_ln113_41_fu_1120_p2;
wire   [31:0] add_ln113_43_fu_1129_p2;
wire   [31:0] add_ln113_45_fu_1138_p2;
wire   [31:0] add_ln113_47_fu_1147_p2;
wire   [31:0] add_ln113_49_fu_1156_p2;
wire   [31:0] add_ln113_fu_1165_p2;
wire   [31:0] shl_ln90_17_fu_1182_p2;
wire   [31:0] shl_ln90_18_fu_1202_p2;
wire   [31:0] shl_ln90_19_fu_1222_p2;
wire   [31:0] shl_ln90_20_fu_1242_p2;
wire   [31:0] shl_ln90_21_fu_1262_p2;
wire   [31:0] shl_ln90_fu_1282_p2;
wire   [31:0] shl_ln90_15_fu_1302_p2;
wire   [31:0] shl_ln90_16_fu_1322_p2;
wire  signed [31:0] sext_ln91_17_fu_1342_p1;
wire  signed [31:0] sext_ln91_18_fu_1360_p1;
wire  signed [31:0] sext_ln91_19_fu_1378_p1;
wire  signed [31:0] sext_ln91_20_fu_1396_p1;
wire  signed [31:0] sext_ln91_21_fu_1414_p1;
wire  signed [31:0] sext_ln91_fu_1432_p1;
wire  signed [31:0] sext_ln91_15_fu_1450_p1;
wire  signed [31:0] sext_ln91_16_fu_1468_p1;
wire  signed [31:0] sext_ln92_17_fu_1486_p1;
wire  signed [31:0] sext_ln92_18_fu_1504_p1;
wire  signed [31:0] sext_ln92_19_fu_1522_p1;
wire  signed [31:0] sext_ln92_20_fu_1540_p1;
wire  signed [31:0] sext_ln92_21_fu_1558_p1;
wire  signed [31:0] sext_ln92_fu_1576_p1;
wire  signed [31:0] sext_ln92_15_fu_1594_p1;
wire  signed [31:0] sext_ln92_16_fu_1612_p1;
wire  signed [31:0] sext_ln93_17_fu_1630_p1;
wire  signed [31:0] sext_ln93_18_fu_1638_p1;
wire  signed [31:0] sext_ln93_19_fu_1646_p1;
wire  signed [31:0] sext_ln93_20_fu_1654_p1;
wire  signed [31:0] sext_ln93_21_fu_1662_p1;
wire   [31:0] res_113_fu_1633_p2;
wire   [31:0] res_117_fu_1641_p2;
wire   [31:0] res_121_fu_1649_p2;
wire   [31:0] res_125_fu_1657_p2;
wire   [31:0] res_129_fu_1665_p2;
wire  signed [31:0] sext_ln93_fu_1720_p1;
wire  signed [31:0] sext_ln93_15_fu_1728_p1;
wire  signed [31:0] sext_ln93_16_fu_1736_p1;
wire   [31:0] res_101_fu_1723_p2;
wire   [0:0] cmp96_i_fu_1744_p2;
wire   [23:0] res_S_var_fu_1749_p4;
wire   [31:0] res_105_fu_1731_p2;
wire   [0:0] or_ln287_fu_1777_p2;
wire   [23:0] res_S_var_8_fu_1767_p4;
wire   [31:0] res_109_fu_1739_p2;
wire   [23:0] trunc_ln8_fu_1790_p4;
wire  signed [31:0] sext_ln174_19_fu_1844_p1;
wire   [55:0] tmp_s_fu_1847_p3;
wire  signed [63:0] sext_ln174_20_fu_1854_p1;
wire   [87:0] tmp_22_fu_1858_p3;
wire  signed [95:0] sext_ln174_21_fu_1865_p1;
wire   [119:0] tmp_23_fu_1869_p3;
wire  signed [127:0] sext_ln174_22_fu_1876_p1;
wire   [151:0] tmp_24_fu_1880_p3;
wire  signed [159:0] sext_ln174_23_fu_1887_p1;
wire  signed [31:0] sext_ln174_fu_1841_p1;
wire  signed [31:0] sext_ln233_fu_1838_p1;
wire   [247:0] tmp_25_fu_1891_p5;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg    ap_loop_exit_ready_pp0_iter5_reg;
reg    ap_loop_exit_ready_pp0_iter6_reg;
reg    ap_loop_exit_ready_pp0_iter7_reg;
reg    ap_loop_exit_ready_pp0_iter8_reg;
reg    ap_loop_exit_ready_pp0_iter9_reg;
reg    ap_loop_exit_ready_pp0_iter10_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
reg    ap_condition_492;
reg    ap_condition_496;
reg    ap_condition_82;
reg    ap_condition_488;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
#0 ap_enable_reg_pp0_iter8 = 1'b0;
#0 ap_enable_reg_pp0_iter9 = 1'b0;
#0 ap_enable_reg_pp0_iter10 = 1'b0;
#0 ap_enable_reg_pp0_iter11 = 1'b0;
#0 ap_done_reg = 1'b0;
end

harris_sobel_rowBuffer_RAM_AUTO_1R1W #(
    .DataWidth( 768 ),
    .AddressRange( 16 ),
    .AddressWidth( 4 ))
rowBuffer_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(rowBuffer_addr_reg_1990_pp0_iter2_reg),
    .ce0(rowBuffer_ce0),
    .we0(rowBuffer_we0),
    .d0(rowBuffer_d0),
    .address1(rowBuffer_address1),
    .ce1(rowBuffer_ce1),
    .q1(rowBuffer_q1)
);

harris_flow_control_loop_pipe flow_control_loop_pipe_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int),
    .ap_continue(ap_continue)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready_pp0_iter10_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter10 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter10 <= ap_enable_reg_pp0_iter9;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter11 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter11 <= ap_enable_reg_pp0_iter10;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter7 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter8 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter9 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_492)) begin
        if (((icmp_ln241_reg_1934 == 1'd0) & (icmp_ln244_fu_492_p2 == 1'd1))) begin
            ap_phi_reg_pp0_iter2_input_3_reg_365 <= 768'd0;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter2_input_3_reg_365 <= ap_phi_reg_pp0_iter1_input_3_reg_365;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_492)) begin
        if ((1'b1 == ap_condition_496)) begin
            ap_phi_reg_pp0_iter2_obj_sroa_12_0_i_reg_321 <= 32'd0;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter2_obj_sroa_12_0_i_reg_321 <= ap_phi_reg_pp0_iter1_obj_sroa_12_0_i_reg_321;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_492)) begin
        if ((1'b1 == ap_condition_496)) begin
            ap_phi_reg_pp0_iter2_obj_sroa_15_0_i_reg_332 <= 32'd0;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter2_obj_sroa_15_0_i_reg_332 <= ap_phi_reg_pp0_iter1_obj_sroa_15_0_i_reg_332;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_492)) begin
        if ((1'b1 == ap_condition_496)) begin
            ap_phi_reg_pp0_iter2_obj_sroa_18_0_i_reg_343 <= 32'd0;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter2_obj_sroa_18_0_i_reg_343 <= ap_phi_reg_pp0_iter1_obj_sroa_18_0_i_reg_343;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_492)) begin
        if ((1'b1 == ap_condition_496)) begin
            ap_phi_reg_pp0_iter2_obj_sroa_21_0_i_reg_354 <= 32'd0;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter2_obj_sroa_21_0_i_reg_354 <= ap_phi_reg_pp0_iter1_obj_sroa_21_0_i_reg_354;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_492)) begin
        if ((1'b1 == ap_condition_496)) begin
            ap_phi_reg_pp0_iter2_obj_sroa_6_0_i_reg_299 <= 32'd0;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter2_obj_sroa_6_0_i_reg_299 <= ap_phi_reg_pp0_iter1_obj_sroa_6_0_i_reg_299;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_492)) begin
        if ((1'b1 == ap_condition_496)) begin
            ap_phi_reg_pp0_iter2_obj_sroa_9_0_i_reg_310 <= 32'd0;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter2_obj_sroa_9_0_i_reg_310 <= ap_phi_reg_pp0_iter1_obj_sroa_9_0_i_reg_310;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_492)) begin
        if ((1'b1 == ap_condition_496)) begin
            ap_phi_reg_pp0_iter2_obj_var_12_reg_288 <= 32'd0;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter2_obj_var_12_reg_288 <= ap_phi_reg_pp0_iter1_obj_var_12_reg_288;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_492)) begin
        if ((1'b1 == ap_condition_496)) begin
            ap_phi_reg_pp0_iter2_obj_var_13_reg_277 <= 32'd0;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter2_obj_var_13_reg_277 <= ap_phi_reg_pp0_iter1_obj_var_13_reg_277;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if ((1'b1 == ap_condition_82)) begin
            ap_phi_reg_pp0_iter3_obj_sroa_12_0_i_reg_321 <= {{GxxStream_dout[159:128]}};
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter3_obj_sroa_12_0_i_reg_321 <= ap_phi_reg_pp0_iter2_obj_sroa_12_0_i_reg_321;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if ((1'b1 == ap_condition_82)) begin
            ap_phi_reg_pp0_iter3_obj_sroa_15_0_i_reg_332 <= {{GxxStream_dout[191:160]}};
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter3_obj_sroa_15_0_i_reg_332 <= ap_phi_reg_pp0_iter2_obj_sroa_15_0_i_reg_332;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if ((1'b1 == ap_condition_82)) begin
            ap_phi_reg_pp0_iter3_obj_sroa_18_0_i_reg_343 <= {{GxxStream_dout[223:192]}};
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter3_obj_sroa_18_0_i_reg_343 <= ap_phi_reg_pp0_iter2_obj_sroa_18_0_i_reg_343;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if ((1'b1 == ap_condition_82)) begin
            ap_phi_reg_pp0_iter3_obj_sroa_21_0_i_reg_354 <= {{GxxStream_dout[255:224]}};
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter3_obj_sroa_21_0_i_reg_354 <= ap_phi_reg_pp0_iter2_obj_sroa_21_0_i_reg_354;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if ((1'b1 == ap_condition_82)) begin
            ap_phi_reg_pp0_iter3_obj_sroa_6_0_i_reg_299 <= {{GxxStream_dout[95:64]}};
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter3_obj_sroa_6_0_i_reg_299 <= ap_phi_reg_pp0_iter2_obj_sroa_6_0_i_reg_299;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if ((1'b1 == ap_condition_82)) begin
            ap_phi_reg_pp0_iter3_obj_sroa_9_0_i_reg_310 <= {{GxxStream_dout[127:96]}};
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter3_obj_sroa_9_0_i_reg_310 <= ap_phi_reg_pp0_iter2_obj_sroa_9_0_i_reg_310;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if ((1'b1 == ap_condition_82)) begin
            ap_phi_reg_pp0_iter3_obj_var_12_reg_288 <= {{GxxStream_dout[63:32]}};
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter3_obj_var_12_reg_288 <= ap_phi_reg_pp0_iter2_obj_var_12_reg_288;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if ((1'b1 == ap_condition_82)) begin
            ap_phi_reg_pp0_iter3_obj_var_13_reg_277 <= obj_var_fu_521_p1;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter3_obj_var_13_reg_277 <= ap_phi_reg_pp0_iter2_obj_var_13_reg_277;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if (((icmp_ln244_reg_1976_pp0_iter2_reg == 1'd0) & (icmp_ln241_reg_1934_pp0_iter2_reg == 1'd0))) begin
            ap_phi_reg_pp0_iter4_input_3_reg_365 <= input_fu_605_p10;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter4_input_3_reg_365 <= ap_phi_reg_pp0_iter3_input_3_reg_365;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if (((ap_loop_init == 1'b1) & (ap_start_int == 1'b1))) begin
            i_fu_232 <= 8'd0;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            i_fu_232 <= select_ln241_reg_1960;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_488)) begin
        if ((icmp_ln241_fu_394_p2 == 1'd0)) begin
            indvar_flatten_fu_236 <= add_ln241_fu_400_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten_fu_236 <= 12'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if (((ap_loop_init == 1'b1) & (ap_start_int == 1'b1))) begin
            j_fu_228 <= 5'd0;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            j_fu_228 <= add_ln242_reg_1967;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((select_ln234_3_reg_1972_pp0_iter4_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        add_ln113_30_reg_2123 <= add_ln113_30_fu_1116_p2;
        add_ln113_37_reg_2118 <= add_ln113_37_fu_1111_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((select_ln234_3_reg_1972_pp0_iter5_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        add_ln113_38_reg_2159 <= add_ln113_38_fu_1169_p2;
        add_ln113_39_reg_2165 <= add_ln113_39_fu_1174_p2;
        add_ln113_40_reg_2171 <= add_ln113_40_fu_1178_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln244_reg_1976_pp0_iter4_reg == 1'd0) & (select_ln234_3_reg_1972_pp0_iter4_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        add_ln113_42_reg_2129 <= add_ln113_42_fu_1124_p2;
        add_ln113_44_reg_2135 <= add_ln113_44_fu_1133_p2;
        add_ln113_46_reg_2141 <= add_ln113_46_fu_1142_p2;
        add_ln113_48_reg_2147 <= add_ln113_48_fu_1151_p2;
        add_ln113_52_reg_2153 <= add_ln113_52_fu_1160_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln244_reg_1976_pp0_iter3_reg == 1'd0) & (select_ln234_3_reg_1972_pp0_iter3_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        add_ln113_51_reg_2113 <= add_ln113_51_fu_1096_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln241_fu_394_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        add_ln242_reg_1967 <= add_ln242_fu_472_p2;
        icmp48_reg_1955 <= icmp48_fu_458_p2;
        icmp_ln242_reg_1938 <= icmp_ln242_fu_412_p2;
        icmp_reg_1950 <= icmp_fu_442_p2;
        select_ln234_reg_1943 <= select_ln234_fu_418_p3;
        select_ln241_reg_1960 <= select_ln241_fu_464_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        ap_loop_exit_ready_pp0_iter10_reg <= ap_loop_exit_ready_pp0_iter9_reg;
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
        ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
        ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
        ap_loop_exit_ready_pp0_iter8_reg <= ap_loop_exit_ready_pp0_iter7_reg;
        ap_loop_exit_ready_pp0_iter9_reg <= ap_loop_exit_ready_pp0_iter8_reg;
        icmp_ln241_reg_1934_pp0_iter2_reg <= icmp_ln241_reg_1934_pp0_iter1_reg;
        icmp_ln244_reg_1976_pp0_iter2_reg <= icmp_ln244_reg_1976;
        icmp_ln244_reg_1976_pp0_iter3_reg <= icmp_ln244_reg_1976_pp0_iter2_reg;
        icmp_ln244_reg_1976_pp0_iter4_reg <= icmp_ln244_reg_1976_pp0_iter3_reg;
        icmp_ln244_reg_1976_pp0_iter5_reg <= icmp_ln244_reg_1976_pp0_iter4_reg;
        icmp_ln244_reg_1976_pp0_iter6_reg <= icmp_ln244_reg_1976_pp0_iter5_reg;
        icmp_ln244_reg_1976_pp0_iter7_reg <= icmp_ln244_reg_1976_pp0_iter6_reg;
        icmp_ln244_reg_1976_pp0_iter8_reg <= icmp_ln244_reg_1976_pp0_iter7_reg;
        icmp_ln244_reg_1976_pp0_iter9_reg <= icmp_ln244_reg_1976_pp0_iter8_reg;
        res_91_reg_2067_pp0_iter5_reg <= res_91_reg_2067;
        res_93_reg_2079_pp0_iter5_reg <= res_93_reg_2079;
        res_reg_2061_pp0_iter5_reg <= res_reg_2061;
        rowBuffer_addr_reg_1990_pp0_iter2_reg <= rowBuffer_addr_reg_1990;
        select_ln234_3_reg_1972_pp0_iter10_reg <= select_ln234_3_reg_1972_pp0_iter9_reg;
        select_ln234_3_reg_1972_pp0_iter2_reg <= select_ln234_3_reg_1972;
        select_ln234_3_reg_1972_pp0_iter3_reg <= select_ln234_3_reg_1972_pp0_iter2_reg;
        select_ln234_3_reg_1972_pp0_iter4_reg <= select_ln234_3_reg_1972_pp0_iter3_reg;
        select_ln234_3_reg_1972_pp0_iter5_reg <= select_ln234_3_reg_1972_pp0_iter4_reg;
        select_ln234_3_reg_1972_pp0_iter6_reg <= select_ln234_3_reg_1972_pp0_iter5_reg;
        select_ln234_3_reg_1972_pp0_iter7_reg <= select_ln234_3_reg_1972_pp0_iter6_reg;
        select_ln234_3_reg_1972_pp0_iter8_reg <= select_ln234_3_reg_1972_pp0_iter7_reg;
        select_ln234_3_reg_1972_pp0_iter9_reg <= select_ln234_3_reg_1972_pp0_iter8_reg;
        select_ln234_reg_1943_pp0_iter2_reg <= select_ln234_reg_1943_pp0_iter1_reg;
        select_ln234_reg_1943_pp0_iter3_reg <= select_ln234_reg_1943_pp0_iter2_reg;
        select_ln234_reg_1943_pp0_iter4_reg <= select_ln234_reg_1943_pp0_iter3_reg;
        select_ln234_reg_1943_pp0_iter5_reg <= select_ln234_reg_1943_pp0_iter4_reg;
        select_ln234_reg_1943_pp0_iter6_reg <= select_ln234_reg_1943_pp0_iter5_reg;
        select_ln234_reg_1943_pp0_iter7_reg <= select_ln234_reg_1943_pp0_iter6_reg;
        select_ln234_reg_1943_pp0_iter8_reg <= select_ln234_reg_1943_pp0_iter7_reg;
        select_ln234_reg_1943_pp0_iter9_reg <= select_ln234_reg_1943_pp0_iter8_reg;
        tmp_155_i_reg_2056_pp0_iter5_reg <= tmp_155_i_reg_2056;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        icmp_ln241_reg_1934 <= icmp_ln241_fu_394_p2;
        icmp_ln241_reg_1934_pp0_iter1_reg <= icmp_ln241_reg_1934;
        select_ln234_reg_1943_pp0_iter1_reg <= select_ln234_reg_1943;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_phi_reg_pp0_iter1_input_3_reg_365 <= ap_phi_reg_pp0_iter0_input_3_reg_365;
        ap_phi_reg_pp0_iter1_obj_sroa_12_0_i_reg_321 <= ap_phi_reg_pp0_iter0_obj_sroa_12_0_i_reg_321;
        ap_phi_reg_pp0_iter1_obj_sroa_15_0_i_reg_332 <= ap_phi_reg_pp0_iter0_obj_sroa_15_0_i_reg_332;
        ap_phi_reg_pp0_iter1_obj_sroa_18_0_i_reg_343 <= ap_phi_reg_pp0_iter0_obj_sroa_18_0_i_reg_343;
        ap_phi_reg_pp0_iter1_obj_sroa_21_0_i_reg_354 <= ap_phi_reg_pp0_iter0_obj_sroa_21_0_i_reg_354;
        ap_phi_reg_pp0_iter1_obj_sroa_6_0_i_reg_299 <= ap_phi_reg_pp0_iter0_obj_sroa_6_0_i_reg_299;
        ap_phi_reg_pp0_iter1_obj_sroa_9_0_i_reg_310 <= ap_phi_reg_pp0_iter0_obj_sroa_9_0_i_reg_310;
        ap_phi_reg_pp0_iter1_obj_var_12_reg_288 <= ap_phi_reg_pp0_iter0_obj_var_12_reg_288;
        ap_phi_reg_pp0_iter1_obj_var_13_reg_277 <= ap_phi_reg_pp0_iter0_obj_var_13_reg_277;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_phi_reg_pp0_iter3_input_3_reg_365 <= ap_phi_reg_pp0_iter2_input_3_reg_365;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln244_fu_492_p2 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        empty_62_reg_1986 <= empty_62_fu_507_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln241_reg_1934 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        icmp_ln244_reg_1976 <= icmp_ln244_fu_492_p2;
        select_ln234_3_reg_1972 <= select_ln234_3_fu_483_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((select_ln234_3_reg_1972_pp0_iter8_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        res_100_reg_2387 <= res_100_fu_1579_p2;
        res_104_reg_2397 <= res_104_fu_1597_p2;
        res_108_reg_2407 <= res_108_fu_1615_p2;
        trunc_ln7_reg_2392 <= {{res_100_fu_1579_p2[31:24]}};
        trunc_ln93_5_reg_2412 <= {{res_108_fu_1615_p2[31:24]}};
        trunc_ln93_s_reg_2402 <= {{res_104_fu_1597_p2[31:24]}};
    end
end

always @ (posedge ap_clk) begin
    if (((select_ln234_3_reg_1972_pp0_iter6_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        res_102_reg_2237 <= res_102_fu_1307_p2;
        res_106_reg_2247 <= res_106_fu_1327_p2;
        res_98_reg_2227 <= res_98_fu_1287_p2;
        trunc_ln91_5_reg_2252 <= {{res_106_fu_1327_p2[31:6]}};
        trunc_ln91_s_reg_2242 <= {{res_102_fu_1307_p2[31:6]}};
        trunc_ln_reg_2232 <= {{res_98_fu_1287_p2[31:6]}};
    end
end

always @ (posedge ap_clk) begin
    if (((select_ln234_3_reg_1972_pp0_iter7_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        res_103_reg_2317 <= res_103_fu_1453_p2;
        res_107_reg_2327 <= res_107_fu_1471_p2;
        res_99_reg_2307 <= res_99_fu_1435_p2;
        trunc_ln6_reg_2312 <= {{res_99_fu_1435_p2[31:12]}};
        trunc_ln92_5_reg_2332 <= {{res_107_fu_1471_p2[31:12]}};
        trunc_ln92_s_reg_2322 <= {{res_103_fu_1453_p2[31:12]}};
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln244_reg_1976_pp0_iter5_reg == 1'd0) & (select_ln234_3_reg_1972_pp0_iter5_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        res_110_reg_2177 <= res_110_fu_1187_p2;
        res_114_reg_2187 <= res_114_fu_1207_p2;
        res_118_reg_2197 <= res_118_fu_1227_p2;
        res_122_reg_2207 <= res_122_fu_1247_p2;
        res_126_reg_2217 <= res_126_fu_1267_p2;
        trunc_ln91_1_reg_2222 <= {{res_126_fu_1267_p2[31:6]}};
        trunc_ln91_6_reg_2182 <= {{res_110_fu_1187_p2[31:6]}};
        trunc_ln91_7_reg_2192 <= {{res_114_fu_1207_p2[31:6]}};
        trunc_ln91_8_reg_2202 <= {{res_118_fu_1227_p2[31:6]}};
        trunc_ln91_9_reg_2212 <= {{res_122_fu_1247_p2[31:6]}};
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln244_reg_1976_pp0_iter6_reg == 1'd0) & (select_ln234_3_reg_1972_pp0_iter6_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        res_111_reg_2257 <= res_111_fu_1345_p2;
        res_115_reg_2267 <= res_115_fu_1363_p2;
        res_119_reg_2277 <= res_119_fu_1381_p2;
        res_123_reg_2287 <= res_123_fu_1399_p2;
        res_127_reg_2297 <= res_127_fu_1417_p2;
        trunc_ln92_1_reg_2302 <= {{res_127_fu_1417_p2[31:12]}};
        trunc_ln92_6_reg_2262 <= {{res_111_fu_1345_p2[31:12]}};
        trunc_ln92_7_reg_2272 <= {{res_115_fu_1363_p2[31:12]}};
        trunc_ln92_8_reg_2282 <= {{res_119_fu_1381_p2[31:12]}};
        trunc_ln92_9_reg_2292 <= {{res_123_fu_1399_p2[31:12]}};
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln244_reg_1976_pp0_iter7_reg == 1'd0) & (select_ln234_3_reg_1972_pp0_iter7_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        res_112_reg_2337 <= res_112_fu_1489_p2;
        res_116_reg_2347 <= res_116_fu_1507_p2;
        res_120_reg_2357 <= res_120_fu_1525_p2;
        res_124_reg_2367 <= res_124_fu_1543_p2;
        res_128_reg_2377 <= res_128_fu_1561_p2;
        trunc_ln93_1_reg_2382 <= {{res_128_fu_1561_p2[31:24]}};
        trunc_ln93_6_reg_2342 <= {{res_112_fu_1489_p2[31:24]}};
        trunc_ln93_7_reg_2352 <= {{res_116_fu_1507_p2[31:24]}};
        trunc_ln93_8_reg_2362 <= {{res_120_fu_1525_p2[31:24]}};
        trunc_ln93_9_reg_2372 <= {{res_124_fu_1543_p2[31:24]}};
    end
end

always @ (posedge ap_clk) begin
    if (((select_ln234_3_reg_1972_pp0_iter3_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        res_91_reg_2067 <= res_91_fu_1012_p2;
        res_92_reg_2073 <= res_92_fu_1024_p2;
        res_93_reg_2079 <= res_93_fu_1036_p2;
        res_94_reg_2086 <= res_94_fu_1048_p2;
        res_95_reg_2093 <= res_95_fu_1060_p2;
        res_96_reg_2100 <= res_96_fu_1072_p2;
        res_97_reg_2107 <= res_97_fu_1084_p2;
        res_reg_2061 <= res_fu_1000_p2;
        tmp_135_i_reg_2046 <= {{windowBuffer_fu_240[479:448]}};
        tmp_145_i_reg_2051 <= {{windowBuffer_fu_240[991:960]}};
        tmp_155_i_reg_2056 <= {{windowBuffer_fu_240[1503:1472]}};
    end
end

always @ (posedge ap_clk) begin
    if (((select_ln234_3_reg_1972_pp0_iter9_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        res_S_var_7_reg_2442 <= res_S_var_7_fu_1759_p3;
        res_S_var_9_reg_2447 <= res_S_var_9_fu_1782_p3;
        select_ln287_reg_2452 <= select_ln287_fu_1800_p3;
        select_ln289_10_reg_2467 <= select_ln289_10_fu_1820_p3;
        select_ln289_11_reg_2472 <= select_ln289_11_fu_1826_p3;
        select_ln289_12_reg_2477 <= select_ln289_12_fu_1832_p3;
        select_ln289_9_reg_2462 <= select_ln289_9_fu_1814_p3;
        select_ln289_reg_2457 <= select_ln289_fu_1808_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln241_reg_1934 == 1'd0) & (icmp_ln244_fu_492_p2 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        rowBuffer_addr_reg_1990 <= trunc_ln244_cast_i_fu_488_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln244_reg_1976 == 1'd0) & (icmp_ln241_reg_1934_pp0_iter1_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        tmp_62_i_reg_2036 <= {{rowBuffer_q1[767:256]}};
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln244_reg_1976_pp0_iter8_reg == 1'd0) & (select_ln234_3_reg_1972_pp0_iter8_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        trunc_ln292_1_reg_2422 <= {{res_117_fu_1641_p2[31:8]}};
        trunc_ln292_2_reg_2427 <= {{res_121_fu_1649_p2[31:8]}};
        trunc_ln292_3_reg_2432 <= {{res_125_fu_1657_p2[31:8]}};
        trunc_ln292_4_reg_2437 <= {{res_129_fu_1665_p2[31:8]}};
        trunc_ln292_s_reg_2417 <= {{res_113_fu_1633_p2[31:8]}};
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b1) & (select_ln234_3_reg_1972_pp0_iter3_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        windowBuffer_fu_240 <= windowBuffer_5_fu_978_p7;
    end
end

always @ (*) begin
    if (((ap_predicate_op69_read_state3 == 1'b1) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0))) begin
        GxxStream_blk_n = GxxStream_empty_n;
    end else begin
        GxxStream_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((ap_predicate_op69_read_state3 == 1'b1) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        GxxStream_read = 1'b1;
    end else begin
        GxxStream_read = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter11 == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (select_ln234_3_reg_1972_pp0_iter10_reg == 1'd0))) begin
        SxxStream_blk_n = SxxStream_full_n;
    end else begin
        SxxStream_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter11 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (select_ln234_3_reg_1972_pp0_iter10_reg == 1'd0))) begin
        SxxStream_write = 1'b1;
    end else begin
        SxxStream_write = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln241_fu_394_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter10_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_start_int == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter11 == 1'b0) & (ap_enable_reg_pp0_iter10 == 1'b0) & (ap_enable_reg_pp0_iter9 == 1'b0) & (ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        if (((ap_loop_init == 1'b1) & (ap_start_int == 1'b1))) begin
            ap_sig_allocacmp_i_load = 8'd0;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            ap_sig_allocacmp_i_load = select_ln241_reg_1960;
        end else begin
            ap_sig_allocacmp_i_load = i_fu_232;
        end
    end else begin
        ap_sig_allocacmp_i_load = i_fu_232;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_sig_allocacmp_indvar_flatten_load = 12'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten_load = indvar_flatten_fu_236;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        if (((ap_loop_init == 1'b1) & (ap_start_int == 1'b1))) begin
            ap_sig_allocacmp_j_load = 5'd0;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            ap_sig_allocacmp_j_load = add_ln242_reg_1967;
        end else begin
            ap_sig_allocacmp_j_load = j_fu_228;
        end
    end else begin
        ap_sig_allocacmp_j_load = j_fu_228;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        rowBuffer_ce0 = 1'b1;
    end else begin
        rowBuffer_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        rowBuffer_ce1 = 1'b1;
    end else begin
        rowBuffer_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b1) & (icmp_ln244_reg_1976_pp0_iter2_reg == 1'd0) & (icmp_ln241_reg_1934_pp0_iter2_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        rowBuffer_we0 = 1'b1;
    end else begin
        rowBuffer_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign SxxStream_din = $signed(tmp_25_fu_1891_p5);

assign add_ln109_32_fu_1006_p2 = (trunc_ln55_fu_630_p1 + tmp_149_i_fu_824_p4);

assign add_ln109_34_fu_1018_p2 = (tmp_130_i_fu_634_p4 + tmp_150_i_fu_834_p4);

assign add_ln109_36_fu_1030_p2 = (tmp_131_i_fu_644_p4 + tmp_151_i_fu_844_p4);

assign add_ln109_38_fu_1042_p2 = (tmp_132_i_fu_654_p4 + tmp_152_i_fu_854_p4);

assign add_ln109_40_fu_1054_p2 = (tmp_133_i_fu_664_p4 + tmp_153_i_fu_864_p4);

assign add_ln109_42_fu_1066_p2 = (tmp_134_i_fu_674_p4 + tmp_154_i_fu_874_p4);

assign add_ln109_44_fu_1078_p2 = (tmp_136_i_fu_694_p4 + tmp_156_i_fu_894_p4);

assign add_ln109_fu_994_p2 = (tmp_137_i_fu_704_p4 + tmp_157_i_fu_904_p4);

assign add_ln113_30_fu_1116_p2 = (res_92_reg_2073 + res_91_reg_2067);

assign add_ln113_36_fu_1107_p2 = (tmp_145_i_reg_2051 + res_reg_2061);

assign add_ln113_37_fu_1111_p2 = (add_ln113_36_fu_1107_p2 + tmp_135_i_reg_2046);

assign add_ln113_38_fu_1169_p2 = (add_ln113_37_reg_2118 + add_ln113_fu_1165_p2);

assign add_ln113_39_fu_1174_p2 = (res_reg_2061_pp0_iter5_reg + add_ln113_30_reg_2123);

assign add_ln113_40_fu_1178_p2 = (res_93_reg_2079_pp0_iter5_reg + add_ln113_30_reg_2123);

assign add_ln113_41_fu_1120_p2 = (res_92_reg_2073 + res_94_reg_2086);

assign add_ln113_42_fu_1124_p2 = (add_ln113_41_fu_1120_p2 + res_93_reg_2079);

assign add_ln113_43_fu_1129_p2 = (res_93_reg_2079 + res_95_reg_2093);

assign add_ln113_44_fu_1133_p2 = (add_ln113_43_fu_1129_p2 + res_94_reg_2086);

assign add_ln113_45_fu_1138_p2 = (res_94_reg_2086 + res_96_reg_2100);

assign add_ln113_46_fu_1142_p2 = (add_ln113_45_fu_1138_p2 + res_95_reg_2093);

assign add_ln113_47_fu_1147_p2 = (res_95_reg_2093 + res_97_reg_2107);

assign add_ln113_48_fu_1151_p2 = (add_ln113_47_fu_1147_p2 + res_96_reg_2100);

assign add_ln113_49_fu_1156_p2 = (res_96_reg_2100 + res_97_reg_2107);

assign add_ln113_50_fu_1090_p2 = (tmp_148_i_fu_814_p4 + tmp_158_i_fu_914_p4);

assign add_ln113_51_fu_1096_p2 = (add_ln113_50_fu_1090_p2 + tmp_138_i_fu_714_p4);

assign add_ln113_52_fu_1160_p2 = (add_ln113_51_reg_2113 + add_ln113_49_fu_1156_p2);

assign add_ln113_fu_1165_p2 = (res_91_reg_2067_pp0_iter5_reg + tmp_155_i_reg_2056_pp0_iter5_reg);

assign add_ln241_3_fu_426_p2 = (ap_sig_allocacmp_i_load + 8'd1);

assign add_ln241_fu_400_p2 = (ap_sig_allocacmp_indvar_flatten_load + 12'd1);

assign add_ln242_fu_472_p2 = (select_ln234_fu_418_p3 + 5'd1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = ((ap_done_reg == 1'b1) | ((ap_predicate_op69_read_state3 == 1'b1) & (1'b0 == GxxStream_empty_n) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((ap_done_reg == 1'b1) & (ap_start_int == 1'b1)) | ((ap_enable_reg_pp0_iter11 == 1'b1) & (1'b0 == SxxStream_full_n) & (select_ln234_3_reg_1972_pp0_iter10_reg == 1'd0)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((ap_done_reg == 1'b1) | ((ap_predicate_op69_read_state3 == 1'b1) & (1'b0 == GxxStream_empty_n) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((ap_done_reg == 1'b1) & (ap_start_int == 1'b1)) | ((ap_enable_reg_pp0_iter11 == 1'b1) & (1'b0 == SxxStream_full_n) & (select_ln234_3_reg_1972_pp0_iter10_reg == 1'd0)));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((ap_done_reg == 1'b1) | ((ap_predicate_op69_read_state3 == 1'b1) & (1'b0 == GxxStream_empty_n) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((ap_done_reg == 1'b1) & (ap_start_int == 1'b1)) | ((ap_enable_reg_pp0_iter11 == 1'b1) & (1'b0 == SxxStream_full_n) & (select_ln234_3_reg_1972_pp0_iter10_reg == 1'd0)));
end

assign ap_block_state10_pp0_stage0_iter9 = ~(1'b1 == 1'b1);

assign ap_block_state11_pp0_stage0_iter10 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state12_pp0_stage0_iter11 = ((1'b0 == SxxStream_full_n) & (select_ln234_3_reg_1972_pp0_iter10_reg == 1'd0));
end

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = (ap_done_reg == 1'b1);
end

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state3_pp0_stage0_iter2 = ((ap_predicate_op69_read_state3 == 1'b1) & (1'b0 == GxxStream_empty_n));
end

assign ap_block_state4_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter4 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage0_iter5 = ~(1'b1 == 1'b1);

assign ap_block_state7_pp0_stage0_iter6 = ~(1'b1 == 1'b1);

assign ap_block_state8_pp0_stage0_iter7 = ~(1'b1 == 1'b1);

assign ap_block_state9_pp0_stage0_iter8 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_condition_488 = ((ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001));
end

always @ (*) begin
    ap_condition_492 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001));
end

always @ (*) begin
    ap_condition_496 = ((icmp_ln241_reg_1934 == 1'd0) & (empty_62_fu_507_p2 == 1'd1) & (icmp_ln244_fu_492_p2 == 1'd0));
end

always @ (*) begin
    ap_condition_82 = ((empty_62_reg_1986 == 1'd0) & (icmp_ln244_reg_1976 == 1'd0) & (icmp_ln241_reg_1934_pp0_iter1_reg == 1'd0));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_phi_reg_pp0_iter0_input_3_reg_365 = 'bx;

assign ap_phi_reg_pp0_iter0_obj_sroa_12_0_i_reg_321 = 'bx;

assign ap_phi_reg_pp0_iter0_obj_sroa_15_0_i_reg_332 = 'bx;

assign ap_phi_reg_pp0_iter0_obj_sroa_18_0_i_reg_343 = 'bx;

assign ap_phi_reg_pp0_iter0_obj_sroa_21_0_i_reg_354 = 'bx;

assign ap_phi_reg_pp0_iter0_obj_sroa_6_0_i_reg_299 = 'bx;

assign ap_phi_reg_pp0_iter0_obj_sroa_9_0_i_reg_310 = 'bx;

assign ap_phi_reg_pp0_iter0_obj_var_12_reg_288 = 'bx;

assign ap_phi_reg_pp0_iter0_obj_var_13_reg_277 = 'bx;

always @ (*) begin
    ap_predicate_op69_read_state3 = ((empty_62_reg_1986 == 1'd0) & (icmp_ln244_reg_1976 == 1'd0) & (icmp_ln241_reg_1934_pp0_iter1_reg == 1'd0));
end

assign cmp96_i_fu_1744_p2 = ((select_ln234_reg_1943_pp0_iter9_reg == 5'd0) ? 1'b1 : 1'b0);

assign empty_61_fu_502_p2 = ((select_ln241_reg_1960 == 8'd0) ? 1'b1 : 1'b0);

assign empty_62_fu_507_p2 = (empty_fu_497_p2 | empty_61_fu_502_p2);

assign empty_fu_497_p2 = ((select_ln241_reg_1960 == 8'd127) ? 1'b1 : 1'b0);

assign icmp48_fu_458_p2 = ((tmp_26_fu_448_p4 == 7'd0) ? 1'b1 : 1'b0);

assign icmp_fu_442_p2 = ((tmp_fu_432_p4 == 7'd0) ? 1'b1 : 1'b0);

assign icmp_ln241_fu_394_p2 = ((ap_sig_allocacmp_indvar_flatten_load == 12'd2176) ? 1'b1 : 1'b0);

assign icmp_ln242_fu_412_p2 = ((ap_sig_allocacmp_j_load == 5'd17) ? 1'b1 : 1'b0);

assign icmp_ln244_fu_492_p2 = ((select_ln234_reg_1943 == 5'd16) ? 1'b1 : 1'b0);

assign input_fu_605_p10 = {{{{{{{{{ap_phi_reg_pp0_iter3_obj_sroa_21_0_i_reg_354}, {ap_phi_reg_pp0_iter3_obj_sroa_18_0_i_reg_343}}, {ap_phi_reg_pp0_iter3_obj_sroa_15_0_i_reg_332}}, {ap_phi_reg_pp0_iter3_obj_sroa_12_0_i_reg_321}}, {ap_phi_reg_pp0_iter3_obj_sroa_9_0_i_reg_310}}, {ap_phi_reg_pp0_iter3_obj_sroa_6_0_i_reg_299}}, {ap_phi_reg_pp0_iter3_obj_var_12_reg_288}}, {ap_phi_reg_pp0_iter3_obj_var_13_reg_277}}, {tmp_62_i_reg_2036}};

assign obj_var_fu_521_p1 = GxxStream_dout[31:0];

assign or_ln287_fu_1777_p2 = (icmp_ln244_reg_1976_pp0_iter9_reg | cmp96_i_fu_1744_p2);

assign res_100_fu_1579_p2 = ($signed(res_99_reg_2307) + $signed(sext_ln92_fu_1576_p1));

assign res_101_fu_1723_p2 = ($signed(res_100_reg_2387) + $signed(sext_ln93_fu_1720_p1));

assign res_102_fu_1307_p2 = (shl_ln90_15_fu_1302_p2 - add_ln113_39_reg_2165);

assign res_103_fu_1453_p2 = ($signed(res_102_reg_2237) + $signed(sext_ln91_15_fu_1450_p1));

assign res_104_fu_1597_p2 = ($signed(res_103_reg_2317) + $signed(sext_ln92_15_fu_1594_p1));

assign res_105_fu_1731_p2 = ($signed(res_104_reg_2397) + $signed(sext_ln93_15_fu_1728_p1));

assign res_106_fu_1327_p2 = (shl_ln90_16_fu_1322_p2 - add_ln113_40_reg_2171);

assign res_107_fu_1471_p2 = ($signed(res_106_reg_2247) + $signed(sext_ln91_16_fu_1468_p1));

assign res_108_fu_1615_p2 = ($signed(res_107_reg_2327) + $signed(sext_ln92_16_fu_1612_p1));

assign res_109_fu_1739_p2 = ($signed(res_108_reg_2407) + $signed(sext_ln93_16_fu_1736_p1));

assign res_110_fu_1187_p2 = (shl_ln90_17_fu_1182_p2 - add_ln113_42_reg_2129);

assign res_111_fu_1345_p2 = ($signed(res_110_reg_2177) + $signed(sext_ln91_17_fu_1342_p1));

assign res_112_fu_1489_p2 = ($signed(res_111_reg_2257) + $signed(sext_ln92_17_fu_1486_p1));

assign res_113_fu_1633_p2 = ($signed(res_112_reg_2337) + $signed(sext_ln93_17_fu_1630_p1));

assign res_114_fu_1207_p2 = (shl_ln90_18_fu_1202_p2 - add_ln113_44_reg_2135);

assign res_115_fu_1363_p2 = ($signed(res_114_reg_2187) + $signed(sext_ln91_18_fu_1360_p1));

assign res_116_fu_1507_p2 = ($signed(res_115_reg_2267) + $signed(sext_ln92_18_fu_1504_p1));

assign res_117_fu_1641_p2 = ($signed(res_116_reg_2347) + $signed(sext_ln93_18_fu_1638_p1));

assign res_118_fu_1227_p2 = (shl_ln90_19_fu_1222_p2 - add_ln113_46_reg_2141);

assign res_119_fu_1381_p2 = ($signed(res_118_reg_2197) + $signed(sext_ln91_19_fu_1378_p1));

assign res_120_fu_1525_p2 = ($signed(res_119_reg_2277) + $signed(sext_ln92_19_fu_1522_p1));

assign res_121_fu_1649_p2 = ($signed(res_120_reg_2357) + $signed(sext_ln93_19_fu_1646_p1));

assign res_122_fu_1247_p2 = (shl_ln90_20_fu_1242_p2 - add_ln113_48_reg_2147);

assign res_123_fu_1399_p2 = ($signed(res_122_reg_2207) + $signed(sext_ln91_20_fu_1396_p1));

assign res_124_fu_1543_p2 = ($signed(res_123_reg_2287) + $signed(sext_ln92_20_fu_1540_p1));

assign res_125_fu_1657_p2 = ($signed(res_124_reg_2367) + $signed(sext_ln93_20_fu_1654_p1));

assign res_126_fu_1267_p2 = (shl_ln90_21_fu_1262_p2 - add_ln113_52_reg_2153);

assign res_127_fu_1417_p2 = ($signed(res_126_reg_2217) + $signed(sext_ln91_21_fu_1414_p1));

assign res_128_fu_1561_p2 = ($signed(res_127_reg_2297) + $signed(sext_ln92_21_fu_1558_p1));

assign res_129_fu_1665_p2 = ($signed(res_128_reg_2377) + $signed(sext_ln93_21_fu_1662_p1));

assign res_91_fu_1012_p2 = (add_ln109_32_fu_1006_p2 + tmp_139_i_fu_724_p4);

assign res_92_fu_1024_p2 = (add_ln109_34_fu_1018_p2 + tmp_140_i_fu_734_p4);

assign res_93_fu_1036_p2 = (add_ln109_36_fu_1030_p2 + tmp_141_i_fu_744_p4);

assign res_94_fu_1048_p2 = (add_ln109_38_fu_1042_p2 + tmp_142_i_fu_754_p4);

assign res_95_fu_1060_p2 = (add_ln109_40_fu_1054_p2 + tmp_143_i_fu_764_p4);

assign res_96_fu_1072_p2 = (add_ln109_42_fu_1066_p2 + tmp_144_i_fu_774_p4);

assign res_97_fu_1084_p2 = (add_ln109_44_fu_1078_p2 + tmp_146_i_fu_794_p4);

assign res_98_fu_1287_p2 = (shl_ln90_fu_1282_p2 - add_ln113_38_reg_2159);

assign res_99_fu_1435_p2 = ($signed(res_98_reg_2227) + $signed(sext_ln91_fu_1432_p1));

assign res_S_var_7_fu_1759_p3 = ((cmp96_i_fu_1744_p2[0:0] == 1'b1) ? 24'd0 : res_S_var_fu_1749_p4);

assign res_S_var_8_fu_1767_p4 = {{res_105_fu_1731_p2[31:8]}};

assign res_S_var_9_fu_1782_p3 = ((or_ln287_fu_1777_p2[0:0] == 1'b1) ? 24'd0 : res_S_var_8_fu_1767_p4);

assign res_S_var_fu_1749_p4 = {{res_101_fu_1723_p2[31:8]}};

assign res_fu_1000_p2 = (add_ln109_fu_994_p2 + tmp_147_i_fu_804_p4);

assign rowBuffer_address1 = trunc_ln244_cast_i_fu_488_p1;

assign rowBuffer_d0 = {{{{{{{{{ap_phi_reg_pp0_iter3_obj_sroa_21_0_i_reg_354}, {ap_phi_reg_pp0_iter3_obj_sroa_18_0_i_reg_343}}, {ap_phi_reg_pp0_iter3_obj_sroa_15_0_i_reg_332}}, {ap_phi_reg_pp0_iter3_obj_sroa_12_0_i_reg_321}}, {ap_phi_reg_pp0_iter3_obj_sroa_9_0_i_reg_310}}, {ap_phi_reg_pp0_iter3_obj_sroa_6_0_i_reg_299}}, {ap_phi_reg_pp0_iter3_obj_var_12_reg_288}}, {ap_phi_reg_pp0_iter3_obj_var_13_reg_277}}, {tmp_62_i_reg_2036}};

assign select_ln234_3_fu_483_p3 = ((icmp_ln242_reg_1938[0:0] == 1'b1) ? icmp_reg_1950 : icmp48_reg_1955);

assign select_ln234_fu_418_p3 = ((icmp_ln242_fu_412_p2[0:0] == 1'b1) ? 5'd0 : ap_sig_allocacmp_j_load);

assign select_ln241_fu_464_p3 = ((icmp_ln242_fu_412_p2[0:0] == 1'b1) ? add_ln241_3_fu_426_p2 : ap_sig_allocacmp_i_load);

assign select_ln287_fu_1800_p3 = ((or_ln287_fu_1777_p2[0:0] == 1'b1) ? 24'd0 : trunc_ln8_fu_1790_p4);

assign select_ln289_10_fu_1820_p3 = ((icmp_ln244_reg_1976_pp0_iter9_reg[0:0] == 1'b1) ? 24'd0 : trunc_ln292_2_reg_2427);

assign select_ln289_11_fu_1826_p3 = ((icmp_ln244_reg_1976_pp0_iter9_reg[0:0] == 1'b1) ? 24'd0 : trunc_ln292_3_reg_2432);

assign select_ln289_12_fu_1832_p3 = ((icmp_ln244_reg_1976_pp0_iter9_reg[0:0] == 1'b1) ? 24'd0 : trunc_ln292_4_reg_2437);

assign select_ln289_9_fu_1814_p3 = ((icmp_ln244_reg_1976_pp0_iter9_reg[0:0] == 1'b1) ? 24'd0 : trunc_ln292_1_reg_2422);

assign select_ln289_fu_1808_p3 = ((icmp_ln244_reg_1976_pp0_iter9_reg[0:0] == 1'b1) ? 24'd0 : trunc_ln292_s_reg_2417);

assign sext_ln174_19_fu_1844_p1 = $signed(select_ln287_reg_2452);

assign sext_ln174_20_fu_1854_p1 = $signed(tmp_s_fu_1847_p3);

assign sext_ln174_21_fu_1865_p1 = $signed(tmp_22_fu_1858_p3);

assign sext_ln174_22_fu_1876_p1 = $signed(tmp_23_fu_1869_p3);

assign sext_ln174_23_fu_1887_p1 = $signed(tmp_24_fu_1880_p3);

assign sext_ln174_fu_1841_p1 = $signed(res_S_var_9_reg_2447);

assign sext_ln233_fu_1838_p1 = $signed(res_S_var_7_reg_2442);

assign sext_ln91_15_fu_1450_p1 = $signed(trunc_ln91_s_reg_2242);

assign sext_ln91_16_fu_1468_p1 = $signed(trunc_ln91_5_reg_2252);

assign sext_ln91_17_fu_1342_p1 = $signed(trunc_ln91_6_reg_2182);

assign sext_ln91_18_fu_1360_p1 = $signed(trunc_ln91_7_reg_2192);

assign sext_ln91_19_fu_1378_p1 = $signed(trunc_ln91_8_reg_2202);

assign sext_ln91_20_fu_1396_p1 = $signed(trunc_ln91_9_reg_2212);

assign sext_ln91_21_fu_1414_p1 = $signed(trunc_ln91_1_reg_2222);

assign sext_ln91_fu_1432_p1 = $signed(trunc_ln_reg_2232);

assign sext_ln92_15_fu_1594_p1 = $signed(trunc_ln92_s_reg_2322);

assign sext_ln92_16_fu_1612_p1 = $signed(trunc_ln92_5_reg_2332);

assign sext_ln92_17_fu_1486_p1 = $signed(trunc_ln92_6_reg_2262);

assign sext_ln92_18_fu_1504_p1 = $signed(trunc_ln92_7_reg_2272);

assign sext_ln92_19_fu_1522_p1 = $signed(trunc_ln92_8_reg_2282);

assign sext_ln92_20_fu_1540_p1 = $signed(trunc_ln92_9_reg_2292);

assign sext_ln92_21_fu_1558_p1 = $signed(trunc_ln92_1_reg_2302);

assign sext_ln92_fu_1576_p1 = $signed(trunc_ln6_reg_2312);

assign sext_ln93_15_fu_1728_p1 = $signed(trunc_ln93_s_reg_2402);

assign sext_ln93_16_fu_1736_p1 = $signed(trunc_ln93_5_reg_2412);

assign sext_ln93_17_fu_1630_p1 = $signed(trunc_ln93_6_reg_2342);

assign sext_ln93_18_fu_1638_p1 = $signed(trunc_ln93_7_reg_2352);

assign sext_ln93_19_fu_1646_p1 = $signed(trunc_ln93_8_reg_2362);

assign sext_ln93_20_fu_1654_p1 = $signed(trunc_ln93_9_reg_2372);

assign sext_ln93_21_fu_1662_p1 = $signed(trunc_ln93_1_reg_2382);

assign sext_ln93_fu_1720_p1 = $signed(trunc_ln7_reg_2392);

assign shl_ln90_15_fu_1302_p2 = add_ln113_39_reg_2165 << 32'd3;

assign shl_ln90_16_fu_1322_p2 = add_ln113_40_reg_2171 << 32'd3;

assign shl_ln90_17_fu_1182_p2 = add_ln113_42_reg_2129 << 32'd3;

assign shl_ln90_18_fu_1202_p2 = add_ln113_44_reg_2135 << 32'd3;

assign shl_ln90_19_fu_1222_p2 = add_ln113_46_reg_2141 << 32'd3;

assign shl_ln90_20_fu_1242_p2 = add_ln113_48_reg_2147 << 32'd3;

assign shl_ln90_21_fu_1262_p2 = add_ln113_52_reg_2153 << 32'd3;

assign shl_ln90_fu_1282_p2 = add_ln113_38_reg_2159 << 32'd3;

assign tmp_130_i_fu_634_p4 = {{ap_phi_reg_pp0_iter4_input_3_reg_365[63:32]}};

assign tmp_131_i_fu_644_p4 = {{ap_phi_reg_pp0_iter4_input_3_reg_365[95:64]}};

assign tmp_132_i_fu_654_p4 = {{ap_phi_reg_pp0_iter4_input_3_reg_365[127:96]}};

assign tmp_133_i_fu_664_p4 = {{ap_phi_reg_pp0_iter4_input_3_reg_365[159:128]}};

assign tmp_134_i_fu_674_p4 = {{ap_phi_reg_pp0_iter4_input_3_reg_365[191:160]}};

assign tmp_136_i_fu_694_p4 = {{ap_phi_reg_pp0_iter4_input_3_reg_365[223:192]}};

assign tmp_137_i_fu_704_p4 = {{windowBuffer_fu_240[511:480]}};

assign tmp_138_i_fu_714_p4 = {{ap_phi_reg_pp0_iter4_input_3_reg_365[255:224]}};

assign tmp_139_i_fu_724_p4 = {{ap_phi_reg_pp0_iter4_input_3_reg_365[287:256]}};

assign tmp_140_i_fu_734_p4 = {{ap_phi_reg_pp0_iter4_input_3_reg_365[319:288]}};

assign tmp_141_i_fu_744_p4 = {{ap_phi_reg_pp0_iter4_input_3_reg_365[351:320]}};

assign tmp_142_i_fu_754_p4 = {{ap_phi_reg_pp0_iter4_input_3_reg_365[383:352]}};

assign tmp_143_i_fu_764_p4 = {{ap_phi_reg_pp0_iter4_input_3_reg_365[415:384]}};

assign tmp_144_i_fu_774_p4 = {{ap_phi_reg_pp0_iter4_input_3_reg_365[447:416]}};

assign tmp_146_i_fu_794_p4 = {{ap_phi_reg_pp0_iter4_input_3_reg_365[479:448]}};

assign tmp_147_i_fu_804_p4 = {{windowBuffer_fu_240[1023:992]}};

assign tmp_148_i_fu_814_p4 = {{ap_phi_reg_pp0_iter4_input_3_reg_365[511:480]}};

assign tmp_149_i_fu_824_p4 = {{ap_phi_reg_pp0_iter4_input_3_reg_365[543:512]}};

assign tmp_150_i_fu_834_p4 = {{ap_phi_reg_pp0_iter4_input_3_reg_365[575:544]}};

assign tmp_151_i_fu_844_p4 = {{ap_phi_reg_pp0_iter4_input_3_reg_365[607:576]}};

assign tmp_152_i_fu_854_p4 = {{ap_phi_reg_pp0_iter4_input_3_reg_365[639:608]}};

assign tmp_153_i_fu_864_p4 = {{ap_phi_reg_pp0_iter4_input_3_reg_365[671:640]}};

assign tmp_154_i_fu_874_p4 = {{ap_phi_reg_pp0_iter4_input_3_reg_365[703:672]}};

assign tmp_156_i_fu_894_p4 = {{ap_phi_reg_pp0_iter4_input_3_reg_365[735:704]}};

assign tmp_157_i_fu_904_p4 = {{windowBuffer_fu_240[1535:1504]}};

assign tmp_158_i_fu_914_p4 = {{ap_phi_reg_pp0_iter4_input_3_reg_365[767:736]}};

assign tmp_22_fu_1858_p3 = {{select_ln289_9_reg_2462}, {sext_ln174_20_fu_1854_p1}};

assign tmp_23_fu_1869_p3 = {{select_ln289_10_reg_2467}, {sext_ln174_21_fu_1865_p1}};

assign tmp_24_fu_1880_p3 = {{select_ln289_11_reg_2472}, {sext_ln174_22_fu_1876_p1}};

assign tmp_25_fu_1891_p5 = {{{{select_ln289_12_reg_2477}, {sext_ln174_23_fu_1887_p1}}, {sext_ln174_fu_1841_p1}}, {sext_ln233_fu_1838_p1}};

assign tmp_26_fu_448_p4 = {{ap_sig_allocacmp_i_load[7:1]}};

assign tmp_63_i_fu_924_p4 = {{ap_phi_reg_pp0_iter4_input_3_reg_365[767:512]}};

assign tmp_64_i_fu_934_p4 = {{windowBuffer_fu_240[1535:1280]}};

assign tmp_65_i_fu_944_p4 = {{ap_phi_reg_pp0_iter4_input_3_reg_365[511:256]}};

assign tmp_66_i_fu_954_p4 = {{windowBuffer_fu_240[1023:768]}};

assign tmp_68_i_fu_964_p4 = {{windowBuffer_fu_240[511:256]}};

assign tmp_fu_432_p4 = {{add_ln241_3_fu_426_p2[7:1]}};

assign tmp_s_fu_1847_p3 = {{select_ln289_reg_2457}, {sext_ln174_19_fu_1844_p1}};

assign trunc_ln244_cast_i_fu_488_p1 = select_ln234_reg_1943;

assign trunc_ln55_3_fu_974_p1 = ap_phi_reg_pp0_iter4_input_3_reg_365[255:0];

assign trunc_ln55_fu_630_p1 = ap_phi_reg_pp0_iter4_input_3_reg_365[31:0];

assign trunc_ln8_fu_1790_p4 = {{res_109_fu_1739_p2[31:8]}};

assign windowBuffer_5_fu_978_p7 = {{{{{{tmp_63_i_fu_924_p4}, {tmp_64_i_fu_934_p4}}, {tmp_65_i_fu_944_p4}}, {tmp_66_i_fu_954_p4}}, {trunc_ln55_3_fu_974_p1}}, {tmp_68_i_fu_964_p4}};

endmodule //harris_filterSingle
