// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.1 (64-bit)
// Version: 2022.1
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module harris_response_Pipeline_VITIS_LOOP_325_1_VITIS_LOOP_326_2 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        SxxStream_dout,
        SxxStream_num_data_valid,
        SxxStream_fifo_cap,
        SxxStream_empty_n,
        SxxStream_read,
        SyyStream_dout,
        SyyStream_num_data_valid,
        SyyStream_fifo_cap,
        SyyStream_empty_n,
        SyyStream_read,
        SxyStream_dout,
        SxyStream_num_data_valid,
        SxyStream_fifo_cap,
        SxyStream_empty_n,
        SxyStream_read,
        RStream_din,
        RStream_num_data_valid,
        RStream_fifo_cap,
        RStream_full_n,
        RStream_write,
        zext_ln325
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [255:0] SxxStream_dout;
input  [4:0] SxxStream_num_data_valid;
input  [4:0] SxxStream_fifo_cap;
input   SxxStream_empty_n;
output   SxxStream_read;
input  [255:0] SyyStream_dout;
input  [4:0] SyyStream_num_data_valid;
input  [4:0] SyyStream_fifo_cap;
input   SyyStream_empty_n;
output   SyyStream_read;
input  [255:0] SxyStream_dout;
input  [4:0] SxyStream_num_data_valid;
input  [4:0] SxyStream_fifo_cap;
input   SxyStream_empty_n;
output   SxyStream_read;
output  [255:0] RStream_din;
input  [4:0] RStream_num_data_valid;
input  [4:0] RStream_fifo_cap;
input   RStream_full_n;
output   RStream_write;
input  [20:0] zext_ln325;

reg ap_idle;
reg SxxStream_read;
reg SyyStream_read;
reg SxyStream_read;
reg RStream_write;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_enable_reg_pp0_iter7;
reg    ap_enable_reg_pp0_iter8;
reg    ap_enable_reg_pp0_iter9;
reg    ap_enable_reg_pp0_iter10;
reg    ap_enable_reg_pp0_iter11;
reg    ap_enable_reg_pp0_iter12;
reg    ap_enable_reg_pp0_iter13;
reg    ap_enable_reg_pp0_iter14;
reg    ap_enable_reg_pp0_iter15;
reg    ap_idle_pp0;
wire    ap_block_state1_pp0_stage0_iter0;
reg    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_state3_pp0_stage0_iter2;
wire    ap_block_state4_pp0_stage0_iter3;
wire    ap_block_state5_pp0_stage0_iter4;
wire    ap_block_state6_pp0_stage0_iter5;
wire    ap_block_state7_pp0_stage0_iter6;
wire    ap_block_state8_pp0_stage0_iter7;
wire    ap_block_state9_pp0_stage0_iter8;
wire    ap_block_state10_pp0_stage0_iter9;
wire    ap_block_state11_pp0_stage0_iter10;
wire    ap_block_state12_pp0_stage0_iter11;
wire    ap_block_state13_pp0_stage0_iter12;
wire    ap_block_state14_pp0_stage0_iter13;
wire    ap_block_state15_pp0_stage0_iter14;
reg    ap_block_state16_pp0_stage0_iter15;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln325_fu_143_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    SxxStream_blk_n;
wire    ap_block_pp0_stage0;
reg    SyyStream_blk_n;
reg    SxyStream_blk_n;
reg    RStream_blk_n;
wire   [51:0] zext_ln325_cast_fu_131_p1;
reg   [51:0] zext_ln325_cast_reg_978;
reg    ap_block_pp0_stage0_11001;
wire  signed [31:0] Sxx_var_fu_160_p1;
reg  signed [31:0] Sxx_var_reg_994;
reg  signed [31:0] Sxx_var_1_reg_1000;
reg  signed [31:0] tmp_31_i7_reg_1006;
reg  signed [31:0] tmp_32_i8_reg_1012;
reg  signed [31:0] tmp_33_i9_reg_1018;
reg  signed [31:0] tmp_34_i_reg_1024;
reg  signed [31:0] tmp_35_i_reg_1030;
reg  signed [31:0] tmp_36_i_reg_1036;
wire  signed [31:0] Syy_var_fu_234_p1;
reg  signed [31:0] Syy_var_reg_1042;
reg  signed [31:0] Syy_var_1_reg_1048;
reg  signed [31:0] tmp_37_i_reg_1054;
reg  signed [31:0] tmp_38_i_reg_1060;
reg  signed [31:0] tmp_39_i_reg_1066;
reg  signed [31:0] tmp_40_i_reg_1072;
reg  signed [31:0] tmp_41_i_reg_1078;
reg  signed [31:0] tmp_42_i_reg_1084;
wire  signed [31:0] Sxy_var_fu_308_p1;
reg  signed [31:0] Sxy_var_reg_1090;
reg  signed [31:0] Sxy_var_1_reg_1096;
reg  signed [31:0] tmp_43_i_reg_1102;
reg  signed [31:0] tmp_44_i_reg_1108;
reg  signed [31:0] tmp_45_i_reg_1114;
reg  signed [31:0] tmp_46_i_reg_1120;
reg  signed [31:0] tmp_47_i_reg_1126;
reg  signed [31:0] tmp_48_i_reg_1132;
wire  signed [31:0] trace_fu_382_p2;
reg  signed [31:0] trace_reg_1138;
wire  signed [31:0] trace_1_fu_394_p2;
reg  signed [31:0] trace_1_reg_1144;
wire  signed [31:0] trace_2_fu_406_p2;
reg  signed [31:0] trace_2_reg_1150;
wire  signed [31:0] trace_3_fu_418_p2;
reg  signed [31:0] trace_3_reg_1156;
wire  signed [31:0] trace_4_fu_430_p2;
reg  signed [31:0] trace_4_reg_1162;
wire  signed [31:0] trace_5_fu_442_p2;
reg  signed [31:0] trace_5_reg_1168;
wire  signed [31:0] trace_6_fu_454_p2;
reg  signed [31:0] trace_6_reg_1174;
wire  signed [31:0] trace_7_fu_466_p2;
reg  signed [31:0] trace_7_reg_1180;
wire   [31:0] grp_fu_386_p2;
reg   [31:0] det1_reg_1186;
wire   [31:0] grp_fu_390_p2;
reg   [31:0] det2_reg_1191;
wire   [31:0] grp_fu_398_p2;
reg   [31:0] det1_1_reg_1196;
wire   [31:0] grp_fu_402_p2;
reg   [31:0] det2_1_reg_1201;
wire   [31:0] grp_fu_410_p2;
reg   [31:0] det1_2_reg_1206;
wire   [31:0] grp_fu_414_p2;
reg   [31:0] det2_2_reg_1211;
wire   [31:0] grp_fu_422_p2;
reg   [31:0] det1_3_reg_1216;
wire   [31:0] grp_fu_426_p2;
reg   [31:0] det2_3_reg_1221;
wire   [31:0] grp_fu_434_p2;
reg   [31:0] det1_4_reg_1226;
wire   [31:0] grp_fu_438_p2;
reg   [31:0] det2_4_reg_1231;
wire   [31:0] grp_fu_446_p2;
reg   [31:0] det1_5_reg_1236;
wire   [31:0] grp_fu_450_p2;
reg   [31:0] det2_5_reg_1241;
wire   [31:0] grp_fu_458_p2;
reg   [31:0] det1_6_reg_1246;
wire   [31:0] grp_fu_462_p2;
reg   [31:0] det2_6_reg_1251;
wire   [31:0] grp_fu_470_p2;
reg   [31:0] det1_7_reg_1256;
wire   [31:0] grp_fu_474_p2;
reg   [31:0] det2_7_reg_1261;
wire   [31:0] grp_fu_478_p2;
reg  signed [31:0] traceSquare_reg_1266;
wire   [31:0] det_fu_510_p2;
reg   [31:0] det_reg_1271;
reg   [31:0] det_reg_1271_pp0_iter8_reg;
reg   [31:0] det_reg_1271_pp0_iter9_reg;
reg   [31:0] det_reg_1271_pp0_iter10_reg;
reg   [31:0] det_reg_1271_pp0_iter11_reg;
reg   [31:0] det_reg_1271_pp0_iter12_reg;
wire   [31:0] grp_fu_482_p2;
reg  signed [31:0] traceSquare_1_reg_1276;
wire   [31:0] det_1_fu_514_p2;
reg   [31:0] det_1_reg_1281;
reg   [31:0] det_1_reg_1281_pp0_iter8_reg;
reg   [31:0] det_1_reg_1281_pp0_iter9_reg;
reg   [31:0] det_1_reg_1281_pp0_iter10_reg;
reg   [31:0] det_1_reg_1281_pp0_iter11_reg;
reg   [31:0] det_1_reg_1281_pp0_iter12_reg;
wire   [31:0] grp_fu_486_p2;
reg  signed [31:0] traceSquare_2_reg_1286;
wire   [31:0] det_2_fu_518_p2;
reg   [31:0] det_2_reg_1291;
reg   [31:0] det_2_reg_1291_pp0_iter8_reg;
reg   [31:0] det_2_reg_1291_pp0_iter9_reg;
reg   [31:0] det_2_reg_1291_pp0_iter10_reg;
reg   [31:0] det_2_reg_1291_pp0_iter11_reg;
reg   [31:0] det_2_reg_1291_pp0_iter12_reg;
wire   [31:0] grp_fu_490_p2;
reg  signed [31:0] traceSquare_3_reg_1296;
wire   [31:0] det_3_fu_522_p2;
reg   [31:0] det_3_reg_1301;
reg   [31:0] det_3_reg_1301_pp0_iter8_reg;
reg   [31:0] det_3_reg_1301_pp0_iter9_reg;
reg   [31:0] det_3_reg_1301_pp0_iter10_reg;
reg   [31:0] det_3_reg_1301_pp0_iter11_reg;
reg   [31:0] det_3_reg_1301_pp0_iter12_reg;
wire   [31:0] grp_fu_494_p2;
reg  signed [31:0] traceSquare_4_reg_1306;
wire   [31:0] det_4_fu_526_p2;
reg   [31:0] det_4_reg_1311;
reg   [31:0] det_4_reg_1311_pp0_iter8_reg;
reg   [31:0] det_4_reg_1311_pp0_iter9_reg;
reg   [31:0] det_4_reg_1311_pp0_iter10_reg;
reg   [31:0] det_4_reg_1311_pp0_iter11_reg;
reg   [31:0] det_4_reg_1311_pp0_iter12_reg;
wire   [31:0] grp_fu_498_p2;
reg  signed [31:0] traceSquare_5_reg_1316;
wire   [31:0] det_5_fu_530_p2;
reg   [31:0] det_5_reg_1321;
reg   [31:0] det_5_reg_1321_pp0_iter8_reg;
reg   [31:0] det_5_reg_1321_pp0_iter9_reg;
reg   [31:0] det_5_reg_1321_pp0_iter10_reg;
reg   [31:0] det_5_reg_1321_pp0_iter11_reg;
reg   [31:0] det_5_reg_1321_pp0_iter12_reg;
wire   [31:0] grp_fu_502_p2;
reg  signed [31:0] traceSquare_6_reg_1326;
wire   [31:0] det_6_fu_534_p2;
reg   [31:0] det_6_reg_1331;
reg   [31:0] det_6_reg_1331_pp0_iter8_reg;
reg   [31:0] det_6_reg_1331_pp0_iter9_reg;
reg   [31:0] det_6_reg_1331_pp0_iter10_reg;
reg   [31:0] det_6_reg_1331_pp0_iter11_reg;
reg   [31:0] det_6_reg_1331_pp0_iter12_reg;
wire   [31:0] grp_fu_506_p2;
reg  signed [31:0] traceSquare_7_reg_1336;
wire   [31:0] det_7_fu_538_p2;
reg   [31:0] det_7_reg_1341;
reg   [31:0] det_7_reg_1341_pp0_iter8_reg;
reg   [31:0] det_7_reg_1341_pp0_iter9_reg;
reg   [31:0] det_7_reg_1341_pp0_iter10_reg;
reg   [31:0] det_7_reg_1341_pp0_iter11_reg;
reg   [31:0] det_7_reg_1341_pp0_iter12_reg;
wire   [51:0] grp_fu_545_p2;
reg   [51:0] r_V_reg_1386;
wire   [51:0] grp_fu_553_p2;
reg   [51:0] r_V_1_reg_1391;
wire   [51:0] grp_fu_561_p2;
reg   [51:0] r_V_2_reg_1396;
wire   [51:0] grp_fu_569_p2;
reg   [51:0] r_V_3_reg_1401;
wire   [51:0] grp_fu_577_p2;
reg   [51:0] r_V_4_reg_1406;
wire   [51:0] grp_fu_585_p2;
reg   [51:0] r_V_5_reg_1411;
wire   [51:0] grp_fu_593_p2;
reg   [51:0] r_V_6_reg_1416;
wire   [51:0] grp_fu_601_p2;
reg   [51:0] r_V_7_reg_1421;
reg   [38:0] p_Val2_s_reg_1426;
reg   [31:0] ret_V_1_reg_1431;
reg   [38:0] p_Val2_1_reg_1436;
reg   [31:0] ret_V_3_reg_1441;
reg   [38:0] p_Val2_2_reg_1446;
reg   [31:0] ret_V_5_reg_1451;
reg   [38:0] p_Val2_3_reg_1456;
reg   [31:0] ret_V_7_reg_1461;
reg   [38:0] p_Val2_4_reg_1466;
reg   [31:0] ret_V_9_reg_1471;
reg   [38:0] p_Val2_5_reg_1476;
reg   [31:0] ret_V_11_reg_1481;
reg   [38:0] p_Val2_6_reg_1486;
reg   [31:0] ret_V_13_reg_1491;
reg   [38:0] p_Val2_7_reg_1496;
reg   [31:0] ret_V_15_reg_1501;
wire   [31:0] res_var_fu_867_p3;
reg   [31:0] res_var_reg_1506;
wire   [31:0] res_var_1_fu_879_p3;
reg   [31:0] res_var_1_reg_1511;
wire   [31:0] select_ln1695_fu_891_p3;
reg   [31:0] select_ln1695_reg_1516;
wire   [31:0] select_ln1695_1_fu_903_p3;
reg   [31:0] select_ln1695_1_reg_1521;
wire   [31:0] select_ln1695_2_fu_915_p3;
reg   [31:0] select_ln1695_2_reg_1526;
wire   [31:0] select_ln1695_3_fu_927_p3;
reg   [31:0] select_ln1695_3_reg_1531;
wire   [31:0] select_ln1695_4_fu_939_p3;
reg   [31:0] select_ln1695_4_reg_1536;
wire   [31:0] select_ln1695_5_fu_951_p3;
reg   [31:0] select_ln1695_5_reg_1541;
reg   [11:0] indvar_flatten_fu_96;
wire   [11:0] add_ln325_fu_149_p2;
wire    ap_loop_init;
reg   [11:0] ap_sig_allocacmp_indvar_flatten_load;
reg    ap_block_pp0_stage0_01001;
wire   [20:0] grp_fu_545_p1;
wire   [20:0] grp_fu_553_p1;
wire   [20:0] grp_fu_561_p1;
wire   [20:0] grp_fu_569_p1;
wire   [20:0] grp_fu_577_p1;
wire   [20:0] grp_fu_585_p1;
wire   [20:0] grp_fu_593_p1;
wire   [20:0] grp_fu_601_p1;
wire   [51:0] lhs_1_fu_606_p3;
wire   [51:0] ret_V_fu_613_p2;
wire   [51:0] lhs_3_fu_638_p3;
wire   [51:0] ret_V_2_fu_645_p2;
wire   [51:0] lhs_5_fu_670_p3;
wire   [51:0] ret_V_4_fu_677_p2;
wire   [51:0] lhs_7_fu_702_p3;
wire   [51:0] ret_V_6_fu_709_p2;
wire   [51:0] lhs_9_fu_734_p3;
wire   [51:0] ret_V_8_fu_741_p2;
wire   [51:0] lhs_11_fu_766_p3;
wire   [51:0] ret_V_10_fu_773_p2;
wire   [51:0] lhs_13_fu_798_p3;
wire   [51:0] ret_V_12_fu_805_p2;
wire   [51:0] lhs_15_fu_830_p3;
wire   [51:0] ret_V_14_fu_837_p2;
wire   [0:0] icmp_ln1695_fu_862_p2;
wire   [0:0] icmp_ln1695_1_fu_874_p2;
wire   [0:0] icmp_ln1695_2_fu_886_p2;
wire   [0:0] icmp_ln1695_3_fu_898_p2;
wire   [0:0] icmp_ln1695_4_fu_910_p2;
wire   [0:0] icmp_ln1695_5_fu_922_p2;
wire   [0:0] icmp_ln1695_6_fu_934_p2;
wire   [0:0] icmp_ln1695_7_fu_946_p2;
reg    grp_fu_386_ce;
reg    grp_fu_390_ce;
reg    grp_fu_398_ce;
reg    grp_fu_402_ce;
reg    grp_fu_410_ce;
reg    grp_fu_414_ce;
reg    grp_fu_422_ce;
reg    grp_fu_426_ce;
reg    grp_fu_434_ce;
reg    grp_fu_438_ce;
reg    grp_fu_446_ce;
reg    grp_fu_450_ce;
reg    grp_fu_458_ce;
reg    grp_fu_462_ce;
reg    grp_fu_470_ce;
reg    grp_fu_474_ce;
reg    grp_fu_478_ce;
reg    grp_fu_482_ce;
reg    grp_fu_486_ce;
reg    grp_fu_490_ce;
reg    grp_fu_494_ce;
reg    grp_fu_498_ce;
reg    grp_fu_502_ce;
reg    grp_fu_506_ce;
reg    grp_fu_545_ce;
reg    grp_fu_553_ce;
reg    grp_fu_561_ce;
reg    grp_fu_569_ce;
reg    grp_fu_577_ce;
reg    grp_fu_585_ce;
reg    grp_fu_593_ce;
reg    grp_fu_601_ce;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg    ap_loop_exit_ready_pp0_iter5_reg;
reg    ap_loop_exit_ready_pp0_iter6_reg;
reg    ap_loop_exit_ready_pp0_iter7_reg;
reg    ap_loop_exit_ready_pp0_iter8_reg;
reg    ap_loop_exit_ready_pp0_iter9_reg;
reg    ap_loop_exit_ready_pp0_iter10_reg;
reg    ap_loop_exit_ready_pp0_iter11_reg;
reg    ap_loop_exit_ready_pp0_iter12_reg;
reg    ap_loop_exit_ready_pp0_iter13_reg;
reg    ap_loop_exit_ready_pp0_iter14_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
#0 ap_enable_reg_pp0_iter8 = 1'b0;
#0 ap_enable_reg_pp0_iter9 = 1'b0;
#0 ap_enable_reg_pp0_iter10 = 1'b0;
#0 ap_enable_reg_pp0_iter11 = 1'b0;
#0 ap_enable_reg_pp0_iter12 = 1'b0;
#0 ap_enable_reg_pp0_iter13 = 1'b0;
#0 ap_enable_reg_pp0_iter14 = 1'b0;
#0 ap_enable_reg_pp0_iter15 = 1'b0;
#0 ap_done_reg = 1'b0;
end

harris_mul_32s_32s_32_5_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_32s_32s_32_5_1_U47(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(Syy_var_reg_1042),
    .din1(Sxx_var_reg_994),
    .ce(grp_fu_386_ce),
    .dout(grp_fu_386_p2)
);

harris_mul_32s_32s_32_5_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_32s_32s_32_5_1_U48(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(Sxy_var_reg_1090),
    .din1(Sxy_var_reg_1090),
    .ce(grp_fu_390_ce),
    .dout(grp_fu_390_p2)
);

harris_mul_32s_32s_32_5_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_32s_32s_32_5_1_U49(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(Syy_var_1_reg_1048),
    .din1(Sxx_var_1_reg_1000),
    .ce(grp_fu_398_ce),
    .dout(grp_fu_398_p2)
);

harris_mul_32s_32s_32_5_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_32s_32s_32_5_1_U50(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(Sxy_var_1_reg_1096),
    .din1(Sxy_var_1_reg_1096),
    .ce(grp_fu_402_ce),
    .dout(grp_fu_402_p2)
);

harris_mul_32s_32s_32_5_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_32s_32s_32_5_1_U51(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(tmp_37_i_reg_1054),
    .din1(tmp_31_i7_reg_1006),
    .ce(grp_fu_410_ce),
    .dout(grp_fu_410_p2)
);

harris_mul_32s_32s_32_5_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_32s_32s_32_5_1_U52(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(tmp_43_i_reg_1102),
    .din1(tmp_43_i_reg_1102),
    .ce(grp_fu_414_ce),
    .dout(grp_fu_414_p2)
);

harris_mul_32s_32s_32_5_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_32s_32s_32_5_1_U53(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(tmp_38_i_reg_1060),
    .din1(tmp_32_i8_reg_1012),
    .ce(grp_fu_422_ce),
    .dout(grp_fu_422_p2)
);

harris_mul_32s_32s_32_5_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_32s_32s_32_5_1_U54(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(tmp_44_i_reg_1108),
    .din1(tmp_44_i_reg_1108),
    .ce(grp_fu_426_ce),
    .dout(grp_fu_426_p2)
);

harris_mul_32s_32s_32_5_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_32s_32s_32_5_1_U55(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(tmp_39_i_reg_1066),
    .din1(tmp_33_i9_reg_1018),
    .ce(grp_fu_434_ce),
    .dout(grp_fu_434_p2)
);

harris_mul_32s_32s_32_5_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_32s_32s_32_5_1_U56(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(tmp_45_i_reg_1114),
    .din1(tmp_45_i_reg_1114),
    .ce(grp_fu_438_ce),
    .dout(grp_fu_438_p2)
);

harris_mul_32s_32s_32_5_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_32s_32s_32_5_1_U57(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(tmp_40_i_reg_1072),
    .din1(tmp_34_i_reg_1024),
    .ce(grp_fu_446_ce),
    .dout(grp_fu_446_p2)
);

harris_mul_32s_32s_32_5_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_32s_32s_32_5_1_U58(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(tmp_46_i_reg_1120),
    .din1(tmp_46_i_reg_1120),
    .ce(grp_fu_450_ce),
    .dout(grp_fu_450_p2)
);

harris_mul_32s_32s_32_5_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_32s_32s_32_5_1_U59(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(tmp_41_i_reg_1078),
    .din1(tmp_35_i_reg_1030),
    .ce(grp_fu_458_ce),
    .dout(grp_fu_458_p2)
);

harris_mul_32s_32s_32_5_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_32s_32s_32_5_1_U60(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(tmp_47_i_reg_1126),
    .din1(tmp_47_i_reg_1126),
    .ce(grp_fu_462_ce),
    .dout(grp_fu_462_p2)
);

harris_mul_32s_32s_32_5_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_32s_32s_32_5_1_U61(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(tmp_42_i_reg_1084),
    .din1(tmp_36_i_reg_1036),
    .ce(grp_fu_470_ce),
    .dout(grp_fu_470_p2)
);

harris_mul_32s_32s_32_5_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_32s_32s_32_5_1_U62(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(tmp_48_i_reg_1132),
    .din1(tmp_48_i_reg_1132),
    .ce(grp_fu_474_ce),
    .dout(grp_fu_474_p2)
);

harris_mul_32s_32s_32_5_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_32s_32s_32_5_1_U63(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(trace_reg_1138),
    .din1(trace_reg_1138),
    .ce(grp_fu_478_ce),
    .dout(grp_fu_478_p2)
);

harris_mul_32s_32s_32_5_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_32s_32s_32_5_1_U64(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(trace_1_reg_1144),
    .din1(trace_1_reg_1144),
    .ce(grp_fu_482_ce),
    .dout(grp_fu_482_p2)
);

harris_mul_32s_32s_32_5_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_32s_32s_32_5_1_U65(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(trace_2_reg_1150),
    .din1(trace_2_reg_1150),
    .ce(grp_fu_486_ce),
    .dout(grp_fu_486_p2)
);

harris_mul_32s_32s_32_5_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_32s_32s_32_5_1_U66(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(trace_3_reg_1156),
    .din1(trace_3_reg_1156),
    .ce(grp_fu_490_ce),
    .dout(grp_fu_490_p2)
);

harris_mul_32s_32s_32_5_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_32s_32s_32_5_1_U67(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(trace_4_reg_1162),
    .din1(trace_4_reg_1162),
    .ce(grp_fu_494_ce),
    .dout(grp_fu_494_p2)
);

harris_mul_32s_32s_32_5_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_32s_32s_32_5_1_U68(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(trace_5_reg_1168),
    .din1(trace_5_reg_1168),
    .ce(grp_fu_498_ce),
    .dout(grp_fu_498_p2)
);

harris_mul_32s_32s_32_5_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_32s_32s_32_5_1_U69(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(trace_6_reg_1174),
    .din1(trace_6_reg_1174),
    .ce(grp_fu_502_ce),
    .dout(grp_fu_502_p2)
);

harris_mul_32s_32s_32_5_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_32s_32s_32_5_1_U70(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(trace_7_reg_1180),
    .din1(trace_7_reg_1180),
    .ce(grp_fu_506_ce),
    .dout(grp_fu_506_p2)
);

harris_mul_32s_21ns_52_5_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 21 ),
    .dout_WIDTH( 52 ))
mul_32s_21ns_52_5_1_U71(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(traceSquare_reg_1266),
    .din1(grp_fu_545_p1),
    .ce(grp_fu_545_ce),
    .dout(grp_fu_545_p2)
);

harris_mul_32s_21ns_52_5_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 21 ),
    .dout_WIDTH( 52 ))
mul_32s_21ns_52_5_1_U72(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(traceSquare_1_reg_1276),
    .din1(grp_fu_553_p1),
    .ce(grp_fu_553_ce),
    .dout(grp_fu_553_p2)
);

harris_mul_32s_21ns_52_5_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 21 ),
    .dout_WIDTH( 52 ))
mul_32s_21ns_52_5_1_U73(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(traceSquare_2_reg_1286),
    .din1(grp_fu_561_p1),
    .ce(grp_fu_561_ce),
    .dout(grp_fu_561_p2)
);

harris_mul_32s_21ns_52_5_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 21 ),
    .dout_WIDTH( 52 ))
mul_32s_21ns_52_5_1_U74(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(traceSquare_3_reg_1296),
    .din1(grp_fu_569_p1),
    .ce(grp_fu_569_ce),
    .dout(grp_fu_569_p2)
);

harris_mul_32s_21ns_52_5_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 21 ),
    .dout_WIDTH( 52 ))
mul_32s_21ns_52_5_1_U75(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(traceSquare_4_reg_1306),
    .din1(grp_fu_577_p1),
    .ce(grp_fu_577_ce),
    .dout(grp_fu_577_p2)
);

harris_mul_32s_21ns_52_5_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 21 ),
    .dout_WIDTH( 52 ))
mul_32s_21ns_52_5_1_U76(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(traceSquare_5_reg_1316),
    .din1(grp_fu_585_p1),
    .ce(grp_fu_585_ce),
    .dout(grp_fu_585_p2)
);

harris_mul_32s_21ns_52_5_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 21 ),
    .dout_WIDTH( 52 ))
mul_32s_21ns_52_5_1_U77(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(traceSquare_6_reg_1326),
    .din1(grp_fu_593_p1),
    .ce(grp_fu_593_ce),
    .dout(grp_fu_593_p2)
);

harris_mul_32s_21ns_52_5_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 21 ),
    .dout_WIDTH( 52 ))
mul_32s_21ns_52_5_1_U78(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(traceSquare_7_reg_1336),
    .din1(grp_fu_601_p1),
    .ce(grp_fu_601_ce),
    .dout(grp_fu_601_p2)
);

harris_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter14_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter10 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter10 <= ap_enable_reg_pp0_iter9;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter11 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter11 <= ap_enable_reg_pp0_iter10;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter12 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter12 <= ap_enable_reg_pp0_iter11;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter13 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter13 <= ap_enable_reg_pp0_iter12;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter14 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter14 <= ap_enable_reg_pp0_iter13;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter15 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter15 <= ap_enable_reg_pp0_iter14;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter7 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter8 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter9 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if (((ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln325_fu_143_p2 == 1'd0))) begin
            indvar_flatten_fu_96 <= add_ln325_fu_149_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten_fu_96 <= 12'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        Sxx_var_1_reg_1000 <= {{SxxStream_dout[63:32]}};
        Sxx_var_reg_994 <= Sxx_var_fu_160_p1;
        Sxy_var_1_reg_1096 <= {{SxyStream_dout[63:32]}};
        Sxy_var_reg_1090 <= Sxy_var_fu_308_p1;
        Syy_var_1_reg_1048 <= {{SyyStream_dout[63:32]}};
        Syy_var_reg_1042 <= Syy_var_fu_234_p1;
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        tmp_31_i7_reg_1006 <= {{SxxStream_dout[95:64]}};
        tmp_32_i8_reg_1012 <= {{SxxStream_dout[127:96]}};
        tmp_33_i9_reg_1018 <= {{SxxStream_dout[159:128]}};
        tmp_34_i_reg_1024 <= {{SxxStream_dout[191:160]}};
        tmp_35_i_reg_1030 <= {{SxxStream_dout[223:192]}};
        tmp_36_i_reg_1036 <= {{SxxStream_dout[255:224]}};
        tmp_37_i_reg_1054 <= {{SyyStream_dout[95:64]}};
        tmp_38_i_reg_1060 <= {{SyyStream_dout[127:96]}};
        tmp_39_i_reg_1066 <= {{SyyStream_dout[159:128]}};
        tmp_40_i_reg_1072 <= {{SyyStream_dout[191:160]}};
        tmp_41_i_reg_1078 <= {{SyyStream_dout[223:192]}};
        tmp_42_i_reg_1084 <= {{SyyStream_dout[255:224]}};
        tmp_43_i_reg_1102 <= {{SxyStream_dout[95:64]}};
        tmp_44_i_reg_1108 <= {{SxyStream_dout[127:96]}};
        tmp_45_i_reg_1114 <= {{SxyStream_dout[159:128]}};
        tmp_46_i_reg_1120 <= {{SxyStream_dout[191:160]}};
        tmp_47_i_reg_1126 <= {{SxyStream_dout[223:192]}};
        tmp_48_i_reg_1132 <= {{SxyStream_dout[255:224]}};
        zext_ln325_cast_reg_978[20 : 0] <= zext_ln325_cast_fu_131_p1[20 : 0];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        ap_loop_exit_ready_pp0_iter10_reg <= ap_loop_exit_ready_pp0_iter9_reg;
        ap_loop_exit_ready_pp0_iter11_reg <= ap_loop_exit_ready_pp0_iter10_reg;
        ap_loop_exit_ready_pp0_iter12_reg <= ap_loop_exit_ready_pp0_iter11_reg;
        ap_loop_exit_ready_pp0_iter13_reg <= ap_loop_exit_ready_pp0_iter12_reg;
        ap_loop_exit_ready_pp0_iter14_reg <= ap_loop_exit_ready_pp0_iter13_reg;
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
        ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
        ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
        ap_loop_exit_ready_pp0_iter8_reg <= ap_loop_exit_ready_pp0_iter7_reg;
        ap_loop_exit_ready_pp0_iter9_reg <= ap_loop_exit_ready_pp0_iter8_reg;
        det1_1_reg_1196 <= grp_fu_398_p2;
        det1_2_reg_1206 <= grp_fu_410_p2;
        det1_3_reg_1216 <= grp_fu_422_p2;
        det1_4_reg_1226 <= grp_fu_434_p2;
        det1_5_reg_1236 <= grp_fu_446_p2;
        det1_6_reg_1246 <= grp_fu_458_p2;
        det1_7_reg_1256 <= grp_fu_470_p2;
        det1_reg_1186 <= grp_fu_386_p2;
        det2_1_reg_1201 <= grp_fu_402_p2;
        det2_2_reg_1211 <= grp_fu_414_p2;
        det2_3_reg_1221 <= grp_fu_426_p2;
        det2_4_reg_1231 <= grp_fu_438_p2;
        det2_5_reg_1241 <= grp_fu_450_p2;
        det2_6_reg_1251 <= grp_fu_462_p2;
        det2_7_reg_1261 <= grp_fu_474_p2;
        det2_reg_1191 <= grp_fu_390_p2;
        det_1_reg_1281 <= det_1_fu_514_p2;
        det_1_reg_1281_pp0_iter10_reg <= det_1_reg_1281_pp0_iter9_reg;
        det_1_reg_1281_pp0_iter11_reg <= det_1_reg_1281_pp0_iter10_reg;
        det_1_reg_1281_pp0_iter12_reg <= det_1_reg_1281_pp0_iter11_reg;
        det_1_reg_1281_pp0_iter8_reg <= det_1_reg_1281;
        det_1_reg_1281_pp0_iter9_reg <= det_1_reg_1281_pp0_iter8_reg;
        det_2_reg_1291 <= det_2_fu_518_p2;
        det_2_reg_1291_pp0_iter10_reg <= det_2_reg_1291_pp0_iter9_reg;
        det_2_reg_1291_pp0_iter11_reg <= det_2_reg_1291_pp0_iter10_reg;
        det_2_reg_1291_pp0_iter12_reg <= det_2_reg_1291_pp0_iter11_reg;
        det_2_reg_1291_pp0_iter8_reg <= det_2_reg_1291;
        det_2_reg_1291_pp0_iter9_reg <= det_2_reg_1291_pp0_iter8_reg;
        det_3_reg_1301 <= det_3_fu_522_p2;
        det_3_reg_1301_pp0_iter10_reg <= det_3_reg_1301_pp0_iter9_reg;
        det_3_reg_1301_pp0_iter11_reg <= det_3_reg_1301_pp0_iter10_reg;
        det_3_reg_1301_pp0_iter12_reg <= det_3_reg_1301_pp0_iter11_reg;
        det_3_reg_1301_pp0_iter8_reg <= det_3_reg_1301;
        det_3_reg_1301_pp0_iter9_reg <= det_3_reg_1301_pp0_iter8_reg;
        det_4_reg_1311 <= det_4_fu_526_p2;
        det_4_reg_1311_pp0_iter10_reg <= det_4_reg_1311_pp0_iter9_reg;
        det_4_reg_1311_pp0_iter11_reg <= det_4_reg_1311_pp0_iter10_reg;
        det_4_reg_1311_pp0_iter12_reg <= det_4_reg_1311_pp0_iter11_reg;
        det_4_reg_1311_pp0_iter8_reg <= det_4_reg_1311;
        det_4_reg_1311_pp0_iter9_reg <= det_4_reg_1311_pp0_iter8_reg;
        det_5_reg_1321 <= det_5_fu_530_p2;
        det_5_reg_1321_pp0_iter10_reg <= det_5_reg_1321_pp0_iter9_reg;
        det_5_reg_1321_pp0_iter11_reg <= det_5_reg_1321_pp0_iter10_reg;
        det_5_reg_1321_pp0_iter12_reg <= det_5_reg_1321_pp0_iter11_reg;
        det_5_reg_1321_pp0_iter8_reg <= det_5_reg_1321;
        det_5_reg_1321_pp0_iter9_reg <= det_5_reg_1321_pp0_iter8_reg;
        det_6_reg_1331 <= det_6_fu_534_p2;
        det_6_reg_1331_pp0_iter10_reg <= det_6_reg_1331_pp0_iter9_reg;
        det_6_reg_1331_pp0_iter11_reg <= det_6_reg_1331_pp0_iter10_reg;
        det_6_reg_1331_pp0_iter12_reg <= det_6_reg_1331_pp0_iter11_reg;
        det_6_reg_1331_pp0_iter8_reg <= det_6_reg_1331;
        det_6_reg_1331_pp0_iter9_reg <= det_6_reg_1331_pp0_iter8_reg;
        det_7_reg_1341 <= det_7_fu_538_p2;
        det_7_reg_1341_pp0_iter10_reg <= det_7_reg_1341_pp0_iter9_reg;
        det_7_reg_1341_pp0_iter11_reg <= det_7_reg_1341_pp0_iter10_reg;
        det_7_reg_1341_pp0_iter12_reg <= det_7_reg_1341_pp0_iter11_reg;
        det_7_reg_1341_pp0_iter8_reg <= det_7_reg_1341;
        det_7_reg_1341_pp0_iter9_reg <= det_7_reg_1341_pp0_iter8_reg;
        det_reg_1271 <= det_fu_510_p2;
        det_reg_1271_pp0_iter10_reg <= det_reg_1271_pp0_iter9_reg;
        det_reg_1271_pp0_iter11_reg <= det_reg_1271_pp0_iter10_reg;
        det_reg_1271_pp0_iter12_reg <= det_reg_1271_pp0_iter11_reg;
        det_reg_1271_pp0_iter8_reg <= det_reg_1271;
        det_reg_1271_pp0_iter9_reg <= det_reg_1271_pp0_iter8_reg;
        p_Val2_1_reg_1436 <= {{ret_V_2_fu_645_p2[51:13]}};
        p_Val2_2_reg_1446 <= {{ret_V_4_fu_677_p2[51:13]}};
        p_Val2_3_reg_1456 <= {{ret_V_6_fu_709_p2[51:13]}};
        p_Val2_4_reg_1466 <= {{ret_V_8_fu_741_p2[51:13]}};
        p_Val2_5_reg_1476 <= {{ret_V_10_fu_773_p2[51:13]}};
        p_Val2_6_reg_1486 <= {{ret_V_12_fu_805_p2[51:13]}};
        p_Val2_7_reg_1496 <= {{ret_V_14_fu_837_p2[51:13]}};
        p_Val2_s_reg_1426 <= {{ret_V_fu_613_p2[51:13]}};
        r_V_1_reg_1391 <= grp_fu_553_p2;
        r_V_2_reg_1396 <= grp_fu_561_p2;
        r_V_3_reg_1401 <= grp_fu_569_p2;
        r_V_4_reg_1406 <= grp_fu_577_p2;
        r_V_5_reg_1411 <= grp_fu_585_p2;
        r_V_6_reg_1416 <= grp_fu_593_p2;
        r_V_7_reg_1421 <= grp_fu_601_p2;
        r_V_reg_1386 <= grp_fu_545_p2;
        res_var_1_reg_1511 <= res_var_1_fu_879_p3;
        res_var_reg_1506 <= res_var_fu_867_p3;
        ret_V_11_reg_1481 <= {{ret_V_10_fu_773_p2[51:20]}};
        ret_V_13_reg_1491 <= {{ret_V_12_fu_805_p2[51:20]}};
        ret_V_15_reg_1501 <= {{ret_V_14_fu_837_p2[51:20]}};
        ret_V_1_reg_1431 <= {{ret_V_fu_613_p2[51:20]}};
        ret_V_3_reg_1441 <= {{ret_V_2_fu_645_p2[51:20]}};
        ret_V_5_reg_1451 <= {{ret_V_4_fu_677_p2[51:20]}};
        ret_V_7_reg_1461 <= {{ret_V_6_fu_709_p2[51:20]}};
        ret_V_9_reg_1471 <= {{ret_V_8_fu_741_p2[51:20]}};
        select_ln1695_1_reg_1521 <= select_ln1695_1_fu_903_p3;
        select_ln1695_2_reg_1526 <= select_ln1695_2_fu_915_p3;
        select_ln1695_3_reg_1531 <= select_ln1695_3_fu_927_p3;
        select_ln1695_4_reg_1536 <= select_ln1695_4_fu_939_p3;
        select_ln1695_5_reg_1541 <= select_ln1695_5_fu_951_p3;
        select_ln1695_reg_1516 <= select_ln1695_fu_891_p3;
        traceSquare_1_reg_1276 <= grp_fu_482_p2;
        traceSquare_2_reg_1286 <= grp_fu_486_p2;
        traceSquare_3_reg_1296 <= grp_fu_490_p2;
        traceSquare_4_reg_1306 <= grp_fu_494_p2;
        traceSquare_5_reg_1316 <= grp_fu_498_p2;
        traceSquare_6_reg_1326 <= grp_fu_502_p2;
        traceSquare_7_reg_1336 <= grp_fu_506_p2;
        traceSquare_reg_1266 <= grp_fu_478_p2;
        trace_1_reg_1144 <= trace_1_fu_394_p2;
        trace_2_reg_1150 <= trace_2_fu_406_p2;
        trace_3_reg_1156 <= trace_3_fu_418_p2;
        trace_4_reg_1162 <= trace_4_fu_430_p2;
        trace_5_reg_1168 <= trace_5_fu_442_p2;
        trace_6_reg_1174 <= trace_6_fu_454_p2;
        trace_7_reg_1180 <= trace_7_fu_466_p2;
        trace_reg_1138 <= trace_fu_382_p2;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter15 == 1'b1) & (1'b0 == ap_block_pp0_stage0))) begin
        RStream_blk_n = RStream_full_n;
    end else begin
        RStream_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter15 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        RStream_write = 1'b1;
    end else begin
        RStream_write = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        SxxStream_blk_n = SxxStream_empty_n;
    end else begin
        SxxStream_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        SxxStream_read = 1'b1;
    end else begin
        SxxStream_read = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        SxyStream_blk_n = SxyStream_empty_n;
    end else begin
        SxyStream_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        SxyStream_read = 1'b1;
    end else begin
        SxyStream_read = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        SyyStream_blk_n = SyyStream_empty_n;
    end else begin
        SyyStream_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        SyyStream_read = 1'b1;
    end else begin
        SyyStream_read = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln325_fu_143_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter14_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_start_int == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter15 == 1'b0) & (ap_enable_reg_pp0_iter14 == 1'b0) & (ap_enable_reg_pp0_iter13 == 1'b0) & (ap_enable_reg_pp0_iter12 == 1'b0) & (ap_enable_reg_pp0_iter11 == 1'b0) & (ap_enable_reg_pp0_iter10 == 1'b0) & (ap_enable_reg_pp0_iter9 == 1'b0) & (ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_sig_allocacmp_indvar_flatten_load = 12'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten_load = indvar_flatten_fu_96;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        grp_fu_386_ce = 1'b1;
    end else begin
        grp_fu_386_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        grp_fu_390_ce = 1'b1;
    end else begin
        grp_fu_390_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        grp_fu_398_ce = 1'b1;
    end else begin
        grp_fu_398_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        grp_fu_402_ce = 1'b1;
    end else begin
        grp_fu_402_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        grp_fu_410_ce = 1'b1;
    end else begin
        grp_fu_410_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        grp_fu_414_ce = 1'b1;
    end else begin
        grp_fu_414_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        grp_fu_422_ce = 1'b1;
    end else begin
        grp_fu_422_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        grp_fu_426_ce = 1'b1;
    end else begin
        grp_fu_426_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        grp_fu_434_ce = 1'b1;
    end else begin
        grp_fu_434_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        grp_fu_438_ce = 1'b1;
    end else begin
        grp_fu_438_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        grp_fu_446_ce = 1'b1;
    end else begin
        grp_fu_446_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        grp_fu_450_ce = 1'b1;
    end else begin
        grp_fu_450_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        grp_fu_458_ce = 1'b1;
    end else begin
        grp_fu_458_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        grp_fu_462_ce = 1'b1;
    end else begin
        grp_fu_462_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        grp_fu_470_ce = 1'b1;
    end else begin
        grp_fu_470_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        grp_fu_474_ce = 1'b1;
    end else begin
        grp_fu_474_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        grp_fu_478_ce = 1'b1;
    end else begin
        grp_fu_478_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        grp_fu_482_ce = 1'b1;
    end else begin
        grp_fu_482_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        grp_fu_486_ce = 1'b1;
    end else begin
        grp_fu_486_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        grp_fu_490_ce = 1'b1;
    end else begin
        grp_fu_490_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        grp_fu_494_ce = 1'b1;
    end else begin
        grp_fu_494_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        grp_fu_498_ce = 1'b1;
    end else begin
        grp_fu_498_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        grp_fu_502_ce = 1'b1;
    end else begin
        grp_fu_502_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        grp_fu_506_ce = 1'b1;
    end else begin
        grp_fu_506_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        grp_fu_545_ce = 1'b1;
    end else begin
        grp_fu_545_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        grp_fu_553_ce = 1'b1;
    end else begin
        grp_fu_553_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        grp_fu_561_ce = 1'b1;
    end else begin
        grp_fu_561_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        grp_fu_569_ce = 1'b1;
    end else begin
        grp_fu_569_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        grp_fu_577_ce = 1'b1;
    end else begin
        grp_fu_577_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        grp_fu_585_ce = 1'b1;
    end else begin
        grp_fu_585_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        grp_fu_593_ce = 1'b1;
    end else begin
        grp_fu_593_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        grp_fu_601_ce = 1'b1;
    end else begin
        grp_fu_601_ce = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign RStream_din = {{{{{{{{select_ln1695_5_reg_1541}, {select_ln1695_4_reg_1536}}, {select_ln1695_3_reg_1531}}, {select_ln1695_2_reg_1526}}, {select_ln1695_1_reg_1521}}, {select_ln1695_reg_1516}}, {res_var_1_reg_1511}}, {res_var_reg_1506}};

assign Sxx_var_fu_160_p1 = SxxStream_dout[31:0];

assign Sxy_var_fu_308_p1 = SxyStream_dout[31:0];

assign Syy_var_fu_234_p1 = SyyStream_dout[31:0];

assign add_ln325_fu_149_p2 = (ap_sig_allocacmp_indvar_flatten_load + 12'd1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = (((ap_enable_reg_pp0_iter1 == 1'b1) & ((1'b0 == SxyStream_empty_n) | (1'b0 == SyyStream_empty_n) | (1'b0 == SxxStream_empty_n))) | ((ap_enable_reg_pp0_iter15 == 1'b1) & (1'b0 == RStream_full_n)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((ap_enable_reg_pp0_iter1 == 1'b1) & ((1'b0 == SxyStream_empty_n) | (1'b0 == SyyStream_empty_n) | (1'b0 == SxxStream_empty_n))) | ((ap_enable_reg_pp0_iter15 == 1'b1) & (1'b0 == RStream_full_n)));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((ap_enable_reg_pp0_iter1 == 1'b1) & ((1'b0 == SxyStream_empty_n) | (1'b0 == SyyStream_empty_n) | (1'b0 == SxxStream_empty_n))) | ((ap_enable_reg_pp0_iter15 == 1'b1) & (1'b0 == RStream_full_n)));
end

assign ap_block_state10_pp0_stage0_iter9 = ~(1'b1 == 1'b1);

assign ap_block_state11_pp0_stage0_iter10 = ~(1'b1 == 1'b1);

assign ap_block_state12_pp0_stage0_iter11 = ~(1'b1 == 1'b1);

assign ap_block_state13_pp0_stage0_iter12 = ~(1'b1 == 1'b1);

assign ap_block_state14_pp0_stage0_iter13 = ~(1'b1 == 1'b1);

assign ap_block_state15_pp0_stage0_iter14 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state16_pp0_stage0_iter15 = (1'b0 == RStream_full_n);
end

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state2_pp0_stage0_iter1 = ((1'b0 == SxyStream_empty_n) | (1'b0 == SyyStream_empty_n) | (1'b0 == SxxStream_empty_n));
end

assign ap_block_state3_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter4 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage0_iter5 = ~(1'b1 == 1'b1);

assign ap_block_state7_pp0_stage0_iter6 = ~(1'b1 == 1'b1);

assign ap_block_state8_pp0_stage0_iter7 = ~(1'b1 == 1'b1);

assign ap_block_state9_pp0_stage0_iter8 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign det_1_fu_514_p2 = (det1_1_reg_1196 - det2_1_reg_1201);

assign det_2_fu_518_p2 = (det1_2_reg_1206 - det2_2_reg_1211);

assign det_3_fu_522_p2 = (det1_3_reg_1216 - det2_3_reg_1221);

assign det_4_fu_526_p2 = (det1_4_reg_1226 - det2_4_reg_1231);

assign det_5_fu_530_p2 = (det1_5_reg_1236 - det2_5_reg_1241);

assign det_6_fu_534_p2 = (det1_6_reg_1246 - det2_6_reg_1251);

assign det_7_fu_538_p2 = (det1_7_reg_1256 - det2_7_reg_1261);

assign det_fu_510_p2 = (det1_reg_1186 - det2_reg_1191);

assign grp_fu_545_p1 = zext_ln325_cast_reg_978;

assign grp_fu_553_p1 = zext_ln325_cast_reg_978;

assign grp_fu_561_p1 = zext_ln325_cast_reg_978;

assign grp_fu_569_p1 = zext_ln325_cast_reg_978;

assign grp_fu_577_p1 = zext_ln325_cast_reg_978;

assign grp_fu_585_p1 = zext_ln325_cast_reg_978;

assign grp_fu_593_p1 = zext_ln325_cast_reg_978;

assign grp_fu_601_p1 = zext_ln325_cast_reg_978;

assign icmp_ln1695_1_fu_874_p2 = (($signed(p_Val2_1_reg_1436) > $signed(39'd56576)) ? 1'b1 : 1'b0);

assign icmp_ln1695_2_fu_886_p2 = (($signed(p_Val2_2_reg_1446) > $signed(39'd56576)) ? 1'b1 : 1'b0);

assign icmp_ln1695_3_fu_898_p2 = (($signed(p_Val2_3_reg_1456) > $signed(39'd56576)) ? 1'b1 : 1'b0);

assign icmp_ln1695_4_fu_910_p2 = (($signed(p_Val2_4_reg_1466) > $signed(39'd56576)) ? 1'b1 : 1'b0);

assign icmp_ln1695_5_fu_922_p2 = (($signed(p_Val2_5_reg_1476) > $signed(39'd56576)) ? 1'b1 : 1'b0);

assign icmp_ln1695_6_fu_934_p2 = (($signed(p_Val2_6_reg_1486) > $signed(39'd56576)) ? 1'b1 : 1'b0);

assign icmp_ln1695_7_fu_946_p2 = (($signed(p_Val2_7_reg_1496) > $signed(39'd56576)) ? 1'b1 : 1'b0);

assign icmp_ln1695_fu_862_p2 = (($signed(p_Val2_s_reg_1426) > $signed(39'd56576)) ? 1'b1 : 1'b0);

assign icmp_ln325_fu_143_p2 = ((ap_sig_allocacmp_indvar_flatten_load == 12'd2142) ? 1'b1 : 1'b0);

assign lhs_11_fu_766_p3 = {{det_5_reg_1321_pp0_iter12_reg}, {20'd0}};

assign lhs_13_fu_798_p3 = {{det_6_reg_1331_pp0_iter12_reg}, {20'd0}};

assign lhs_15_fu_830_p3 = {{det_7_reg_1341_pp0_iter12_reg}, {20'd0}};

assign lhs_1_fu_606_p3 = {{det_reg_1271_pp0_iter12_reg}, {20'd0}};

assign lhs_3_fu_638_p3 = {{det_1_reg_1281_pp0_iter12_reg}, {20'd0}};

assign lhs_5_fu_670_p3 = {{det_2_reg_1291_pp0_iter12_reg}, {20'd0}};

assign lhs_7_fu_702_p3 = {{det_3_reg_1301_pp0_iter12_reg}, {20'd0}};

assign lhs_9_fu_734_p3 = {{det_4_reg_1311_pp0_iter12_reg}, {20'd0}};

assign res_var_1_fu_879_p3 = ((icmp_ln1695_1_fu_874_p2[0:0] == 1'b1) ? ret_V_3_reg_1441 : 32'd0);

assign res_var_fu_867_p3 = ((icmp_ln1695_fu_862_p2[0:0] == 1'b1) ? ret_V_1_reg_1431 : 32'd0);

assign ret_V_10_fu_773_p2 = (lhs_11_fu_766_p3 - r_V_5_reg_1411);

assign ret_V_12_fu_805_p2 = (lhs_13_fu_798_p3 - r_V_6_reg_1416);

assign ret_V_14_fu_837_p2 = (lhs_15_fu_830_p3 - r_V_7_reg_1421);

assign ret_V_2_fu_645_p2 = (lhs_3_fu_638_p3 - r_V_1_reg_1391);

assign ret_V_4_fu_677_p2 = (lhs_5_fu_670_p3 - r_V_2_reg_1396);

assign ret_V_6_fu_709_p2 = (lhs_7_fu_702_p3 - r_V_3_reg_1401);

assign ret_V_8_fu_741_p2 = (lhs_9_fu_734_p3 - r_V_4_reg_1406);

assign ret_V_fu_613_p2 = (lhs_1_fu_606_p3 - r_V_reg_1386);

assign select_ln1695_1_fu_903_p3 = ((icmp_ln1695_3_fu_898_p2[0:0] == 1'b1) ? ret_V_7_reg_1461 : 32'd0);

assign select_ln1695_2_fu_915_p3 = ((icmp_ln1695_4_fu_910_p2[0:0] == 1'b1) ? ret_V_9_reg_1471 : 32'd0);

assign select_ln1695_3_fu_927_p3 = ((icmp_ln1695_5_fu_922_p2[0:0] == 1'b1) ? ret_V_11_reg_1481 : 32'd0);

assign select_ln1695_4_fu_939_p3 = ((icmp_ln1695_6_fu_934_p2[0:0] == 1'b1) ? ret_V_13_reg_1491 : 32'd0);

assign select_ln1695_5_fu_951_p3 = ((icmp_ln1695_7_fu_946_p2[0:0] == 1'b1) ? ret_V_15_reg_1501 : 32'd0);

assign select_ln1695_fu_891_p3 = ((icmp_ln1695_2_fu_886_p2[0:0] == 1'b1) ? ret_V_5_reg_1451 : 32'd0);

assign trace_1_fu_394_p2 = ($signed(Syy_var_1_reg_1048) + $signed(Sxx_var_1_reg_1000));

assign trace_2_fu_406_p2 = ($signed(tmp_37_i_reg_1054) + $signed(tmp_31_i7_reg_1006));

assign trace_3_fu_418_p2 = ($signed(tmp_38_i_reg_1060) + $signed(tmp_32_i8_reg_1012));

assign trace_4_fu_430_p2 = ($signed(tmp_39_i_reg_1066) + $signed(tmp_33_i9_reg_1018));

assign trace_5_fu_442_p2 = ($signed(tmp_40_i_reg_1072) + $signed(tmp_34_i_reg_1024));

assign trace_6_fu_454_p2 = ($signed(tmp_41_i_reg_1078) + $signed(tmp_35_i_reg_1030));

assign trace_7_fu_466_p2 = ($signed(tmp_42_i_reg_1084) + $signed(tmp_36_i_reg_1036));

assign trace_fu_382_p2 = ($signed(Syy_var_reg_1042) + $signed(Sxx_var_reg_994));

assign zext_ln325_cast_fu_131_p1 = zext_ln325;

always @ (posedge ap_clk) begin
    zext_ln325_cast_reg_978[51:21] <= 31'b0000000000000000000000000000000;
end

endmodule //harris_response_Pipeline_VITIS_LOOP_325_1_VITIS_LOOP_326_2
