// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.1 (64-bit)
// Version: 2022.1
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module harris_sobel (
        ap_clk,
        ap_rst,
        ap_start,
        start_full_n,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        inStream_dout,
        inStream_num_data_valid,
        inStream_fifo_cap,
        inStream_empty_n,
        inStream_read,
        GxxStream_din,
        GxxStream_num_data_valid,
        GxxStream_fifo_cap,
        GxxStream_full_n,
        GxxStream_write,
        GyyStream_din,
        GyyStream_num_data_valid,
        GyyStream_fifo_cap,
        GyyStream_full_n,
        GyyStream_write,
        GxyStream_din,
        GxyStream_num_data_valid,
        GxyStream_fifo_cap,
        GxyStream_full_n,
        GxyStream_write,
        start_out,
        start_write
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
input   start_full_n;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [255:0] inStream_dout;
input  [4:0] inStream_num_data_valid;
input  [4:0] inStream_fifo_cap;
input   inStream_empty_n;
output   inStream_read;
output  [255:0] GxxStream_din;
input  [4:0] GxxStream_num_data_valid;
input  [4:0] GxxStream_fifo_cap;
input   GxxStream_full_n;
output   GxxStream_write;
output  [255:0] GyyStream_din;
input  [4:0] GyyStream_num_data_valid;
input  [4:0] GyyStream_fifo_cap;
input   GyyStream_full_n;
output   GyyStream_write;
output  [255:0] GxyStream_din;
input  [4:0] GxyStream_num_data_valid;
input  [4:0] GxyStream_fifo_cap;
input   GxyStream_full_n;
output   GxyStream_write;
output   start_out;
output   start_write;

reg ap_idle;
reg inStream_read;
reg GxxStream_write;
reg GyyStream_write;
reg GxyStream_write;
reg start_write;

reg    real_start;
reg    start_once_reg;
(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_enable_reg_pp0_iter7;
reg    ap_enable_reg_pp0_iter8;
reg    ap_enable_reg_pp0_iter9;
reg    ap_enable_reg_pp0_iter10;
reg    ap_enable_reg_pp0_iter11;
reg    ap_idle_pp0;
wire    internal_ap_ready;
reg    ap_done_reg;
reg    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
reg    ap_block_state3_pp0_stage0_iter2;
wire    ap_block_state4_pp0_stage0_iter3;
wire    ap_block_state5_pp0_stage0_iter4;
wire    ap_block_state6_pp0_stage0_iter5;
wire    ap_block_state7_pp0_stage0_iter6;
wire    ap_block_state8_pp0_stage0_iter7;
wire    ap_block_state9_pp0_stage0_iter8;
wire    ap_block_state10_pp0_stage0_iter9;
wire    ap_block_state11_pp0_stage0_iter10;
reg   [0:0] select_ln157_1_reg_1795;
reg   [0:0] select_ln157_1_reg_1795_pp0_iter10_reg;
reg    ap_block_state12_pp0_stage0_iter11;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln164_fu_311_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    GxxStream_blk_n;
wire    ap_block_pp0_stage0;
reg    GyyStream_blk_n;
reg    GxyStream_blk_n;
reg    inStream_blk_n;
reg    ap_block_pp0_stage0_11001;
wire   [0:0] icmp_ln165_fu_326_p2;
reg   [0:0] icmp_ln165_reg_1757;
reg   [0:0] icmp_ln165_reg_1757_pp0_iter1_reg;
wire   [4:0] select_ln157_fu_332_p3;
reg   [4:0] select_ln157_reg_1763;
reg   [4:0] select_ln157_reg_1763_pp0_iter1_reg;
reg   [4:0] select_ln157_reg_1763_pp0_iter2_reg;
reg   [4:0] select_ln157_reg_1763_pp0_iter3_reg;
reg   [4:0] select_ln157_reg_1763_pp0_iter4_reg;
wire   [4:0] add_ln165_fu_340_p2;
reg   [4:0] add_ln165_reg_1769;
wire   [0:0] icmp_fu_370_p2;
reg   [0:0] icmp_reg_1774;
wire   [0:0] icmp22_fu_386_p2;
reg   [0:0] icmp22_reg_1779;
wire   [7:0] select_ln164_fu_392_p3;
reg   [7:0] select_ln164_reg_1784;
reg   [3:0] rowBuffer_addr_reg_1789;
reg   [3:0] rowBuffer_addr_reg_1789_pp0_iter2_reg;
wire   [0:0] select_ln157_1_fu_407_p3;
reg   [0:0] select_ln157_1_reg_1795_pp0_iter3_reg;
reg   [0:0] select_ln157_1_reg_1795_pp0_iter4_reg;
reg   [0:0] select_ln157_1_reg_1795_pp0_iter5_reg;
reg   [0:0] select_ln157_1_reg_1795_pp0_iter6_reg;
reg   [0:0] select_ln157_1_reg_1795_pp0_iter7_reg;
reg   [0:0] select_ln157_1_reg_1795_pp0_iter8_reg;
reg   [0:0] select_ln157_1_reg_1795_pp0_iter9_reg;
reg   [255:0] tmp_3_reg_1799;
wire   [31:0] obj_var_fu_412_p1;
reg   [31:0] obj_var_reg_1804;
reg   [31:0] obj_var_1_reg_1811;
reg   [31:0] tmp_8_i_reg_1818;
reg   [31:0] tmp_9_i_reg_1825;
reg   [31:0] tmp_i_reg_1832;
reg   [31:0] tmp_1_i_reg_1839;
reg   [31:0] tmp_2_i_reg_1846;
reg   [31:0] tmp_3_i_reg_1852;
reg   [31:0] tmp_3_i_reg_1852_pp0_iter3_reg;
reg   [31:0] tmp_4_i_reg_1858;
reg   [30:0] trunc_ln_reg_1865;
reg   [31:0] tmp_6_i_reg_1871;
reg   [30:0] trunc_ln173_s_reg_1878;
reg   [31:0] tmp_10_i_reg_1884;
reg   [31:0] tmp_10_i_reg_1884_pp0_iter3_reg;
reg   [30:0] trunc_ln173_1_reg_1891;
reg   [31:0] tmp_12_i_reg_1897;
reg   [31:0] tmp_12_i_reg_1897_pp0_iter3_reg;
reg   [30:0] trunc_ln173_2_reg_1904;
reg   [31:0] tmp_14_i_reg_1910;
reg   [31:0] tmp_14_i_reg_1910_pp0_iter3_reg;
reg   [30:0] trunc_ln173_3_reg_1917;
reg   [31:0] tmp_16_i_reg_1923;
reg   [31:0] tmp_16_i_reg_1923_pp0_iter3_reg;
reg   [30:0] trunc_ln173_4_reg_1930;
reg   [31:0] tmp_18_i_reg_1936;
reg   [31:0] tmp_18_i_reg_1936_pp0_iter3_reg;
reg   [30:0] trunc_ln173_5_reg_1942;
reg   [31:0] tmp_20_i_reg_1947;
reg   [31:0] tmp_20_i_reg_1947_pp0_iter3_reg;
reg   [31:0] tmp_20_i_reg_1947_pp0_iter4_reg;
reg   [30:0] trunc_ln1_reg_1953;
reg   [511:0] tmp_24_i_reg_1958;
reg   [31:0] tmp_25_i_reg_1963;
reg   [31:0] tmp_26_i_reg_1969;
reg   [30:0] trunc_ln2_reg_1975;
reg   [30:0] trunc_ln54_s_reg_1980;
reg   [31:0] tmp_29_i_reg_1985;
reg   [31:0] tmp_30_i_reg_1991;
wire   [30:0] sub_ln69_fu_801_p2;
reg   [30:0] sub_ln69_reg_1997;
wire   [31:0] sub_ln70_fu_805_p2;
reg   [31:0] sub_ln70_reg_2002;
wire   [31:0] sub_ln68_fu_809_p2;
reg   [31:0] sub_ln68_reg_2007;
wire   [30:0] sub_ln69_1_fu_813_p2;
reg   [30:0] sub_ln69_1_reg_2012;
wire   [31:0] sub_ln70_1_fu_817_p2;
reg   [31:0] sub_ln70_1_reg_2017;
wire   [31:0] sub_ln68_1_fu_821_p2;
reg   [31:0] sub_ln68_1_reg_2022;
wire   [30:0] sub_ln69_2_fu_825_p2;
reg   [30:0] sub_ln69_2_reg_2027;
wire   [31:0] sub_ln68_2_fu_833_p2;
reg   [31:0] sub_ln68_2_reg_2032;
wire   [30:0] sub_ln69_3_fu_838_p2;
reg   [30:0] sub_ln69_3_reg_2037;
wire   [31:0] sub_ln68_3_fu_846_p2;
reg   [31:0] sub_ln68_3_reg_2042;
wire   [30:0] sub_ln69_4_fu_851_p2;
reg   [30:0] sub_ln69_4_reg_2047;
wire   [31:0] sub_ln68_4_fu_859_p2;
reg   [31:0] sub_ln68_4_reg_2052;
wire   [30:0] sub_ln69_5_fu_864_p2;
reg   [30:0] sub_ln69_5_reg_2057;
wire   [31:0] sub_ln68_5_fu_872_p2;
reg   [31:0] sub_ln68_5_reg_2062;
wire   [30:0] sub_ln69_6_fu_877_p2;
reg   [30:0] sub_ln69_6_reg_2067;
wire   [31:0] sub_ln68_6_fu_885_p2;
reg   [31:0] sub_ln68_6_reg_2072;
wire   [30:0] sub_ln69_7_fu_890_p2;
reg   [30:0] sub_ln69_7_reg_2077;
wire   [31:0] sub_ln68_7_fu_898_p2;
reg   [31:0] sub_ln68_7_reg_2082;
wire   [31:0] sub_ln83_fu_903_p2;
reg   [31:0] sub_ln83_reg_2087;
wire   [31:0] sub_ln84_fu_907_p2;
reg   [31:0] sub_ln84_reg_2093;
wire   [31:0] sub_ln82_fu_911_p2;
reg   [31:0] sub_ln82_reg_2100;
wire   [31:0] sub_ln84_1_fu_915_p2;
reg   [31:0] sub_ln84_1_reg_2105;
wire   [31:0] sub_ln84_2_fu_919_p2;
reg   [31:0] sub_ln84_2_reg_2112;
wire   [31:0] sub_ln84_3_fu_923_p2;
reg   [31:0] sub_ln84_3_reg_2119;
wire   [31:0] sub_ln84_4_fu_927_p2;
reg   [31:0] sub_ln84_4_reg_2126;
wire   [31:0] sub_ln84_5_fu_931_p2;
reg   [31:0] sub_ln84_5_reg_2133;
wire   [31:0] sub_ln84_6_fu_935_p2;
reg   [31:0] sub_ln84_6_reg_2140;
reg   [31:0] sub_ln84_6_reg_2140_pp0_iter4_reg;
wire  signed [31:0] Gx_var_fu_951_p2;
reg  signed [31:0] Gx_var_reg_2146;
reg  signed [31:0] Gx_var_reg_2146_pp0_iter5_reg;
wire  signed [31:0] Gx_var_1_fu_968_p2;
reg  signed [31:0] Gx_var_1_reg_2153;
reg  signed [31:0] Gx_var_1_reg_2153_pp0_iter5_reg;
wire  signed [31:0] add_ln69_fu_985_p2;
reg  signed [31:0] add_ln69_reg_2160;
reg  signed [31:0] add_ln69_reg_2160_pp0_iter5_reg;
wire  signed [31:0] add_ln69_1_fu_1002_p2;
reg  signed [31:0] add_ln69_1_reg_2167;
reg  signed [31:0] add_ln69_1_reg_2167_pp0_iter5_reg;
wire  signed [31:0] add_ln69_2_fu_1019_p2;
reg  signed [31:0] add_ln69_2_reg_2174;
reg  signed [31:0] add_ln69_2_reg_2174_pp0_iter5_reg;
wire  signed [31:0] add_ln69_3_fu_1036_p2;
reg  signed [31:0] add_ln69_3_reg_2181;
reg  signed [31:0] add_ln69_3_reg_2181_pp0_iter5_reg;
wire  signed [31:0] add_ln69_4_fu_1053_p2;
reg  signed [31:0] add_ln69_4_reg_2188;
reg  signed [31:0] add_ln69_4_reg_2188_pp0_iter5_reg;
wire  signed [31:0] add_ln69_5_fu_1070_p2;
reg  signed [31:0] add_ln69_5_reg_2195;
reg  signed [31:0] add_ln69_5_reg_2195_pp0_iter5_reg;
wire  signed [31:0] Gy_var_fu_1085_p2;
reg  signed [31:0] Gy_var_reg_2202;
reg  signed [31:0] Gy_var_reg_2202_pp0_iter5_reg;
wire  signed [31:0] Gy_var_1_fu_1099_p2;
reg  signed [31:0] Gy_var_1_reg_2209;
reg  signed [31:0] Gy_var_1_reg_2209_pp0_iter5_reg;
wire  signed [31:0] add_ln83_fu_1114_p2;
reg  signed [31:0] add_ln83_reg_2216;
reg  signed [31:0] add_ln83_reg_2216_pp0_iter5_reg;
wire  signed [31:0] add_ln83_1_fu_1129_p2;
reg  signed [31:0] add_ln83_1_reg_2223;
reg  signed [31:0] add_ln83_1_reg_2223_pp0_iter5_reg;
wire  signed [31:0] add_ln83_2_fu_1144_p2;
reg  signed [31:0] add_ln83_2_reg_2230;
reg  signed [31:0] add_ln83_2_reg_2230_pp0_iter5_reg;
wire  signed [31:0] add_ln83_3_fu_1159_p2;
reg  signed [31:0] add_ln83_3_reg_2237;
reg  signed [31:0] add_ln83_3_reg_2237_pp0_iter5_reg;
wire  signed [31:0] add_ln83_4_fu_1174_p2;
reg  signed [31:0] add_ln83_4_reg_2244;
reg  signed [31:0] add_ln83_4_reg_2244_pp0_iter5_reg;
wire   [31:0] add_ln84_fu_1180_p2;
reg   [31:0] add_ln84_reg_2251;
wire  signed [31:0] add_ln83_5_fu_1193_p2;
reg  signed [31:0] add_ln83_5_reg_2256;
wire   [0:0] cmp63_i_fu_1199_p2;
reg   [0:0] cmp63_i_reg_2263;
reg   [0:0] cmp63_i_reg_2263_pp0_iter6_reg;
reg   [0:0] cmp63_i_reg_2263_pp0_iter7_reg;
reg   [0:0] cmp63_i_reg_2263_pp0_iter8_reg;
reg   [0:0] cmp63_i_reg_2263_pp0_iter9_reg;
reg   [0:0] cmp63_i_reg_2263_pp0_iter10_reg;
reg   [25:0] trunc_ln3_reg_2273;
reg   [25:0] trunc_ln156_1_reg_2278;
reg   [25:0] Gxy_var_reg_2283;
reg   [25:0] trunc_ln4_reg_2288;
reg   [25:0] trunc_ln206_1_reg_2293;
reg   [25:0] trunc_ln206_2_reg_2298;
reg   [25:0] trunc_ln206_3_reg_2303;
reg   [25:0] trunc_ln206_5_reg_2308;
reg   [25:0] tmp_4_reg_2313;
reg   [25:0] trunc_ln5_reg_2318;
reg   [25:0] trunc_ln174_1_reg_2323;
reg   [25:0] trunc_ln174_2_reg_2328;
reg   [25:0] trunc_ln174_3_reg_2333;
reg   [25:0] trunc_ln174_4_reg_2338;
reg   [25:0] trunc_ln174_5_reg_2343;
reg   [25:0] tmp_5_reg_2348;
reg   [25:0] tmp_7_reg_2353;
reg   [25:0] trunc_ln174_7_reg_2358;
reg   [25:0] trunc_ln174_8_reg_2363;
reg   [25:0] trunc_ln174_9_reg_2368;
reg   [25:0] trunc_ln174_s_reg_2373;
reg   [25:0] trunc_ln174_6_reg_2378;
reg   [0:0] tmp_8_reg_2383;
reg   [24:0] tmp_s_reg_2388;
reg   [25:0] tmp_9_reg_2393;
reg    rowBuffer_ce0;
reg    rowBuffer_we0;
wire   [767:0] rowBuffer_d0;
wire   [3:0] rowBuffer_address1;
reg    rowBuffer_ce1;
wire   [767:0] rowBuffer_q1;
wire   [63:0] j_cast_i_fu_399_p1;
reg   [4:0] j_fu_230;
reg   [4:0] ap_sig_allocacmp_j_load;
wire    ap_loop_init;
reg   [7:0] i_fu_234;
reg   [7:0] ap_sig_allocacmp_i_load;
reg    ap_loop_init_pp0_iter1_reg;
reg   [11:0] indvar_flatten_fu_238;
wire   [11:0] add_ln164_fu_317_p2;
reg   [11:0] ap_sig_allocacmp_indvar_flatten_load;
reg   [1535:0] windowBuffer_fu_242;
wire   [1535:0] windowBuffer_1_fu_769_p7;
reg    ap_block_pp0_stage0_01001;
wire   [7:0] add_ln164_1_fu_354_p2;
wire   [6:0] tmp_fu_360_p4;
wire   [6:0] tmp_1_fu_376_p4;
wire   [255:0] tmp_31_i_fu_719_p4;
wire   [255:0] tmp_32_i_fu_729_p4;
wire   [255:0] tmp_33_i_fu_739_p4;
wire   [255:0] tmp_34_i_fu_749_p4;
wire   [255:0] tmp_35_i_fu_759_p4;
wire   [31:0] sub_ln70_2_fu_829_p2;
wire   [31:0] sub_ln70_3_fu_842_p2;
wire   [31:0] sub_ln70_4_fu_855_p2;
wire   [31:0] sub_ln70_5_fu_868_p2;
wire   [31:0] sub_ln70_6_fu_881_p2;
wire   [31:0] sub_ln70_7_fu_894_p2;
wire   [31:0] shl_ln_fu_939_p3;
wire   [31:0] add_ln69_6_fu_946_p2;
wire   [31:0] shl_ln69_1_fu_956_p3;
wire   [31:0] add_ln69_8_fu_963_p2;
wire   [31:0] shl_ln69_2_fu_973_p3;
wire   [31:0] add_ln69_10_fu_980_p2;
wire   [31:0] shl_ln69_3_fu_990_p3;
wire   [31:0] add_ln69_11_fu_997_p2;
wire   [31:0] shl_ln69_4_fu_1007_p3;
wire   [31:0] add_ln69_12_fu_1014_p2;
wire   [31:0] shl_ln69_5_fu_1024_p3;
wire   [31:0] add_ln69_13_fu_1031_p2;
wire   [31:0] shl_ln69_6_fu_1041_p3;
wire   [31:0] add_ln69_14_fu_1048_p2;
wire   [31:0] shl_ln69_7_fu_1058_p3;
wire   [31:0] add_ln69_15_fu_1065_p2;
wire   [31:0] shl_ln83_fu_1075_p2;
wire   [31:0] add_ln83_6_fu_1080_p2;
wire   [31:0] add_ln83_8_fu_1095_p2;
wire   [31:0] shl_ln83_1_fu_1090_p2;
wire   [31:0] add_ln83_10_fu_1110_p2;
wire   [31:0] shl_ln83_2_fu_1105_p2;
wire   [31:0] add_ln83_11_fu_1125_p2;
wire   [31:0] shl_ln83_3_fu_1120_p2;
wire   [31:0] add_ln83_12_fu_1140_p2;
wire   [31:0] shl_ln83_4_fu_1135_p2;
wire   [31:0] add_ln83_13_fu_1155_p2;
wire   [31:0] shl_ln83_5_fu_1150_p2;
wire   [31:0] add_ln83_14_fu_1170_p2;
wire   [31:0] shl_ln83_6_fu_1165_p2;
wire   [31:0] sub_ln82_1_fu_1189_p2;
wire   [31:0] shl_ln83_7_fu_1184_p2;
wire   [31:0] grp_fu_1204_p2;
wire   [31:0] grp_fu_1208_p2;
wire   [31:0] grp_fu_1212_p2;
wire   [31:0] grp_fu_1236_p2;
wire   [31:0] grp_fu_1248_p2;
wire   [31:0] grp_fu_1260_p2;
wire   [31:0] grp_fu_1272_p2;
wire   [31:0] grp_fu_1296_p2;
wire   [31:0] grp_fu_1216_p2;
wire   [31:0] grp_fu_1228_p2;
wire   [31:0] grp_fu_1240_p2;
wire   [31:0] grp_fu_1252_p2;
wire   [31:0] grp_fu_1264_p2;
wire   [31:0] grp_fu_1276_p2;
wire   [31:0] grp_fu_1288_p2;
wire   [31:0] grp_fu_1220_p2;
wire   [31:0] grp_fu_1232_p2;
wire   [31:0] grp_fu_1244_p2;
wire   [31:0] grp_fu_1256_p2;
wire   [31:0] grp_fu_1268_p2;
wire   [31:0] grp_fu_1280_p2;
wire   [31:0] grp_fu_1292_p2;
wire   [31:0] grp_fu_1284_p2;
wire   [31:0] grp_fu_1224_p2;
wire   [25:0] Gxx_sroa_0_0141_i_fu_1560_p3;
wire   [25:0] Gyy_sroa_0_0142_i_fu_1554_p3;
wire   [25:0] Gxy_sroa_0_0143_i_fu_1548_p3;
wire   [25:0] empty_fu_1578_p3;
wire   [31:0] zext_ln156_fu_1566_p1;
wire   [249:0] tmp_2_fu_1584_p15;
wire   [25:0] empty_34_fu_1615_p3;
wire   [31:0] zext_ln156_1_fu_1570_p1;
wire   [249:0] tmp_6_fu_1621_p15;
wire   [25:0] empty_35_fu_1658_p3;
wire  signed [31:0] sext_ln156_fu_1574_p1;
wire   [57:0] or_ln_fu_1664_p3;
wire  signed [31:0] sext_ln174_fu_1652_p1;
wire   [57:0] tmp_10_fu_1676_p3;
wire  signed [63:0] sext_ln174_3_fu_1683_p1;
wire   [89:0] tmp_11_fu_1687_p3;
wire  signed [95:0] sext_ln174_4_fu_1694_p1;
wire   [121:0] tmp_12_fu_1698_p3;
wire  signed [30:0] sext_ln174_1_fu_1655_p1;
wire  signed [127:0] sext_ln174_5_fu_1705_p1;
wire  signed [63:0] sext_ln174_2_fu_1672_p1;
wire   [249:0] tmp_13_fu_1709_p6;
reg    grp_fu_1204_ce;
reg    grp_fu_1208_ce;
reg    grp_fu_1212_ce;
reg    grp_fu_1216_ce;
reg    grp_fu_1220_ce;
reg    grp_fu_1224_ce;
reg    grp_fu_1228_ce;
reg    grp_fu_1232_ce;
reg    grp_fu_1236_ce;
reg    grp_fu_1240_ce;
reg    grp_fu_1244_ce;
reg    grp_fu_1248_ce;
reg    grp_fu_1252_ce;
reg    grp_fu_1256_ce;
reg    grp_fu_1260_ce;
reg    grp_fu_1264_ce;
reg    grp_fu_1268_ce;
reg    grp_fu_1272_ce;
reg    grp_fu_1276_ce;
reg    grp_fu_1280_ce;
reg    grp_fu_1284_ce;
reg    grp_fu_1288_ce;
reg    grp_fu_1292_ce;
reg    grp_fu_1296_ce;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg    ap_loop_exit_ready_pp0_iter5_reg;
reg    ap_loop_exit_ready_pp0_iter6_reg;
reg    ap_loop_exit_ready_pp0_iter7_reg;
reg    ap_loop_exit_ready_pp0_iter8_reg;
reg    ap_loop_exit_ready_pp0_iter9_reg;
reg    ap_loop_exit_ready_pp0_iter10_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
reg    ap_condition_591;
reg    ap_condition_577;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 start_once_reg = 1'b0;
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
#0 ap_enable_reg_pp0_iter8 = 1'b0;
#0 ap_enable_reg_pp0_iter9 = 1'b0;
#0 ap_enable_reg_pp0_iter10 = 1'b0;
#0 ap_enable_reg_pp0_iter11 = 1'b0;
#0 ap_done_reg = 1'b0;
end

harris_sobel_rowBuffer_RAM_AUTO_1R1W #(
    .DataWidth( 768 ),
    .AddressRange( 16 ),
    .AddressWidth( 4 ))
rowBuffer_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(rowBuffer_addr_reg_1789_pp0_iter2_reg),
    .ce0(rowBuffer_ce0),
    .we0(rowBuffer_we0),
    .d0(rowBuffer_d0),
    .address1(rowBuffer_address1),
    .ce1(rowBuffer_ce1),
    .q1(rowBuffer_q1)
);

harris_mul_32s_32s_32_5_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_32s_32s_32_5_1_U5(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(Gx_var_reg_2146_pp0_iter5_reg),
    .din1(Gx_var_reg_2146_pp0_iter5_reg),
    .ce(grp_fu_1204_ce),
    .dout(grp_fu_1204_p2)
);

harris_mul_32s_32s_32_5_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_32s_32s_32_5_1_U6(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(Gy_var_reg_2202_pp0_iter5_reg),
    .din1(Gy_var_reg_2202_pp0_iter5_reg),
    .ce(grp_fu_1208_ce),
    .dout(grp_fu_1208_p2)
);

harris_mul_32s_32s_32_5_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_32s_32s_32_5_1_U7(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(Gy_var_reg_2202_pp0_iter5_reg),
    .din1(Gx_var_reg_2146_pp0_iter5_reg),
    .ce(grp_fu_1212_ce),
    .dout(grp_fu_1212_p2)
);

harris_mul_32s_32s_32_5_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_32s_32s_32_5_1_U8(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(Gx_var_1_reg_2153_pp0_iter5_reg),
    .din1(Gx_var_1_reg_2153_pp0_iter5_reg),
    .ce(grp_fu_1216_ce),
    .dout(grp_fu_1216_p2)
);

harris_mul_32s_32s_32_5_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_32s_32s_32_5_1_U9(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(Gy_var_1_reg_2209_pp0_iter5_reg),
    .din1(Gy_var_1_reg_2209_pp0_iter5_reg),
    .ce(grp_fu_1220_ce),
    .dout(grp_fu_1220_p2)
);

harris_mul_32s_32s_32_5_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_32s_32s_32_5_1_U10(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(Gy_var_1_reg_2209_pp0_iter5_reg),
    .din1(Gx_var_1_reg_2153_pp0_iter5_reg),
    .ce(grp_fu_1224_ce),
    .dout(grp_fu_1224_p2)
);

harris_mul_32s_32s_32_5_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_32s_32s_32_5_1_U11(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(add_ln69_reg_2160_pp0_iter5_reg),
    .din1(add_ln69_reg_2160_pp0_iter5_reg),
    .ce(grp_fu_1228_ce),
    .dout(grp_fu_1228_p2)
);

harris_mul_32s_32s_32_5_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_32s_32s_32_5_1_U12(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(add_ln83_reg_2216_pp0_iter5_reg),
    .din1(add_ln83_reg_2216_pp0_iter5_reg),
    .ce(grp_fu_1232_ce),
    .dout(grp_fu_1232_p2)
);

harris_mul_32s_32s_32_5_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_32s_32s_32_5_1_U13(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(add_ln83_reg_2216_pp0_iter5_reg),
    .din1(add_ln69_reg_2160_pp0_iter5_reg),
    .ce(grp_fu_1236_ce),
    .dout(grp_fu_1236_p2)
);

harris_mul_32s_32s_32_5_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_32s_32s_32_5_1_U14(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(add_ln69_1_reg_2167_pp0_iter5_reg),
    .din1(add_ln69_1_reg_2167_pp0_iter5_reg),
    .ce(grp_fu_1240_ce),
    .dout(grp_fu_1240_p2)
);

harris_mul_32s_32s_32_5_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_32s_32s_32_5_1_U15(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(add_ln83_1_reg_2223_pp0_iter5_reg),
    .din1(add_ln83_1_reg_2223_pp0_iter5_reg),
    .ce(grp_fu_1244_ce),
    .dout(grp_fu_1244_p2)
);

harris_mul_32s_32s_32_5_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_32s_32s_32_5_1_U16(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(add_ln83_1_reg_2223_pp0_iter5_reg),
    .din1(add_ln69_1_reg_2167_pp0_iter5_reg),
    .ce(grp_fu_1248_ce),
    .dout(grp_fu_1248_p2)
);

harris_mul_32s_32s_32_5_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_32s_32s_32_5_1_U17(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(add_ln69_2_reg_2174_pp0_iter5_reg),
    .din1(add_ln69_2_reg_2174_pp0_iter5_reg),
    .ce(grp_fu_1252_ce),
    .dout(grp_fu_1252_p2)
);

harris_mul_32s_32s_32_5_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_32s_32s_32_5_1_U18(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(add_ln83_2_reg_2230_pp0_iter5_reg),
    .din1(add_ln83_2_reg_2230_pp0_iter5_reg),
    .ce(grp_fu_1256_ce),
    .dout(grp_fu_1256_p2)
);

harris_mul_32s_32s_32_5_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_32s_32s_32_5_1_U19(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(add_ln83_2_reg_2230_pp0_iter5_reg),
    .din1(add_ln69_2_reg_2174_pp0_iter5_reg),
    .ce(grp_fu_1260_ce),
    .dout(grp_fu_1260_p2)
);

harris_mul_32s_32s_32_5_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_32s_32s_32_5_1_U20(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(add_ln69_3_reg_2181_pp0_iter5_reg),
    .din1(add_ln69_3_reg_2181_pp0_iter5_reg),
    .ce(grp_fu_1264_ce),
    .dout(grp_fu_1264_p2)
);

harris_mul_32s_32s_32_5_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_32s_32s_32_5_1_U21(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(add_ln83_3_reg_2237_pp0_iter5_reg),
    .din1(add_ln83_3_reg_2237_pp0_iter5_reg),
    .ce(grp_fu_1268_ce),
    .dout(grp_fu_1268_p2)
);

harris_mul_32s_32s_32_5_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_32s_32s_32_5_1_U22(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(add_ln83_3_reg_2237_pp0_iter5_reg),
    .din1(add_ln69_3_reg_2181_pp0_iter5_reg),
    .ce(grp_fu_1272_ce),
    .dout(grp_fu_1272_p2)
);

harris_mul_32s_32s_32_5_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_32s_32s_32_5_1_U23(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(add_ln69_4_reg_2188_pp0_iter5_reg),
    .din1(add_ln69_4_reg_2188_pp0_iter5_reg),
    .ce(grp_fu_1276_ce),
    .dout(grp_fu_1276_p2)
);

harris_mul_32s_32s_32_5_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_32s_32s_32_5_1_U24(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(add_ln83_4_reg_2244_pp0_iter5_reg),
    .din1(add_ln83_4_reg_2244_pp0_iter5_reg),
    .ce(grp_fu_1280_ce),
    .dout(grp_fu_1280_p2)
);

harris_mul_32s_32s_32_5_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_32s_32s_32_5_1_U25(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(add_ln83_4_reg_2244_pp0_iter5_reg),
    .din1(add_ln69_4_reg_2188_pp0_iter5_reg),
    .ce(grp_fu_1284_ce),
    .dout(grp_fu_1284_p2)
);

harris_mul_32s_32s_32_5_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_32s_32s_32_5_1_U26(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(add_ln69_5_reg_2195_pp0_iter5_reg),
    .din1(add_ln69_5_reg_2195_pp0_iter5_reg),
    .ce(grp_fu_1288_ce),
    .dout(grp_fu_1288_p2)
);

harris_mul_32s_32s_32_5_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_32s_32s_32_5_1_U27(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(add_ln83_5_reg_2256),
    .din1(add_ln83_5_reg_2256),
    .ce(grp_fu_1292_ce),
    .dout(grp_fu_1292_p2)
);

harris_mul_32s_32s_32_5_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_32s_32s_32_5_1_U28(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(add_ln83_5_reg_2256),
    .din1(add_ln69_5_reg_2195_pp0_iter5_reg),
    .ce(grp_fu_1296_ce),
    .dout(grp_fu_1296_p2)
);

harris_flow_control_loop_pipe flow_control_loop_pipe_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(real_start),
    .ap_ready(internal_ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int),
    .ap_continue(ap_continue)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready_pp0_iter10_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter10 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter10 <= ap_enable_reg_pp0_iter9;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter11 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter11 <= ap_enable_reg_pp0_iter10;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter7 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter8 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter9 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        start_once_reg <= 1'b0;
    end else begin
        if (((real_start == 1'b1) & (internal_ap_ready == 1'b0))) begin
            start_once_reg <= 1'b1;
        end else if ((internal_ap_ready == 1'b1)) begin
            start_once_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if ((1'b1 == ap_condition_591)) begin
            i_fu_234 <= 8'd0;
        end else if ((ap_enable_reg_pp0_iter2 == 1'b1)) begin
            i_fu_234 <= select_ln164_reg_1784;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_577)) begin
        if ((icmp_ln164_fu_311_p2 == 1'd0)) begin
            indvar_flatten_fu_238 <= add_ln164_fu_317_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten_fu_238 <= 12'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if (((ap_loop_init == 1'b1) & (ap_start_int == 1'b1))) begin
            j_fu_230 <= 5'd0;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            j_fu_230 <= add_ln165_reg_1769;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((select_ln157_1_reg_1795_pp0_iter3_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        Gx_var_1_reg_2153 <= Gx_var_1_fu_968_p2;
        Gx_var_reg_2146 <= Gx_var_fu_951_p2;
        Gy_var_1_reg_2209 <= Gy_var_1_fu_1099_p2;
        Gy_var_reg_2202 <= Gy_var_fu_1085_p2;
        add_ln69_1_reg_2167 <= add_ln69_1_fu_1002_p2;
        add_ln69_2_reg_2174 <= add_ln69_2_fu_1019_p2;
        add_ln69_3_reg_2181 <= add_ln69_3_fu_1036_p2;
        add_ln69_4_reg_2188 <= add_ln69_4_fu_1053_p2;
        add_ln69_5_reg_2195 <= add_ln69_5_fu_1070_p2;
        add_ln69_reg_2160 <= add_ln69_fu_985_p2;
        add_ln83_1_reg_2223 <= add_ln83_1_fu_1129_p2;
        add_ln83_2_reg_2230 <= add_ln83_2_fu_1144_p2;
        add_ln83_3_reg_2237 <= add_ln83_3_fu_1159_p2;
        add_ln83_4_reg_2244 <= add_ln83_4_fu_1174_p2;
        add_ln83_reg_2216 <= add_ln83_fu_1114_p2;
        add_ln84_reg_2251 <= add_ln84_fu_1180_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        Gx_var_1_reg_2153_pp0_iter5_reg <= Gx_var_1_reg_2153;
        Gx_var_reg_2146_pp0_iter5_reg <= Gx_var_reg_2146;
        Gy_var_1_reg_2209_pp0_iter5_reg <= Gy_var_1_reg_2209;
        Gy_var_reg_2202_pp0_iter5_reg <= Gy_var_reg_2202;
        add_ln69_1_reg_2167_pp0_iter5_reg <= add_ln69_1_reg_2167;
        add_ln69_2_reg_2174_pp0_iter5_reg <= add_ln69_2_reg_2174;
        add_ln69_3_reg_2181_pp0_iter5_reg <= add_ln69_3_reg_2181;
        add_ln69_4_reg_2188_pp0_iter5_reg <= add_ln69_4_reg_2188;
        add_ln69_5_reg_2195_pp0_iter5_reg <= add_ln69_5_reg_2195;
        add_ln69_reg_2160_pp0_iter5_reg <= add_ln69_reg_2160;
        add_ln83_1_reg_2223_pp0_iter5_reg <= add_ln83_1_reg_2223;
        add_ln83_2_reg_2230_pp0_iter5_reg <= add_ln83_2_reg_2230;
        add_ln83_3_reg_2237_pp0_iter5_reg <= add_ln83_3_reg_2237;
        add_ln83_4_reg_2244_pp0_iter5_reg <= add_ln83_4_reg_2244;
        add_ln83_reg_2216_pp0_iter5_reg <= add_ln83_reg_2216;
        ap_loop_exit_ready_pp0_iter10_reg <= ap_loop_exit_ready_pp0_iter9_reg;
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
        ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
        ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
        ap_loop_exit_ready_pp0_iter8_reg <= ap_loop_exit_ready_pp0_iter7_reg;
        ap_loop_exit_ready_pp0_iter9_reg <= ap_loop_exit_ready_pp0_iter8_reg;
        cmp63_i_reg_2263_pp0_iter10_reg <= cmp63_i_reg_2263_pp0_iter9_reg;
        cmp63_i_reg_2263_pp0_iter6_reg <= cmp63_i_reg_2263;
        cmp63_i_reg_2263_pp0_iter7_reg <= cmp63_i_reg_2263_pp0_iter6_reg;
        cmp63_i_reg_2263_pp0_iter8_reg <= cmp63_i_reg_2263_pp0_iter7_reg;
        cmp63_i_reg_2263_pp0_iter9_reg <= cmp63_i_reg_2263_pp0_iter8_reg;
        obj_var_1_reg_1811 <= {{inStream_dout[63:32]}};
        obj_var_reg_1804 <= obj_var_fu_412_p1;
        rowBuffer_addr_reg_1789_pp0_iter2_reg <= rowBuffer_addr_reg_1789;
        select_ln157_1_reg_1795 <= select_ln157_1_fu_407_p3;
        select_ln157_1_reg_1795_pp0_iter10_reg <= select_ln157_1_reg_1795_pp0_iter9_reg;
        select_ln157_1_reg_1795_pp0_iter3_reg <= select_ln157_1_reg_1795;
        select_ln157_1_reg_1795_pp0_iter4_reg <= select_ln157_1_reg_1795_pp0_iter3_reg;
        select_ln157_1_reg_1795_pp0_iter5_reg <= select_ln157_1_reg_1795_pp0_iter4_reg;
        select_ln157_1_reg_1795_pp0_iter6_reg <= select_ln157_1_reg_1795_pp0_iter5_reg;
        select_ln157_1_reg_1795_pp0_iter7_reg <= select_ln157_1_reg_1795_pp0_iter6_reg;
        select_ln157_1_reg_1795_pp0_iter8_reg <= select_ln157_1_reg_1795_pp0_iter7_reg;
        select_ln157_1_reg_1795_pp0_iter9_reg <= select_ln157_1_reg_1795_pp0_iter8_reg;
        select_ln157_reg_1763_pp0_iter2_reg <= select_ln157_reg_1763_pp0_iter1_reg;
        select_ln157_reg_1763_pp0_iter3_reg <= select_ln157_reg_1763_pp0_iter2_reg;
        select_ln157_reg_1763_pp0_iter4_reg <= select_ln157_reg_1763_pp0_iter3_reg;
        sub_ln84_6_reg_2140_pp0_iter4_reg <= sub_ln84_6_reg_2140;
        tmp_10_i_reg_1884 <= {{rowBuffer_q1[351:320]}};
        tmp_10_i_reg_1884_pp0_iter3_reg <= tmp_10_i_reg_1884;
        tmp_12_i_reg_1897 <= {{rowBuffer_q1[383:352]}};
        tmp_12_i_reg_1897_pp0_iter3_reg <= tmp_12_i_reg_1897;
        tmp_14_i_reg_1910 <= {{rowBuffer_q1[415:384]}};
        tmp_14_i_reg_1910_pp0_iter3_reg <= tmp_14_i_reg_1910;
        tmp_16_i_reg_1923 <= {{rowBuffer_q1[447:416]}};
        tmp_16_i_reg_1923_pp0_iter3_reg <= tmp_16_i_reg_1923;
        tmp_18_i_reg_1936 <= {{rowBuffer_q1[479:448]}};
        tmp_18_i_reg_1936_pp0_iter3_reg <= tmp_18_i_reg_1936;
        tmp_1_i_reg_1839 <= {{inStream_dout[191:160]}};
        tmp_20_i_reg_1947 <= {{rowBuffer_q1[511:480]}};
        tmp_20_i_reg_1947_pp0_iter3_reg <= tmp_20_i_reg_1947;
        tmp_20_i_reg_1947_pp0_iter4_reg <= tmp_20_i_reg_1947_pp0_iter3_reg;
        tmp_24_i_reg_1958 <= {{rowBuffer_q1[767:256]}};
        tmp_2_i_reg_1846 <= {{inStream_dout[223:192]}};
        tmp_3_i_reg_1852 <= {{inStream_dout[255:224]}};
        tmp_3_i_reg_1852_pp0_iter3_reg <= tmp_3_i_reg_1852;
        tmp_3_reg_1799 <= inStream_dout;
        tmp_4_i_reg_1858 <= {{rowBuffer_q1[287:256]}};
        tmp_6_i_reg_1871 <= {{rowBuffer_q1[319:288]}};
        tmp_8_i_reg_1818 <= {{inStream_dout[95:64]}};
        tmp_9_i_reg_1825 <= {{inStream_dout[127:96]}};
        tmp_i_reg_1832 <= {{inStream_dout[159:128]}};
        trunc_ln173_1_reg_1891 <= {{rowBuffer_q1[606:576]}};
        trunc_ln173_2_reg_1904 <= {{rowBuffer_q1[638:608]}};
        trunc_ln173_3_reg_1917 <= {{rowBuffer_q1[670:640]}};
        trunc_ln173_4_reg_1930 <= {{rowBuffer_q1[702:672]}};
        trunc_ln173_5_reg_1942 <= {{rowBuffer_q1[734:704]}};
        trunc_ln173_s_reg_1878 <= {{rowBuffer_q1[574:544]}};
        trunc_ln1_reg_1953 <= {{rowBuffer_q1[766:736]}};
        trunc_ln_reg_1865 <= {{rowBuffer_q1[542:512]}};
    end
end

always @ (posedge ap_clk) begin
    if (((cmp63_i_reg_2263_pp0_iter9_reg == 1'd0) & (select_ln157_1_reg_1795_pp0_iter9_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        Gxy_var_reg_2283 <= {{grp_fu_1212_p2[31:6]}};
        tmp_4_reg_2313 <= {{grp_fu_1216_p2[31:6]}};
        tmp_5_reg_2348 <= {{grp_fu_1220_p2[31:6]}};
        tmp_9_reg_2393 <= {{grp_fu_1224_p2[31:6]}};
        trunc_ln156_1_reg_2278 <= {{grp_fu_1208_p2[31:6]}};
        trunc_ln3_reg_2273 <= {{grp_fu_1204_p2[31:6]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln164_fu_311_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        add_ln165_reg_1769 <= add_ln165_fu_340_p2;
        icmp_ln165_reg_1757 <= icmp_ln165_fu_326_p2;
        select_ln157_reg_1763 <= select_ln157_fu_332_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((select_ln157_1_reg_1795_pp0_iter4_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        add_ln83_5_reg_2256 <= add_ln83_5_fu_1193_p2;
        cmp63_i_reg_2263 <= cmp63_i_fu_1199_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        ap_loop_init_pp0_iter1_reg <= ap_loop_init;
        icmp_ln165_reg_1757_pp0_iter1_reg <= icmp_ln165_reg_1757;
        rowBuffer_addr_reg_1789 <= j_cast_i_fu_399_p1;
        select_ln157_reg_1763_pp0_iter1_reg <= select_ln157_reg_1763;
        select_ln164_reg_1784 <= select_ln164_fu_392_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln165_reg_1757 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        icmp22_reg_1779 <= icmp22_fu_386_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln165_reg_1757 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        icmp_reg_1774 <= icmp_fu_370_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((select_ln157_1_reg_1795 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        sub_ln68_1_reg_2022 <= sub_ln68_1_fu_821_p2;
        sub_ln68_2_reg_2032 <= sub_ln68_2_fu_833_p2;
        sub_ln68_3_reg_2042 <= sub_ln68_3_fu_846_p2;
        sub_ln68_4_reg_2052 <= sub_ln68_4_fu_859_p2;
        sub_ln68_5_reg_2062 <= sub_ln68_5_fu_872_p2;
        sub_ln68_6_reg_2072 <= sub_ln68_6_fu_885_p2;
        sub_ln68_7_reg_2082 <= sub_ln68_7_fu_898_p2;
        sub_ln68_reg_2007 <= sub_ln68_fu_809_p2;
        sub_ln69_1_reg_2012 <= sub_ln69_1_fu_813_p2;
        sub_ln69_2_reg_2027 <= sub_ln69_2_fu_825_p2;
        sub_ln69_3_reg_2037 <= sub_ln69_3_fu_838_p2;
        sub_ln69_4_reg_2047 <= sub_ln69_4_fu_851_p2;
        sub_ln69_5_reg_2057 <= sub_ln69_5_fu_864_p2;
        sub_ln69_6_reg_2067 <= sub_ln69_6_fu_877_p2;
        sub_ln69_7_reg_2077 <= sub_ln69_7_fu_890_p2;
        sub_ln69_reg_1997 <= sub_ln69_fu_801_p2;
        sub_ln70_1_reg_2017 <= sub_ln70_1_fu_817_p2;
        sub_ln70_reg_2002 <= sub_ln70_fu_805_p2;
        sub_ln82_reg_2100 <= sub_ln82_fu_911_p2;
        sub_ln83_reg_2087 <= sub_ln83_fu_903_p2;
        sub_ln84_1_reg_2105 <= sub_ln84_1_fu_915_p2;
        sub_ln84_2_reg_2112 <= sub_ln84_2_fu_919_p2;
        sub_ln84_3_reg_2119 <= sub_ln84_3_fu_923_p2;
        sub_ln84_4_reg_2126 <= sub_ln84_4_fu_927_p2;
        sub_ln84_5_reg_2133 <= sub_ln84_5_fu_931_p2;
        sub_ln84_6_reg_2140 <= sub_ln84_6_fu_935_p2;
        sub_ln84_reg_2093 <= sub_ln84_fu_907_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((select_ln157_1_fu_407_p3 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        tmp_25_i_reg_1963 <= {{windowBuffer_fu_242[479:448]}};
        tmp_26_i_reg_1969 <= {{windowBuffer_fu_242[511:480]}};
        tmp_29_i_reg_1985 <= {{windowBuffer_fu_242[1503:1472]}};
        tmp_30_i_reg_1991 <= {{windowBuffer_fu_242[1535:1504]}};
        trunc_ln2_reg_1975 <= {{windowBuffer_fu_242[990:960]}};
        trunc_ln54_s_reg_1980 <= {{windowBuffer_fu_242[1022:992]}};
    end
end

always @ (posedge ap_clk) begin
    if (((select_ln157_1_reg_1795_pp0_iter9_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        tmp_7_reg_2353 <= {{grp_fu_1232_p2[31:6]}};
        tmp_8_reg_2383 <= grp_fu_1284_p2[32'd6];
        tmp_s_reg_2388 <= {{grp_fu_1284_p2[31:7]}};
        trunc_ln174_1_reg_2323 <= {{grp_fu_1240_p2[31:6]}};
        trunc_ln174_2_reg_2328 <= {{grp_fu_1252_p2[31:6]}};
        trunc_ln174_3_reg_2333 <= {{grp_fu_1264_p2[31:6]}};
        trunc_ln174_4_reg_2338 <= {{grp_fu_1276_p2[31:6]}};
        trunc_ln174_5_reg_2343 <= {{grp_fu_1288_p2[31:6]}};
        trunc_ln174_6_reg_2378 <= {{grp_fu_1292_p2[31:6]}};
        trunc_ln174_7_reg_2358 <= {{grp_fu_1244_p2[31:6]}};
        trunc_ln174_8_reg_2363 <= {{grp_fu_1256_p2[31:6]}};
        trunc_ln174_9_reg_2368 <= {{grp_fu_1268_p2[31:6]}};
        trunc_ln174_s_reg_2373 <= {{grp_fu_1280_p2[31:6]}};
        trunc_ln206_1_reg_2293 <= {{grp_fu_1248_p2[31:6]}};
        trunc_ln206_2_reg_2298 <= {{grp_fu_1260_p2[31:6]}};
        trunc_ln206_3_reg_2303 <= {{grp_fu_1272_p2[31:6]}};
        trunc_ln206_5_reg_2308 <= {{grp_fu_1296_p2[31:6]}};
        trunc_ln4_reg_2288 <= {{grp_fu_1236_p2[31:6]}};
        trunc_ln5_reg_2318 <= {{grp_fu_1228_p2[31:6]}};
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (select_ln157_1_fu_407_p3 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        windowBuffer_fu_242 <= windowBuffer_1_fu_769_p7;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter11 == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (select_ln157_1_reg_1795_pp0_iter10_reg == 1'd0))) begin
        GxxStream_blk_n = GxxStream_full_n;
    end else begin
        GxxStream_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter11 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (select_ln157_1_reg_1795_pp0_iter10_reg == 1'd0))) begin
        GxxStream_write = 1'b1;
    end else begin
        GxxStream_write = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter11 == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (select_ln157_1_reg_1795_pp0_iter10_reg == 1'd0))) begin
        GxyStream_blk_n = GxyStream_full_n;
    end else begin
        GxyStream_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter11 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (select_ln157_1_reg_1795_pp0_iter10_reg == 1'd0))) begin
        GxyStream_write = 1'b1;
    end else begin
        GxyStream_write = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter11 == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (select_ln157_1_reg_1795_pp0_iter10_reg == 1'd0))) begin
        GyyStream_blk_n = GyyStream_full_n;
    end else begin
        GyyStream_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter11 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (select_ln157_1_reg_1795_pp0_iter10_reg == 1'd0))) begin
        GyyStream_write = 1'b1;
    end else begin
        GyyStream_write = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln164_fu_311_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter10_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_start_int == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter11 == 1'b0) & (ap_enable_reg_pp0_iter10 == 1'b0) & (ap_enable_reg_pp0_iter9 == 1'b0) & (ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if ((1'b0 == ap_block_pp0_stage0)) begin
        if ((1'b1 == ap_condition_591)) begin
            ap_sig_allocacmp_i_load = 8'd0;
        end else if ((ap_enable_reg_pp0_iter2 == 1'b1)) begin
            ap_sig_allocacmp_i_load = select_ln164_reg_1784;
        end else begin
            ap_sig_allocacmp_i_load = i_fu_234;
        end
    end else begin
        ap_sig_allocacmp_i_load = i_fu_234;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_sig_allocacmp_indvar_flatten_load = 12'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten_load = indvar_flatten_fu_238;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        if (((ap_loop_init == 1'b1) & (ap_start_int == 1'b1))) begin
            ap_sig_allocacmp_j_load = 5'd0;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            ap_sig_allocacmp_j_load = add_ln165_reg_1769;
        end else begin
            ap_sig_allocacmp_j_load = j_fu_230;
        end
    end else begin
        ap_sig_allocacmp_j_load = j_fu_230;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        grp_fu_1204_ce = 1'b1;
    end else begin
        grp_fu_1204_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        grp_fu_1208_ce = 1'b1;
    end else begin
        grp_fu_1208_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        grp_fu_1212_ce = 1'b1;
    end else begin
        grp_fu_1212_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        grp_fu_1216_ce = 1'b1;
    end else begin
        grp_fu_1216_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        grp_fu_1220_ce = 1'b1;
    end else begin
        grp_fu_1220_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        grp_fu_1224_ce = 1'b1;
    end else begin
        grp_fu_1224_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        grp_fu_1228_ce = 1'b1;
    end else begin
        grp_fu_1228_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        grp_fu_1232_ce = 1'b1;
    end else begin
        grp_fu_1232_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        grp_fu_1236_ce = 1'b1;
    end else begin
        grp_fu_1236_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        grp_fu_1240_ce = 1'b1;
    end else begin
        grp_fu_1240_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        grp_fu_1244_ce = 1'b1;
    end else begin
        grp_fu_1244_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        grp_fu_1248_ce = 1'b1;
    end else begin
        grp_fu_1248_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        grp_fu_1252_ce = 1'b1;
    end else begin
        grp_fu_1252_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        grp_fu_1256_ce = 1'b1;
    end else begin
        grp_fu_1256_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        grp_fu_1260_ce = 1'b1;
    end else begin
        grp_fu_1260_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        grp_fu_1264_ce = 1'b1;
    end else begin
        grp_fu_1264_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        grp_fu_1268_ce = 1'b1;
    end else begin
        grp_fu_1268_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        grp_fu_1272_ce = 1'b1;
    end else begin
        grp_fu_1272_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        grp_fu_1276_ce = 1'b1;
    end else begin
        grp_fu_1276_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        grp_fu_1280_ce = 1'b1;
    end else begin
        grp_fu_1280_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        grp_fu_1284_ce = 1'b1;
    end else begin
        grp_fu_1284_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        grp_fu_1288_ce = 1'b1;
    end else begin
        grp_fu_1288_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        grp_fu_1292_ce = 1'b1;
    end else begin
        grp_fu_1292_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        grp_fu_1296_ce = 1'b1;
    end else begin
        grp_fu_1296_ce = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0))) begin
        inStream_blk_n = inStream_empty_n;
    end else begin
        inStream_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        inStream_read = 1'b1;
    end else begin
        inStream_read = 1'b0;
    end
end

always @ (*) begin
    if (((start_full_n == 1'b0) & (start_once_reg == 1'b0))) begin
        real_start = 1'b0;
    end else begin
        real_start = ap_start;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        rowBuffer_ce0 = 1'b1;
    end else begin
        rowBuffer_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        rowBuffer_ce1 = 1'b1;
    end else begin
        rowBuffer_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        rowBuffer_we0 = 1'b1;
    end else begin
        rowBuffer_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((real_start == 1'b1) & (start_once_reg == 1'b0))) begin
        start_write = 1'b1;
    end else begin
        start_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign Gx_var_1_fu_968_p2 = (add_ln69_8_fu_963_p2 + sub_ln68_1_reg_2022);

assign Gx_var_fu_951_p2 = (add_ln69_6_fu_946_p2 + sub_ln68_reg_2007);

assign GxxStream_din = tmp_2_fu_1584_p15;

assign Gxx_sroa_0_0141_i_fu_1560_p3 = ((cmp63_i_reg_2263_pp0_iter10_reg[0:0] == 1'b1) ? 26'd0 : trunc_ln3_reg_2273);

assign GxyStream_din = $signed(tmp_13_fu_1709_p6);

assign Gxy_sroa_0_0143_i_fu_1548_p3 = ((cmp63_i_reg_2263_pp0_iter10_reg[0:0] == 1'b1) ? 26'd0 : Gxy_var_reg_2283);

assign Gy_var_1_fu_1099_p2 = (add_ln83_8_fu_1095_p2 + shl_ln83_1_fu_1090_p2);

assign Gy_var_fu_1085_p2 = (add_ln83_6_fu_1080_p2 + sub_ln82_reg_2100);

assign GyyStream_din = tmp_6_fu_1621_p15;

assign Gyy_sroa_0_0142_i_fu_1554_p3 = ((cmp63_i_reg_2263_pp0_iter10_reg[0:0] == 1'b1) ? 26'd0 : trunc_ln156_1_reg_2278);

assign add_ln164_1_fu_354_p2 = (ap_sig_allocacmp_i_load + 8'd1);

assign add_ln164_fu_317_p2 = (ap_sig_allocacmp_indvar_flatten_load + 12'd1);

assign add_ln165_fu_340_p2 = (select_ln157_fu_332_p3 + 5'd1);

assign add_ln69_10_fu_980_p2 = (tmp_10_i_reg_1884_pp0_iter3_reg + shl_ln69_2_fu_973_p3);

assign add_ln69_11_fu_997_p2 = (tmp_12_i_reg_1897_pp0_iter3_reg + shl_ln69_3_fu_990_p3);

assign add_ln69_12_fu_1014_p2 = (tmp_14_i_reg_1910_pp0_iter3_reg + shl_ln69_4_fu_1007_p3);

assign add_ln69_13_fu_1031_p2 = (tmp_16_i_reg_1923_pp0_iter3_reg + shl_ln69_5_fu_1024_p3);

assign add_ln69_14_fu_1048_p2 = (tmp_18_i_reg_1936_pp0_iter3_reg + shl_ln69_6_fu_1041_p3);

assign add_ln69_15_fu_1065_p2 = (tmp_20_i_reg_1947_pp0_iter3_reg + shl_ln69_7_fu_1058_p3);

assign add_ln69_1_fu_1002_p2 = (add_ln69_11_fu_997_p2 + sub_ln68_3_reg_2042);

assign add_ln69_2_fu_1019_p2 = (add_ln69_12_fu_1014_p2 + sub_ln68_4_reg_2052);

assign add_ln69_3_fu_1036_p2 = (add_ln69_13_fu_1031_p2 + sub_ln68_5_reg_2062);

assign add_ln69_4_fu_1053_p2 = (add_ln69_14_fu_1048_p2 + sub_ln68_6_reg_2072);

assign add_ln69_5_fu_1070_p2 = (add_ln69_15_fu_1065_p2 + sub_ln68_7_reg_2082);

assign add_ln69_6_fu_946_p2 = (shl_ln_fu_939_p3 + sub_ln70_reg_2002);

assign add_ln69_8_fu_963_p2 = (shl_ln69_1_fu_956_p3 + sub_ln70_1_reg_2017);

assign add_ln69_fu_985_p2 = (add_ln69_10_fu_980_p2 + sub_ln68_2_reg_2032);

assign add_ln83_10_fu_1110_p2 = (sub_ln84_reg_2093 + sub_ln84_2_reg_2112);

assign add_ln83_11_fu_1125_p2 = (sub_ln84_1_reg_2105 + sub_ln84_3_reg_2119);

assign add_ln83_12_fu_1140_p2 = (sub_ln84_2_reg_2112 + sub_ln84_4_reg_2126);

assign add_ln83_13_fu_1155_p2 = (sub_ln84_3_reg_2119 + sub_ln84_5_reg_2133);

assign add_ln83_14_fu_1170_p2 = (sub_ln84_4_reg_2126 + sub_ln84_6_reg_2140);

assign add_ln83_1_fu_1129_p2 = (add_ln83_11_fu_1125_p2 + shl_ln83_3_fu_1120_p2);

assign add_ln83_2_fu_1144_p2 = (add_ln83_12_fu_1140_p2 + shl_ln83_4_fu_1135_p2);

assign add_ln83_3_fu_1159_p2 = (add_ln83_13_fu_1155_p2 + shl_ln83_5_fu_1150_p2);

assign add_ln83_4_fu_1174_p2 = (add_ln83_14_fu_1170_p2 + shl_ln83_6_fu_1165_p2);

assign add_ln83_5_fu_1193_p2 = (sub_ln82_1_fu_1189_p2 + shl_ln83_7_fu_1184_p2);

assign add_ln83_6_fu_1080_p2 = (shl_ln83_fu_1075_p2 + sub_ln84_reg_2093);

assign add_ln83_8_fu_1095_p2 = (sub_ln83_reg_2087 + sub_ln84_1_reg_2105);

assign add_ln83_fu_1114_p2 = (add_ln83_10_fu_1110_p2 + shl_ln83_2_fu_1105_p2);

assign add_ln84_fu_1180_p2 = (sub_ln84_5_reg_2133 + tmp_3_i_reg_1852_pp0_iter3_reg);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = ((ap_done_reg == 1'b1) | ((inStream_empty_n == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((ap_done_reg == 1'b1) & (ap_start_int == 1'b1)) | ((ap_enable_reg_pp0_iter11 == 1'b1) & (((1'b0 == GxxStream_full_n) & (select_ln157_1_reg_1795_pp0_iter10_reg == 1'd0)) | ((1'b0 == GxyStream_full_n) & (select_ln157_1_reg_1795_pp0_iter10_reg == 1'd0)) | ((1'b0 == GyyStream_full_n) & (select_ln157_1_reg_1795_pp0_iter10_reg == 1'd0)))));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((ap_done_reg == 1'b1) | ((inStream_empty_n == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((ap_done_reg == 1'b1) & (ap_start_int == 1'b1)) | ((ap_enable_reg_pp0_iter11 == 1'b1) & (((1'b0 == GxxStream_full_n) & (select_ln157_1_reg_1795_pp0_iter10_reg == 1'd0)) | ((1'b0 == GxyStream_full_n) & (select_ln157_1_reg_1795_pp0_iter10_reg == 1'd0)) | ((1'b0 == GyyStream_full_n) & (select_ln157_1_reg_1795_pp0_iter10_reg == 1'd0)))));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((ap_done_reg == 1'b1) | ((inStream_empty_n == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((ap_done_reg == 1'b1) & (ap_start_int == 1'b1)) | ((ap_enable_reg_pp0_iter11 == 1'b1) & (((1'b0 == GxxStream_full_n) & (select_ln157_1_reg_1795_pp0_iter10_reg == 1'd0)) | ((1'b0 == GxyStream_full_n) & (select_ln157_1_reg_1795_pp0_iter10_reg == 1'd0)) | ((1'b0 == GyyStream_full_n) & (select_ln157_1_reg_1795_pp0_iter10_reg == 1'd0)))));
end

assign ap_block_state10_pp0_stage0_iter9 = ~(1'b1 == 1'b1);

assign ap_block_state11_pp0_stage0_iter10 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state12_pp0_stage0_iter11 = (((1'b0 == GxxStream_full_n) & (select_ln157_1_reg_1795_pp0_iter10_reg == 1'd0)) | ((1'b0 == GxyStream_full_n) & (select_ln157_1_reg_1795_pp0_iter10_reg == 1'd0)) | ((1'b0 == GyyStream_full_n) & (select_ln157_1_reg_1795_pp0_iter10_reg == 1'd0)));
end

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = (ap_done_reg == 1'b1);
end

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state3_pp0_stage0_iter2 = (inStream_empty_n == 1'b0);
end

assign ap_block_state4_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter4 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage0_iter5 = ~(1'b1 == 1'b1);

assign ap_block_state7_pp0_stage0_iter6 = ~(1'b1 == 1'b1);

assign ap_block_state8_pp0_stage0_iter7 = ~(1'b1 == 1'b1);

assign ap_block_state9_pp0_stage0_iter8 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_condition_577 = ((ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001));
end

always @ (*) begin
    ap_condition_591 = ((ap_loop_init_pp0_iter1_reg == 1'b1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = internal_ap_ready;

assign cmp63_i_fu_1199_p2 = ((select_ln157_reg_1763_pp0_iter4_reg == 5'd0) ? 1'b1 : 1'b0);

assign empty_34_fu_1615_p3 = ((cmp63_i_reg_2263_pp0_iter10_reg[0:0] == 1'b1) ? 26'd0 : tmp_5_reg_2348);

assign empty_35_fu_1658_p3 = ((cmp63_i_reg_2263_pp0_iter10_reg[0:0] == 1'b1) ? 26'd0 : tmp_9_reg_2393);

assign empty_fu_1578_p3 = ((cmp63_i_reg_2263_pp0_iter10_reg[0:0] == 1'b1) ? 26'd0 : tmp_4_reg_2313);

assign icmp22_fu_386_p2 = ((tmp_1_fu_376_p4 == 7'd0) ? 1'b1 : 1'b0);

assign icmp_fu_370_p2 = ((tmp_fu_360_p4 == 7'd0) ? 1'b1 : 1'b0);

assign icmp_ln164_fu_311_p2 = ((ap_sig_allocacmp_indvar_flatten_load == 12'd2048) ? 1'b1 : 1'b0);

assign icmp_ln165_fu_326_p2 = ((ap_sig_allocacmp_j_load == 5'd16) ? 1'b1 : 1'b0);

assign j_cast_i_fu_399_p1 = select_ln157_reg_1763;

assign obj_var_fu_412_p1 = inStream_dout[31:0];

assign or_ln_fu_1664_p3 = {{empty_35_fu_1658_p3}, {sext_ln156_fu_1574_p1}};

assign rowBuffer_address1 = j_cast_i_fu_399_p1;

assign rowBuffer_d0 = {{tmp_3_reg_1799}, {tmp_24_i_reg_1958}};

assign select_ln157_1_fu_407_p3 = ((icmp_ln165_reg_1757_pp0_iter1_reg[0:0] == 1'b1) ? icmp_reg_1774 : icmp22_reg_1779);

assign select_ln157_fu_332_p3 = ((icmp_ln165_fu_326_p2[0:0] == 1'b1) ? 5'd0 : ap_sig_allocacmp_j_load);

assign select_ln164_fu_392_p3 = ((icmp_ln165_reg_1757[0:0] == 1'b1) ? add_ln164_1_fu_354_p2 : ap_sig_allocacmp_i_load);

assign sext_ln156_fu_1574_p1 = $signed(Gxy_sroa_0_0143_i_fu_1548_p3);

assign sext_ln174_1_fu_1655_p1 = $signed(tmp_s_reg_2388);

assign sext_ln174_2_fu_1672_p1 = $signed(or_ln_fu_1664_p3);

assign sext_ln174_3_fu_1683_p1 = $signed(tmp_10_fu_1676_p3);

assign sext_ln174_4_fu_1694_p1 = $signed(tmp_11_fu_1687_p3);

assign sext_ln174_5_fu_1705_p1 = $signed(tmp_12_fu_1698_p3);

assign sext_ln174_fu_1652_p1 = $signed(trunc_ln4_reg_2288);

assign shl_ln69_1_fu_956_p3 = {{sub_ln69_1_reg_2012}, {1'd0}};

assign shl_ln69_2_fu_973_p3 = {{sub_ln69_2_reg_2027}, {1'd0}};

assign shl_ln69_3_fu_990_p3 = {{sub_ln69_3_reg_2037}, {1'd0}};

assign shl_ln69_4_fu_1007_p3 = {{sub_ln69_4_reg_2047}, {1'd0}};

assign shl_ln69_5_fu_1024_p3 = {{sub_ln69_5_reg_2057}, {1'd0}};

assign shl_ln69_6_fu_1041_p3 = {{sub_ln69_6_reg_2067}, {1'd0}};

assign shl_ln69_7_fu_1058_p3 = {{sub_ln69_7_reg_2077}, {1'd0}};

assign shl_ln83_1_fu_1090_p2 = sub_ln84_reg_2093 << 32'd1;

assign shl_ln83_2_fu_1105_p2 = sub_ln84_1_reg_2105 << 32'd1;

assign shl_ln83_3_fu_1120_p2 = sub_ln84_2_reg_2112 << 32'd1;

assign shl_ln83_4_fu_1135_p2 = sub_ln84_3_reg_2119 << 32'd1;

assign shl_ln83_5_fu_1150_p2 = sub_ln84_4_reg_2126 << 32'd1;

assign shl_ln83_6_fu_1165_p2 = sub_ln84_5_reg_2133 << 32'd1;

assign shl_ln83_7_fu_1184_p2 = sub_ln84_6_reg_2140_pp0_iter4_reg << 32'd1;

assign shl_ln83_fu_1075_p2 = sub_ln83_reg_2087 << 32'd1;

assign shl_ln_fu_939_p3 = {{sub_ln69_reg_1997}, {1'd0}};

assign start_out = real_start;

assign sub_ln68_1_fu_821_p2 = (tmp_6_i_reg_1871 - tmp_26_i_reg_1969);

assign sub_ln68_2_fu_833_p2 = (sub_ln70_2_fu_829_p2 - tmp_4_i_reg_1858);

assign sub_ln68_3_fu_846_p2 = (sub_ln70_3_fu_842_p2 - tmp_6_i_reg_1871);

assign sub_ln68_4_fu_859_p2 = (sub_ln70_4_fu_855_p2 - tmp_10_i_reg_1884);

assign sub_ln68_5_fu_872_p2 = (sub_ln70_5_fu_868_p2 - tmp_12_i_reg_1897);

assign sub_ln68_6_fu_885_p2 = (sub_ln70_6_fu_881_p2 - tmp_14_i_reg_1910);

assign sub_ln68_7_fu_898_p2 = (sub_ln70_7_fu_894_p2 - tmp_16_i_reg_1923);

assign sub_ln68_fu_809_p2 = (tmp_4_i_reg_1858 - tmp_25_i_reg_1963);

assign sub_ln69_1_fu_813_p2 = (trunc_ln173_s_reg_1878 - trunc_ln54_s_reg_1980);

assign sub_ln69_2_fu_825_p2 = (trunc_ln173_1_reg_1891 - trunc_ln_reg_1865);

assign sub_ln69_3_fu_838_p2 = (trunc_ln173_2_reg_1904 - trunc_ln173_s_reg_1878);

assign sub_ln69_4_fu_851_p2 = (trunc_ln173_3_reg_1917 - trunc_ln173_1_reg_1891);

assign sub_ln69_5_fu_864_p2 = (trunc_ln173_4_reg_1930 - trunc_ln173_2_reg_1904);

assign sub_ln69_6_fu_877_p2 = (trunc_ln173_5_reg_1942 - trunc_ln173_3_reg_1917);

assign sub_ln69_7_fu_890_p2 = (trunc_ln1_reg_1953 - trunc_ln173_4_reg_1930);

assign sub_ln69_fu_801_p2 = (trunc_ln_reg_1865 - trunc_ln2_reg_1975);

assign sub_ln70_1_fu_817_p2 = (obj_var_1_reg_1811 - tmp_30_i_reg_1991);

assign sub_ln70_2_fu_829_p2 = (tmp_8_i_reg_1818 - obj_var_reg_1804);

assign sub_ln70_3_fu_842_p2 = (tmp_9_i_reg_1825 - obj_var_1_reg_1811);

assign sub_ln70_4_fu_855_p2 = (tmp_i_reg_1832 - tmp_8_i_reg_1818);

assign sub_ln70_5_fu_868_p2 = (tmp_1_i_reg_1839 - tmp_9_i_reg_1825);

assign sub_ln70_6_fu_881_p2 = (tmp_2_i_reg_1846 - tmp_i_reg_1832);

assign sub_ln70_7_fu_894_p2 = (tmp_3_i_reg_1852 - tmp_1_i_reg_1839);

assign sub_ln70_fu_805_p2 = (obj_var_reg_1804 - tmp_29_i_reg_1985);

assign sub_ln82_1_fu_1189_p2 = (add_ln84_reg_2251 - tmp_20_i_reg_1947_pp0_iter4_reg);

assign sub_ln82_fu_911_p2 = (tmp_29_i_reg_1985 - tmp_25_i_reg_1963);

assign sub_ln83_fu_903_p2 = (tmp_30_i_reg_1991 - tmp_26_i_reg_1969);

assign sub_ln84_1_fu_915_p2 = (obj_var_1_reg_1811 - tmp_6_i_reg_1871);

assign sub_ln84_2_fu_919_p2 = (tmp_8_i_reg_1818 - tmp_10_i_reg_1884);

assign sub_ln84_3_fu_923_p2 = (tmp_9_i_reg_1825 - tmp_12_i_reg_1897);

assign sub_ln84_4_fu_927_p2 = (tmp_i_reg_1832 - tmp_14_i_reg_1910);

assign sub_ln84_5_fu_931_p2 = (tmp_1_i_reg_1839 - tmp_16_i_reg_1923);

assign sub_ln84_6_fu_935_p2 = (tmp_2_i_reg_1846 - tmp_18_i_reg_1936);

assign sub_ln84_fu_907_p2 = (obj_var_reg_1804 - tmp_4_i_reg_1858);

assign tmp_10_fu_1676_p3 = {{trunc_ln206_1_reg_2293}, {sext_ln174_fu_1652_p1}};

assign tmp_11_fu_1687_p3 = {{trunc_ln206_2_reg_2298}, {sext_ln174_3_fu_1683_p1}};

assign tmp_12_fu_1698_p3 = {{trunc_ln206_3_reg_2303}, {sext_ln174_4_fu_1694_p1}};

assign tmp_13_fu_1709_p6 = {{{{{trunc_ln206_5_reg_2308}, {sext_ln174_1_fu_1655_p1}}, {tmp_8_reg_2383}}, {sext_ln174_5_fu_1705_p1}}, {sext_ln174_2_fu_1672_p1}};

assign tmp_1_fu_376_p4 = {{ap_sig_allocacmp_i_load[7:1]}};

assign tmp_2_fu_1584_p15 = {{{{{{{{{{{{{{trunc_ln174_5_reg_2343}, {6'd0}}, {trunc_ln174_4_reg_2338}}, {6'd0}}, {trunc_ln174_3_reg_2333}}, {6'd0}}, {trunc_ln174_2_reg_2328}}, {6'd0}}, {trunc_ln174_1_reg_2323}}, {6'd0}}, {trunc_ln5_reg_2318}}, {6'd0}}, {empty_fu_1578_p3}}, {zext_ln156_fu_1566_p1}};

assign tmp_31_i_fu_719_p4 = {{windowBuffer_fu_242[1535:1280]}};

assign tmp_32_i_fu_729_p4 = {{rowBuffer_q1[767:512]}};

assign tmp_33_i_fu_739_p4 = {{windowBuffer_fu_242[1023:768]}};

assign tmp_34_i_fu_749_p4 = {{rowBuffer_q1[511:256]}};

assign tmp_35_i_fu_759_p4 = {{windowBuffer_fu_242[511:256]}};

assign tmp_6_fu_1621_p15 = {{{{{{{{{{{{{{trunc_ln174_6_reg_2378}, {6'd0}}, {trunc_ln174_s_reg_2373}}, {6'd0}}, {trunc_ln174_9_reg_2368}}, {6'd0}}, {trunc_ln174_8_reg_2363}}, {6'd0}}, {trunc_ln174_7_reg_2358}}, {6'd0}}, {tmp_7_reg_2353}}, {6'd0}}, {empty_34_fu_1615_p3}}, {zext_ln156_1_fu_1570_p1}};

assign tmp_fu_360_p4 = {{add_ln164_1_fu_354_p2[7:1]}};

assign windowBuffer_1_fu_769_p7 = {{{{{{inStream_dout}, {tmp_31_i_fu_719_p4}}, {tmp_32_i_fu_729_p4}}, {tmp_33_i_fu_739_p4}}, {tmp_34_i_fu_749_p4}}, {tmp_35_i_fu_759_p4}};

assign zext_ln156_1_fu_1570_p1 = Gyy_sroa_0_0142_i_fu_1554_p3;

assign zext_ln156_fu_1566_p1 = Gxx_sroa_0_0141_i_fu_1560_p3;

endmodule //harris_sobel
